/* ============================================================
   TacticLab 内容库
   坐标约定：x 0-100（左→右，己方进攻方向），y 0-100（上→下）
   球员 team：own 己方 / gk 己方门将 / opp 对方 / oppgk 对方门将 / ball 球
   动作 type：run 跑位(虚线) / pass 传球(实线) / carry 运球(实粗) / shot 射门(橙粗)
   依据标签 refs → 见 REFS
   ============================================================ */
"use strict";

/* ---------- 权威依据 ---------- */
const REFS = [
  { id:"fa-dna", name:"英格兰 DNA（England DNA）", org:"The FA · England Football Learning",
    url:"https://learn.englandfootball.com", tag:"英格兰",
    note:"英格兰各级国字号统一的踢球与执教哲学，五大支柱：我们是谁 / 我们怎么踢 / 未来的英格兰球员 / 我们怎么执教 / 我们怎么支持。本应用的进攻理念（控球、创造、勇敢）与执教流程（引导提问）均以此为准。" },
  { id:"fa-cap", name:"六大核心能力", org:"The FA · England Football Learning",
    url:"https://learn.englandfootball.com/articles-and-resources/coaching", tag:"英格兰",
    note:"Scanning 观察 · Timing 时机 · Movement 跑动 · Positioning 站位 · Deception 伪装 · Techniques 技术。本应用每个战术步骤的“指导要点”都尽量落到这六项能力上，而不是空喊口号。" },
  { id:"fa-4corner", name:"四角模型（Four Corner Model）", org:"The FA 教练员培训体系",
    url:"https://learn.englandfootball.com", tag:"英格兰",
    note:"技术 / 战术 / 身体 / 心理社交 四角同训。本应用生成的训练课，每项练习至少覆盖两角，并在指导要点中注明。" },
  { id:"fa-fp", name:"基础阶段要求（5-11 岁）", org:"The FA · Age Phase Priorities",
    url:"https://www.thefa.com", tag:"英格兰",
    note:"持球时：Stay on the ball, master the ball（先敢于持球，再谈配合）；Excite with the ball。U8-U10 训练以大量触球、1v1、乐趣为第一优先级，讲解不超过 20 秒。" },
  { id:"rfef-8", name:"西班牙基层赛制（Fútbol 8）", org:"RFEF 及大区足协竞赛规程",
    url:"https://rfef.es", tag:"西班牙",
    note:"西班牙 8-12 岁（Benjamín / Alevín 组）长期采用 7/8 人制小场地赛制，目标就是让每名球员在“真实比赛形状”里获得更多触球与决策。本应用八人制内容对应西班牙 alevín 组训练逻辑。" },
  { id:"laliga-pos", name:"位置足球与 Rondo", org:"LaLiga 青训方法论 · 拉玛西亚传统",
    url:"https://www.laliga.com", tag:"西班牙",
    note:"抢圈（Rondo）、位置轮转、穿线传球（entre líneas）、以人数围绕球——西班牙青训的传控基因。技术练习模块大量采用 rondo 与位置游戏。" },
  { id:"fifa-manual", name:"FIFA 五人制足球教练手册", org:"FIFA 官方出版物",
    url:"https://www.fifa.com", tag:"五人制",
    note:"五人制专项体系：4-0 / 3-1 / 2-2 / 1-2-1 轮转体系、支点（Pivo）运用、快速攻防转换。本应用五人制阵型与进攻套路的骨架以此为准。" },
  { id:"fifa-laws", name:"FIFA 五人制竞赛规则", org:"FIFA",
    url:"https://www.fifa.com", tag:"五人制",
    note:"40×20m 场地、4 秒发球、门将出球后在本方半场不得再触球（除非球过半场或对方触球）、累积犯规。所有五人制套路均已核对规则合法性。" },
  { id:"jfa", name:"JFA 训练图解体系", org:"日本足球协会（JFA）指导者培养材料",
    url:"https://www.jfa.jp", tag:"日本",
    note:"日本青训教案以精细的器材布置图、时间-人数-器材表头和明确的练习目标著称。本应用教案的布置图与总览表结构参考此格式。" },
  { id:"uefa-tg", name:"UEFA Training Ground", org:"UEFA",
    url:"https://www.uefa.com", tag:"欧洲",
    note:"欧足联官方训练与技战术资源库，用于交叉印证压迫触发器、由守转攻等主题的通行做法。" },
];
const refName = id => (REFS.find(r => r.id === id) || {}).name || id;
const refTag  = id => (REFS.find(r => r.id === id) || {}).tag || "依据";

/* ---------- 五人制阵型 ---------- */
const FUTSAL_FORMATIONS = [
  {
    id:"f-121", gameType:"futsal", name:"1-2-1 菱形", en:"Diamond",
    desc:"五人制最经典的基石阵型：一名后卫（Fixo）、两名边路（Ala）、一名支点（Pivo），天然形成菱形传球网络，攻守转换顺畅。",
    roles:[
      { num:"1", label:"门将", desc:"第十名外场球员：出球是进攻第一发起，站位随时上提。" },
      { num:"4", label:"Fixo 后卫", desc:"出球组织者，横向调度，防守时殿后保护。" },
      { num:"7/10", label:"Ala 边路", desc:"两翼发动机：内收配合、套边推进、回防落位。" },
      { num:"9", label:"Pivo 支点", desc:"顶在对方防线身前的柱子：要位、回做、做墙。" },
    ],
    pros:["攻守平衡，纵向连接最快","菱形四点天然互相保护","是学习一切轮转的基础"],
    cons:["对 Ala 的往返体能要求极高","Pivo 被盯死时中路容易拥堵","两翼身后是对方反击通道"],
    use:"青训首选基础阵型；对手打 2-2 时中路占优。",
    refs:["fifa-manual","fa-cap"],
    players:[
      {id:1,num:1,team:"gk",x:8,y:50,label:"GK"},
      {id:4,num:4,team:"own",x:24,y:50,label:"Fixo"},
      {id:7,num:7,team:"own",x:46,y:22,label:"Ala"},
      {id:10,num:10,team:"own",x:46,y:78,label:"Ala"},
      {id:9,num:9,team:"own",x:70,y:50,label:"Pivo"},
    ],
  },
  {
    id:"f-40", gameType:"futsal", name:"4-0 轮转", en:"Four-Zero Rotation",
    desc:"四名外场球员排成一线，通过持续轮转让防守始终无法稳定对位。五人制最复杂也最成熟的进攻体系，西班牙、巴西与伊朗国家队的常用武器。",
    roles:[
      { num:"1", label:"门将", desc:"拖后保护与出球，随时提醒轮转方向，是 4-0 的防守底线与进攻第一发起点。" },
      { num:"—", label:"四外场", desc:"无固定位置：有人带球、有人下拉、有人轮补，全部角色流动，任何位置都可能瞬间变成发起人。" },
    ],
    pros:["持续轮转让盯人防守不断换人错位","任何位置都能形成 2v1","被逼抢时永远有接应点"],
    cons:["学习成本最高，需要长期训练","轮转断档瞬间易被反击","对球员无球跑动理解力要求高"],
    use:"技术较好、训练量有保证的队伍；破解全场紧逼。",
    refs:["fifa-manual","laliga-pos"],
    players:[
      {id:1,num:1,team:"gk",x:8,y:50,label:"GK"},
      {id:2,num:2,team:"own",x:24,y:50,label:""},
      {id:3,num:3,team:"own",x:42,y:24,label:""},
      {id:4,num:4,team:"own",x:42,y:76,label:""},
      {id:5,num:5,team:"own",x:60,y:50,label:""},
    ],
  },
  {
    id:"f-22", gameType:"futsal", name:"2-2 方块", en:"Square",
    desc:"两名后卫 + 两名前锋的方块结构，覆盖均衡、易于理解，是年轻队伍和刚建队队伍的稳妥起点。",
    roles:[
      { num:"1", label:"门将", desc:"指挥方块整体横移，方块散架的第一责任人在他的口令上。" },
      { num:"4/5", label:"双后卫", desc:"横向拉开出球，保持互相保护距离；一人上前则另一人立即回收补位。" },
      { num:"9/10", label:"双前锋", desc:"压住对方防线，接长传与二点球；一人背身做轴时另一人反跑身后。" },
    ],
    pros:["结构简单、覆盖均衡、易教易学","由守转攻时两点直接顶前","边路空当天然存在利于突破"],
    cons:["中路只有两脚，人数优势不明显","进攻套路相对有限、易被预判","对阵 1-2-1 时中场被打穿"],
    use:"初学队伍、U8-U10 打基础；比赛落后的简单强攻。",
    refs:["fifa-manual"],
    players:[
      {id:1,num:1,team:"gk",x:8,y:50,label:"GK"},
      {id:4,num:4,team:"own",x:24,y:32,label:""},
      {id:5,num:5,team:"own",x:24,y:68,label:""},
      {id:9,num:9,team:"own",x:50,y:32,label:""},
      {id:10,num:10,team:"own",x:50,y:68,label:""},
    ],
  },
  {
    id:"f-31", gameType:"futsal", name:"3-1 单支点", en:"Three-One",
    desc:"三名后卫加一名支点：出球点多、破紧逼利器，把组织权交给 Pivo 一人做轴；门将作为第四名出球人参与，是高压时代的标准答案。",
    roles:[
      { num:"1", label:"门将", desc:"作为第四名「后卫」参与构建，邀请对方上抢后再转移，破解第一波压迫。" },
      { num:"2/4/5", label:"三后卫", desc:"宽站位拉开，一人持球两人给角度；持球人抬头即有两个出球点。" },
      { num:"9", label:"Pivo", desc:"压住对方最后线做轴：背身回做、转身反跑、吸引包夹后分弱侧。" },
    ],
    pros:["对全场紧逼出球点最多","三后卫横向覆盖反击通道","Pivo 单点战术清晰"],
    cons:["中场衔接弱，前后场易脱节","依赖 Pivo 的背身质量","进攻推进慢时对手能从容落位"],
    use:"对手高压逼抢时；需要控制节奏的比赛。",
    refs:["fifa-manual","fifa-laws"],
    players:[
      {id:1,num:1,team:"gk",x:8,y:50,label:"GK"},
      {id:2,num:2,team:"own",x:20,y:24,label:""},
      {id:4,num:4,team:"own",x:17,y:50,label:""},
      {id:5,num:5,team:"own",x:20,y:76,label:""},
      {id:9,num:9,team:"own",x:66,y:50,label:"Pivo"},
    ],
  },
  {
    id:"f-211", gameType:"futsal", name:"2-1-1 变形菱形", en:"Two-One-One",
    desc:"菱形的防守变体：双后卫殿后互相保护，一名自由边路居中串联，支点顶前——牺牲部分进攻宽度，换取防守稳定性。",
    roles:[
      { num:"4/5", label:"双 Fixo", desc:"横向互相保护，一人上抢一人补位；两人之间的默契就是这条防线的全部。" },
      { num:"8", label:"自由 Ala", desc:"居中串联前后场，进攻的第一接应点；被盯死前多转移，被盯死后说明队友有空当。" },
      { num:"9", label:"Pivo", desc:"顶住对方防线做轴与反跑；领先时回撤参与控球，帮全队消化时间。" },
    ],
    pros:["双后卫结构防守最稳","适合保护领先优势","自由人角色培养决策能力"],
    cons:["进攻宽度不足，依赖边路个人突破","自由人被盯死则前后脱节","阵地战套路相对单一"],
    use:"领先保护比分；对阵攻击强队时的稳健选择。",
    refs:["fifa-manual"],
    players:[
      {id:1,num:1,team:"gk",x:8,y:50,label:"GK"},
      {id:4,num:4,team:"own",x:26,y:36,label:""},
      {id:5,num:5,team:"own",x:26,y:64,label:""},
      {id:8,num:8,team:"own",x:48,y:50,label:"8"},
      {id:9,num:9,team:"own",x:70,y:50,label:"9"},
    ],
  },
];

/* ---------- 八人制阵型 ---------- */
const FIELD8_FORMATIONS = [
  {
    id:"s-331", gameType:"field8", name:"3-3-1", en:"Three-Three-One",
    desc:"八人制最均衡的结构：三中卫保宽度与深度，三中场连接前后，单前锋压制对方防线。西班牙 alevín 组与英格兰青训都以此为教学首选。",
    roles:[
      { num:"1", label:"门将", desc:"出球第一发起人，充当 +1 人数；站位随防线前压上提，做防线身后的清道夫。" },
      { num:"2/3/4", label:"三中卫", desc:"居中者拖后指挥，两侧拉开宽度持球推进；边中卫上前时居中中卫横移补位。" },
      { num:"6/8/10", label:"三中场", desc:"6 号殿后保护，8 号上下往返接应两端，10 号前插组织——三人是一台机器的三个齿轮。" },
      { num:"9", label:"单前锋", desc:"顶住中卫做支点，反跑身后；孤军时等中场成组插上，绝不单打独斗。" },
    ],
    pros:["三角形传球网络遍布全场","三条线人数均衡，攻守转换顺","天然教会球员“线”的概念"],
    cons:["两肋是唯一弱点，需边中卫补位","单前锋孤军时需要中场成组插上","对中场三人纪律性要求高"],
    use:"建队首选与长期主阵型；教学比赛默认阵型。",
    refs:["rfef-8","fa-dna"],
    players:[
      {id:1,num:1,team:"gk",x:6,y:50,label:"GK"},
      {id:2,num:2,team:"own",x:20,y:24,label:""},
      {id:3,num:3,team:"own",x:17,y:50,label:""},
      {id:4,num:4,team:"own",x:20,y:76,label:""},
      {id:6,num:6,team:"own",x:42,y:50,label:"6"},
      {id:8,num:8,team:"own",x:46,y:24,label:"8"},
      {id:10,num:10,team:"own",x:46,y:76,label:"10"},
      {id:9,num:9,team:"own",x:70,y:50,label:"9"},
    ],
  },
  {
    id:"s-322", gameType:"field8", name:"3-2-2", en:"Three-Two-Two",
    desc:"双前锋结构：中路终结点多，反击锋线成对，适合身体对抗强、直接打法为主的队伍；两翼宽度交给边中卫拉开是它的独特风景。",
    roles:[
      { num:"2/3/4", label:"三中卫", desc:"出球三人组，居中者指挥；边中卫压上时必须有人回填他的通道。" },
      { num:"6/8", label:"双中场", desc:"一攻一守：6 号拖后扫荡，8 号前插到禁区线；两人不同时离开中场。" },
      { num:"9/11", label:"双前锋", desc:"一高一快或一前一后，交叉跑位；反击时一人冲身后一人回接做二点。" },
    ],
    pros:["锋线两人互相掩护，反击锐利","边路可放手交给中卫拉开","双中场有层次"],
    cons:["边路中场空缺，宽度全靠翼中卫","被压半场时中场只有两人","两翼身后易被打身后"],
    use:"以快攻与对抗为主的队伍；对阵控球型对手打反击。",
    refs:["rfef-8"],
    players:[
      {id:1,num:1,team:"gk",x:6,y:50,label:"GK"},
      {id:2,num:2,team:"own",x:20,y:26,label:""},
      {id:3,num:3,team:"own",x:17,y:50,label:""},
      {id:4,num:4,team:"own",x:20,y:74,label:""},
      {id:6,num:6,team:"own",x:44,y:38,label:"6"},
      {id:8,num:8,team:"own",x:44,y:62,label:"8"},
      {id:9,num:9,team:"own",x:70,y:38,label:"9"},
      {id:11,num:11,team:"own",x:70,y:62,label:"11"},
    ],
  },
  {
    id:"s-232", gameType:"field8", name:"2-3-2", en:"Two-Three-Two",
    desc:"攻击性最强的八人制结构：五名中前场球员形成横排控制，英格兰 9 人制前身、西班牙也常用于领先后的控制阶段。",
    roles:[
      { num:"2/3", label:"双后卫", desc:"宽度担当，一人上抢一人保护；身后的大片草地靠两人互相喊话补。" },
      { num:"7/8/10", label:"三中场", desc:"居中者掌控节奏，两翼内收配合；丢球瞬间三人就是第一道反抢线。" },
      { num:"9/10", label:"双前锋", desc:"顶住防线，为中场前插让出空间；一人回接另一人必顶上，门前不能没人。" },
    ],
    pros:["中场人数最多，控制力强","进攻端五人联动套路丰富","落后追分的高效选择"],
    cons:["只有两名后卫，防守宽度告急","边路身前大片空当","被反击时非常脆弱"],
    use:"领先控制节奏或落后强攻；队员技术较好时。",
    refs:["rfef-8"],
    players:[
      {id:1,num:1,team:"gk",x:6,y:50,label:"GK"},
      {id:2,num:2,team:"own",x:22,y:34,label:""},
      {id:3,num:3,team:"own",x:22,y:66,label:""},
      {id:7,num:7,team:"own",x:46,y:20,label:"7"},
      {id:8,num:8,team:"own",x:42,y:50,label:"8"},
      {id:10,num:10,team:"own",x:46,y:80,label:"10"},
      {id:9,num:9,team:"own",x:70,y:38,label:"9"},
      {id:11,num:11,team:"own",x:70,y:62,label:"11"},
    ],
  },
  {
    id:"s-313", gameType:"field8", name:"3-1-3", en:"Three-One-Three",
    desc:"镜像三前锋：单后腰居中调度，三名攻击手顶上，最强控场与施压结构，酷似十一人制的 4-3-3 缩影。",
    roles:[
      { num:"2/3/4", label:"三中卫", desc:"三人组出球，后腰回接成菱形；两侧中卫套边时居中者横移补通道。" },
      { num:"6", label:"单后腰", desc:"全场节拍器：接应、转身、转移；被冻结时回撤到中卫线自救。" },
      { num:"7/9/11", label:"三前锋", desc:"占住宽与深，压迫时分别逼三人；回防时内收保护肋部而不是追边线。" },
    ],
    pros:["高位压迫时结构天然对位","三前锋拉满宽度与纵深","培养位置足球的最佳模板"],
    cons:["单后腰被冻结则全场瘫痪","三前锋回防少，防守 7 人变 5 人","对 6 号要求极高"],
    use:"控球流队伍；对阵弱旅演练压迫。",
    refs:["laliga-pos","rfef-8"],
    players:[
      {id:1,num:1,team:"gk",x:6,y:50,label:"GK"},
      {id:2,num:2,team:"own",x:20,y:26,label:""},
      {id:3,num:3,team:"own",x:17,y:50,label:""},
      {id:4,num:4,team:"own",x:20,y:74,label:""},
      {id:6,num:6,team:"own",x:40,y:50,label:"6"},
      {id:7,num:7,team:"own",x:66,y:20,label:"7"},
      {id:9,num:9,team:"own",x:68,y:50,label:"9"},
      {id:11,num:11,team:"own",x:66,y:80,label:"11"},
    ],
  },
  {
    id:"f-13", gameType:"futsal", name:"1-3 高压进攻", en:"One-Three",
    desc:"一名 Fixo 殿后，三名攻击手顶成一线横排：极致的宽度与高位，配合全场压迫使用——进球之后连着进球的阵型。",
    roles:[
      { num:"4", label:"Fixo", desc:"唯一后卫：横移覆盖巨大，出球与补位全靠他。" },
      { num:"7/8/10", label:"攻击线", desc:"三人横排站满宽度，压迫时分别对位对方三人。" },
      { num:"1", label:"门将", desc:"清道夫：1-3 身后空间大，门将站位必须极高。" },
    ],
    pros:["压迫时天然三线对位","进攻宽度拉满、转移最快","落后强攻的最后武器"],
    cons:["身后一个直塞就单刀","对 Fixo 体能和判断要求极高","门将压力巨大"],
    use:"落后追分最后阶段；对手怕压迫时的主动选择。",
    refs:["fifa-manual"],
    players:[
      {id:1,num:1,team:"gk",x:8,y:50,label:"GK"},
      {id:4,num:4,team:"own",x:26,y:50,label:""},
      {id:7,num:7,team:"own",x:58,y:16,label:""},
      {id:8,num:8,team:"own",x:62,y:50,label:""},
      {id:10,num:10,team:"own",x:58,y:84,label:""},
    ],
  },
  {
    id:"s-2131", gameType:"field8", name:"2-1-3-1", en:"Two-One-Three-One",
    desc:"双中卫加单后腰筑底，三名攻击中场平行在前，单前锋顶上——结构现代、攻守弹性大，适合技战术理解力强的队伍。",
    roles:[
      { num:"2/3", label:"双中卫", desc:"宽度担当：一人上抢另一人保护；两人之间不许有超过 10 米的缝。" },
      { num:"4", label:"单后腰", desc:"攻防节拍器：接中卫出球、扫描全场；丢球瞬间他就是第一道延缓线。" },
      { num:"7/8/10", label:"攻击中场", desc:"平行三人：两翼拉开宽度，10 号居中串联；丢球后三人就地构成反抢第一线。" },
      { num:"9", label:"单前锋", desc:"顶住中卫，为三人攻击组让出十号区；回防时只回撤到中场线，保留反击箭头。" },
    ],
    pros:["后腰护中卫，转换速度快","三人攻击组套路变化多","天然练会「线」的概念"],
    cons:["边路防守靠攻击中场回追","单后腰被冻结则前后脱节","对球员位置感要求高"],
    use:"技术流队伍的进阶选择；U12+ 逐步引入。",
    refs:["laliga-pos","fa-dna"],
    players:[
      {id:1,num:1,team:"gk",x:6,y:50,label:"GK"},
      {id:2,num:2,team:"own",x:22,y:32,label:""},
      {id:3,num:3,team:"own",x:22,y:68,label:""},
      {id:4,num:4,team:"own",x:38,y:50,label:"4"},
      {id:7,num:7,team:"own",x:56,y:16,label:"7"},
      {id:10,num:10,team:"own",x:58,y:50,label:"10"},
      {id:8,num:8,team:"own",x:56,y:84,label:"8"},
      {id:9,num:9,team:"own",x:76,y:50,label:"9"},
    ],
  },
  {
    id:"s-421", gameType:"field8", name:"4-2-1", en:"Four-Two-One",
    desc:"四后卫稳健结构：两条人墙保中路，双中场清扫，适合防守反击和年轻队伍建立防守安全感。",
    roles:[
      { num:"2/3/4/5", label:"四后卫", desc:"边后卫上前要果断，中卫互补位；一条边压上时，同侧后腰必须横移补他的身后。" },
      { num:"6/8", label:"双中场", desc:"防线身前的双闸：拦截后第一时间向前；一个保护一个接应，绝不一起扑球。" },
      { num:"9", label:"单前锋", desc:"反击支点：回接做球后立刻转身冲身后，做球与反跑是同一回合的两个动作。" },
    ],
    pros:["防守厚度最高，失球少","结构简单，年轻队伍有安全感","反击通道明确"],
    cons:["进攻人数少，推进依赖边后卫","中场创造力不足时易被围攻","单前锋需要极强背身能力"],
    use:"防守反击打法；保护年轻队伍建立信心。",
    refs:["fa-dna"],
    players:[
      {id:1,num:1,team:"gk",x:6,y:50,label:"GK"},
      {id:2,num:2,team:"own",x:22,y:16,label:""},
      {id:4,num:4,team:"own",x:19,y:39,label:""},
      {id:5,num:5,team:"own",x:19,y:61,label:""},
      {id:3,num:3,team:"own",x:22,y:84,label:""},
      {id:6,num:6,team:"own",x:44,y:38,label:"6"},
      {id:8,num:8,team:"own",x:44,y:62,label:"8"},
      {id:9,num:9,team:"own",x:70,y:50,label:"9"},
    ],
  },
  {
    id:"s-241", gameType:"field8", name:"2-4-1", en:"Two-Four-One",
    desc:"中场菱形控制：四名中场形成菱形（1 后腰 + 2 内收边路 + 1 前腰），最大化学传递网络。",
    roles:[
      { num:"2/3", label:"双后卫", desc:"边后卫随时外扩补宽度；菱形中场不回边路，两翼走廊是他们的专属防区。" },
      { num:"4/8/7/10", label:"菱形四中场", desc:"4 号拖后扫荡、7/10 边路内收接应、10 号前腰插禁区——四个点轮流到达每个角度。" },
      { num:"9", label:"单前锋", desc:"牵制中卫，为前腰腾出十号位空间；做球后原地反抢是菱形的第一次拦截。" },
    ],
    pros:["传球网络最密、控球率天然高","菱形教会球员不同角度接应","中场反抢人数多"],
    cons:["边路防守完全依赖边后卫冲刺","菱形横向覆盖窄","对球员跑位默契要求高"],
    use:"传控风格成型后的进阶阵型。",
    refs:["laliga-pos"],
    players:[
      {id:1,num:1,team:"gk",x:6,y:50,label:"GK"},
      {id:2,num:2,team:"own",x:22,y:34,label:""},
      {id:3,num:3,team:"own",x:22,y:66,label:""},
      {id:4,num:4,team:"own",x:40,y:50,label:"4"},
      {id:7,num:7,team:"own",x:52,y:18,label:"7"},
      {id:10,num:10,team:"own",x:52,y:82,label:"10"},
      {id:8,num:8,team:"own",x:60,y:50,label:"8"},
      {id:9,num:9,team:"own",x:74,y:50,label:"9"},
    ],
  },
];

/* ============================================================
   战术套路库
   ============================================================ */
const FUTSAL_ATTACK = [
  {
    id:"fa-rot", gameType:"futsal", phase:"atk", formation:"f-40", styles:["possession"],
    title:"4-0 轮转 · 横传拉扯二打一", difficulty:3,
    summary:"一线站位横向传导，把防守整体“调”起来，在轮转错位瞬间打穿边路。",
    refs:["fifa-manual","laliga-pos"],
    keyPoints:[
      "横传不是倒脚：每一次转移都要让防守整体移动，谁动谁露缝",
      "轮转三原则：有人上、有人补、有人拉——永远保持一线四点",
      "转移最多两脚完成，第三脚必须改变进攻区域",
      "接球人先观察（Scanning）再触球，眼睛比脚快",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:8,y:50},{id:2,num:2,team:"own",x:24,y:50},{id:3,num:3,team:"own",x:40,y:24},
      {id:4,num:4,team:"own",x:40,y:76},{id:5,num:5,team:"own",x:58,y:50},
      {id:"b",team:"ball",x:24,y:50},
      {id:"o1",num:6,team:"opp",x:48,y:40},{id:"o2",num:7,team:"opp",x:48,y:62},{id:"o3",num:8,team:"opp",x:60,y:50},
      {id:"og",num:1,team:"oppgk",x:92,y:50},
    ],
    steps:[
      { note:"一线横传：2 号与 3 号横向倒脚，吸引防守整体向有球侧移动。",
        moves:[{id:2,x:34,y:42,type:"run"},{id:3,x:44,y:28,type:"run"},{id:"b",x:44,y:28,type:"pass"}] },
      { note:"3 号回敲 2 号，同时 5 号下拉到深位接应——防守人开始犹豫跟谁。",
        moves:[{id:3,x:50,y:22,type:"run"},{id:5,x:62,y:64,type:"run"},{id:"b",x:34,y:42,type:"pass"}] },
      { note:"2 号两脚内转移弱侧 4 号：防守横移不到，右侧出现 2v1。",
        moves:[{id:4,x:46,y:70,type:"run"},{id:"b",x:46,y:70,type:"pass"},{id:2,x:40,y:46,type:"run"}] },
      { note:"4 号带球内收吸引对方 7 号上抢，为 5 号让出中路通道。",
        moves:[{id:4,x:56,y:62,type:"carry"},{id:"b",x:56,y:62,type:"carry"},{id:"o2",x:52,y:66,type:"run"}] },
      { note:"4 号直塞 5 号反跑空当——打穿第一道防线，形成单刀。",
        moves:[{id:5,x:74,y:52,type:"run"},{id:"b",x:74,y:52,type:"pass"}] },
      { note:"5 号面对出击的门将推远角，终结。",
        moves:[{id:5,x:82,y:49,type:"run"},{id:"b",x:90,y:44,type:"shot"}] },
    ],
  },
  {
    id:"fa-pivot", gameType:"futsal", phase:"atk", formation:"f-121", styles:["possession","pivot"],
    title:"支点回做 · 后排插上射门", difficulty:2,
    summary:"Pivo 背身要位回做，Fixo 从后排突然插上完成远射——五人制最实用的中路终结配合。",
    refs:["fifa-manual","fa-cap"],
    keyPoints:[
      "Pivo 要位：张开手臂隔开防守人，掌心向队友示意传球线路（Deception）",
      "回做力度：脚弓推地滚球，力度刚好让插上人不用停球",
      "插上时机：Pivo 触球瞬间启动，早一步越位、晚一步被封堵（Timing）",
      "射门第一选择：打远角贴地，门将扑近角重心已偏",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:8,y:50},{id:4,num:4,team:"own",x:24,y:50},{id:7,num:7,team:"own",x:46,y:22},
      {id:10,num:10,team:"own",x:46,y:78},{id:9,num:9,team:"own",x:68,y:50},
      {id:"b",team:"ball",x:24,y:50},
      {id:"o1",num:5,team:"opp",x:52,y:40},{id:"o2",num:6,team:"opp",x:52,y:62},{id:"o3",num:8,team:"opp",x:74,y:44},
      {id:"og",num:1,team:"oppgk",x:92,y:50},
    ],
    steps:[
      { note:"4 号（Fixo）横传右路 10 号，把防守吸引到有球侧。",
        moves:[{id:10,x:54,y:74,type:"run"},{id:"b",x:54,y:74,type:"pass"}] },
      { note:"10 号推进两步传给背身要位的 Pivo（9 号），防守收缩包夹支点。",
        moves:[{id:9,x:66,y:46,type:"run"},{id:"b",x:66,y:46,type:"pass"},{id:"o3",x:70,y:48,type:"run"}] },
      { note:"Pivo 触球瞬间，4 号从后排突然启动插上——防守全在盯球。",
        moves:[{id:4,x:48,y:34,type:"run"},{id:9,x:63,y:50,type:"run"}] },
      { note:"Pivo 脚弓回做，地滚球精准送到插上线路，4 号不做停球直接跟进。",
        moves:[{id:"b",x:48,y:34,type:"pass"},{id:4,x:56,y:36,type:"run"}] },
      { note:"4 号不停球直接远射——贴地斩打远角。",
        moves:[{id:"b",x:90,y:42,type:"shot"},{id:4,x:62,y:37,type:"run"}] },
    ],
  },
  {
    id:"fa-wall", gameType:"futsal", phase:"atk", formation:"f-121", styles:["possession","fast"],
    title:"二过一穿越 · Ala 斜插单刀", difficulty:2,
    summary:"边路（Ala）与 Pivo 的墙式二过一，用一次撞墙打穿边路第一道防线。",
    refs:["fifa-manual","fa-fp"],
    keyPoints:[
      "墙式配合的第一传要“喂到脚下”，让做墙人一触即回",
      "传球后立即加速——传跑是同一个动作（Movement）",
      "做墙人可以脚后跟或外脚背让球变线，增加欺骗性（Deception）",
      "U10 以下先在 2v1 里练会“传了就跑”，再加防守人",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:8,y:50},{id:4,num:4,team:"own",x:24,y:50},{id:7,num:7,team:"own",x:46,y:22},
      {id:10,num:10,team:"own",x:44,y:78},{id:9,num:9,team:"own",x:66,y:50},
      {id:"b",team:"ball",x:44,y:78},
      {id:"o1",num:5,team:"opp",x:50,y:68},{id:"o2",num:6,team:"opp",x:62,y:60},{id:"o3",num:8,team:"opp",x:56,y:44},
      {id:"og",num:1,team:"oppgk",x:92,y:50},
    ],
    steps:[
      { note:"10 号（Ala）带球内收，把对方 5 号引出来形成 1v1 局面。",
        moves:[{id:10,x:54,y:70,type:"carry"},{id:"b",x:54,y:70,type:"carry"},{id:"o1",x:52,y:66,type:"run"}] },
      { note:"敲给 Pivo 做墙——球一出脚立刻起步，不要回头看球。",
        moves:[{id:9,x:62,y:56,type:"run"},{id:"b",x:62,y:56,type:"pass"},{id:10,x:60,y:76,type:"run"}] },
      { note:"Pivo 顺势直塞，10 号从对方 5 号身后穿插而过。",
        moves:[{id:"b",x:72,y:70,type:"pass"},{id:10,x:70,y:72,type:"run"},{id:"o1",x:56,y:64,type:"run"}] },
      { note:"10 号单刀突入，观察门将站位后推远角。",
        moves:[{id:10,x:80,y:60,type:"run"},{id:"b",x:80,y:60,type:"carry"}] },
      { note:"冷静推射远角完成终结。",
        moves:[{id:"b",x:91,y:56,type:"shot"}] },
    ],
  },
  {
    id:"fa-gk", gameType:"futsal", phase:"atk", formation:"f-31", styles:["possession"],
    title:"门将发动 · 破全场紧逼", difficulty:3,
    summary:"面对人盯人全场紧逼：门将持球邀压，三后卫拉开接应，Pivo 身后一击。",
    refs:["fifa-laws","fifa-manual"],
    keyPoints:[
      "规则要点：门将出球后在己方半场不得再触球（除非球过半场或对方触球），门将只做第一次出球",
      "持球 4 秒规则：邀压时间最多 3 秒，出球前给队友完整喊话",
      "三后卫呈宽三角形站位，永远保持两个出球角度",
      "被逼急了就踢出边线——拿到界外球重新组织，好过在本方禁区丢球",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:8,y:50},{id:2,num:2,team:"own",x:20,y:24},{id:4,num:4,team:"own",x:16,y:50},
      {id:5,num:5,team:"own",x:20,y:76},{id:9,num:9,team:"own",x:62,y:50},
      {id:"b",team:"ball",x:8,y:50},
      {id:"o1",num:6,team:"opp",x:30,y:32},{id:"o2",num:7,team:"opp",x:28,y:54},{id:"o3",num:8,team:"opp",x:30,y:70},
      {id:"og",num:1,team:"oppgk",x:92,y:50},
    ],
    steps:[
      { note:"对方全场人盯人上抢。门将持球邀压 3 秒，三后卫向两翼拉开——把场子撑大。",
        moves:[{id:2,x:16,y:18,type:"run"},{id:5,x:16,y:82,type:"run"},{id:4,x:18,y:48,type:"run"}] },
      { note:"门将手抛球给位置最稳的 4 号（Fixo），不传被盯死的一侧。",
        moves:[{id:"b",x:18,y:48,type:"pass"},{id:"o2",x:24,y:50,type:"run"}] },
      { note:"4 号回敲 2 号（第三人有角度），吸引对方 6 号继续上抢。",
        moves:[{id:"b",x:16,y:18,type:"pass"},{id:"o1",x:22,y:22,type:"run"}] },
      { note:"2 号斜长传转移弱侧 5 号——压迫被一次性甩开，完成破逼抢。",
        moves:[{id:5,x:34,y:74,type:"run"},{id:"b",x:34,y:74,type:"pass"}] },
      { note:"5 号带球推进，Pivo 已在防线身后启动反跑。",
        moves:[{id:9,x:74,y:44,type:"run"},{id:5,x:44,y:70,type:"carry"},{id:"b",x:44,y:70,type:"carry"}] },
      { note:"5 号直塞 Pivo，单刀终结。",
        moves:[{id:"b",x:78,y:46,type:"pass"},{id:9,x:78,y:46,type:"run"}] },
    ],
  },
  {
    id:"fa-switch", gameType:"futsal", phase:"atk", formation:"f-121", styles:["fast","possession"],
    title:"换边转移 · 弱侧 Ala 内切终结", difficulty:2,
    summary:"强侧吸引包夹后一脚长传转移，弱侧 Ala 内切与 Pivo 墙式配合完成射门。",
    refs:["fifa-manual","fa-cap"],
    keyPoints:[
      "转移前必须先“卖”强侧：至少两次横向倒脚把防守拉过去",
      "弱侧 Ala 提前启动半拍——转移球到之前你已经在跑",
      "转移脚法：脚背平抽地滚球，2 秒内横穿全场",
      "弱侧接球第一动作向中路带（进入射门区域），不是沿着边线走",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:8,y:50},{id:4,num:4,team:"own",x:24,y:50},{id:7,num:7,team:"own",x:46,y:22},
      {id:10,num:10,team:"own",x:48,y:78},{id:9,num:9,team:"own",x:66,y:50},
      {id:"b",team:"ball",x:48,y:78},
      {id:"o1",num:5,team:"opp",x:54,y:70},{id:"o2",num:6,team:"opp",x:60,y:80},{id:"o3",num:8,team:"opp",x:40,y:40},
      {id:"og",num:1,team:"oppgk",x:92,y:50},
    ],
    steps:[
      { note:"右路 10 号持球，对方 5 号、6 号形成包夹——强侧已经“做局”。",
        moves:[{id:10,x:56,y:76,type:"carry"},{id:"b",x:56,y:76,type:"carry"},{id:"o2",x:56,y:82,type:"run"}] },
      { note:"10 号回敲 4 号（Fixo），包夹随球移动。",
        moves:[{id:"b",x:30,y:52,type:"pass"},{id:10,x:60,y:72,type:"run"}] },
      { note:"4 号一脚长传转移弱侧 7 号——防守重心还在右侧。",
        moves:[{id:7,x:50,y:28,type:"run"},{id:"b",x:50,y:28,type:"pass"}] },
      { note:"7 号不沿边线走，直接向中路禁区弧内切。",
        moves:[{id:7,x:60,y:38,type:"carry"},{id:"b",x:60,y:38,type:"carry"}] },
      { note:"与 Pivo 撞墙：7 号敲 9 号再前插，撕开肋部。",
        moves:[{id:9,x:68,y:48,type:"run"},{id:"b",x:68,y:48,type:"pass"},{id:7,x:70,y:40,type:"run"}] },
      { note:"9 号做墙回做，7 号近角爆射。",
        moves:[{id:"b",x:72,y:40,type:"pass"},{id:"b",x:90,y:36,type:"shot"}] },
    ],
  },
  {
    id:"fa-kickin", gameType:"futsal", phase:"atk", formation:"any", styles:["fast","possession"],
    title:"边线球战术 · 4 秒快发", difficulty:2,
    summary:"五人制边线球 4 秒内必须发出：快发打转身慢的防守，慢发用假跑拉开固定接应——两种套路都要练熟。",
    refs:["fifa-laws","fifa-manual"],
    keyPoints:[
      "规则红线：球放定后 4 秒内发出、发球时脚不得踩线、直接射门不算进球",
      "快发时机：防守人还没落位、最近的防守人距球超过 2 米",
      "慢发信号：接应人举手=要球，假跑换位后传第二接应点",
      "发球后立即进场参与——发球人不是旁观者（规则允许直接进场）",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:8,y:50},{id:4,num:4,team:"own",x:22,y:50},{id:7,num:7,team:"own",x:44,y:24},
      {id:10,num:10,team:"own",x:40,y:78},{id:9,num:9,team:"own",x:66,y:50},
      {id:"b",team:"ball",x:2,y:30},
      {id:"o1",num:5,team:"opp",x:36,y:30},{id:"o2",num:6,team:"opp",x:30,y:48},{id:"o3",num:8,team:"opp",x:52,y:66},
      {id:"og",num:1,team:"oppgk",x:92,y:50},
    ],
    steps:[
      { note:"边线球由 10 号主罚：防守 6 号上前来封，但还没站定——快发时机出现。",
        moves:[{id:10,x:2,y:30,type:"run"},{id:"b",x:2,y:30,type:"pass"},{id:"o2",x:12,y:38,type:"run"}] },
      { note:"10 号 2 秒内发出：地滚球传给回接的 4 号——防守没来得及对位。",
        moves:[{id:"b",x:22,y:48,type:"pass"},{id:4,x:24,y:50,type:"run"}] },
      { note:"4 号一脚横敲 7 号（第二接应点），10 号发完球立刻进场接应。",
        moves:[{id:"b",x:44,y:26,type:"pass"},{id:7,x:46,y:24,type:"run"},{id:10,x:14,y:38,type:"run"}] },
      { note:"7 号带球内切吸引 5 号，为 9 号拉出肋部通道。",
        moves:[{id:7,x:52,y:30,type:"carry"},{id:"b",x:52,y:30,type:"carry"},{id:"o1",x:44,y:32,type:"run"}] },
      { note:"7 号直塞 9 号反跑——边线球战术直接转换为得分机会。",
        moves:[{id:"b",x:74,y:46,type:"pass"},{id:9,x:76,y:48,type:"run"}] },
    ],
  },
  {
    id:"fa-corner", gameType:"futsal", phase:"atk", formation:"any", styles:["pivot"],
    title:"角球战术 · 近柱三威胁", difficulty:2,
    summary:"五人制角球没有越位：近门柱一人抢前点、Pivo 做墙回做、后排一人远射——三重威胁让门将顾此失彼。",
    refs:["fifa-laws","fifa-manual"],
    keyPoints:[
      "五人制角球无越位： Pivo 可以直接站在对方门前要位",
      "近柱威胁：第一点抢前点是门将最怕的——逼出门将移动",
      "回做远射：角球开出后回做给后排，远射打穿封堵的人堆",
      "发球脚法：内脚背弧线找近柱队友的脚，不是往人堆里踢",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:8,y:50},{id:4,num:4,team:"own",x:24,y:50},{id:7,num:7,team:"own",x:44,y:20},
      {id:10,num:10,team:"own",x:80,y:12},{id:9,num:9,team:"own",x:88,y:42},
      {id:"b",team:"ball",x:80,y:88},
      {id:"o1",num:5,team:"opp",x:78,y:78},{id:"o2",num:6,team:"opp",x:88,y:56},{id:"o3",num:8,team:"opp",x:70,y:44},
      {id:"og",num:1,team:"oppgk",x:93,y:50},
    ],
    steps:[
      { note:"7 号开角球：9 号（Pivo）卡住近门柱，10 号绕向远点，防守被迫全部回收门前。",
        moves:[{id:9,x:86,y:40,type:"run"},{id:10,x:84,y:24,type:"run"}] },
      { note:"角球开向近柱 9 号——门将被迫向近门柱移动。",
        moves:[{id:"b",x:84,y:38,type:"pass"},{id:9,x:88,y:38,type:"run"},{id:"og",x:90,y:44,type:"run"}] },
      { note:"9 号不做停球，脚弓敲回点球点——门将已经扑向近柱，中路全空。",
        moves:[{id:"b",x:76,y:44,type:"pass"},{id:9,x:86,y:40,type:"run"}] },
      { note:"后排 4 号从弧顶插上，迎球直接远射——人堆里的穿云箭。",
        moves:[{id:4,x:68,y:44,type:"run"},{id:"b",x:88,y:45,type:"shot"}] },
      { note:"远射被封堵弹回弧顶：7 号早从角旗区移到二点位——控制球权重新组织，不丢二次进攻权。",
        moves:[{id:"b",x:58,y:34,type:"pass"},{id:7,x:54,y:30,type:"run"},{id:"og",x:92,y:47,type:"run"}] },
    ],
  },
  {
    id:"fa-22low", gameType:"futsal", phase:"atk", formation:"f-22", styles:["possession"],
    title:"2-2 高低位转换", difficulty:3,
    summary:"双前锋一高一低：低位回撤接球吸引中卫上抢，高位瞬间斜插身后——中卫一跟就丢位，不跟就接球转身。",
    refs:["fifa-manual","laliga-pos"],
    keyPoints:[
      "高低位是双人舞：一人回撤，另一人必须同时斜插，不能同向",
      "回撤的深度：拉到中场线附近——把中卫拽出舒适区",
      "斜插的线路：贴着回撤人的肩部穿，防守换人来不及",
      "接球人转身三选一：直塞、带球、回做——提前扫描再触球",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:8,y:50},{id:2,num:2,team:"own",x:24,y:32},{id:5,num:5,team:"own",x:24,y:68},
      {id:9,num:9,team:"own",x:52,y:36},{id:10,num:10,team:"own",x:52,y:64},
      {id:"b",team:"ball",x:24,y:32},
      {id:"o1",num:5,team:"opp",x:44,y:36},{id:"o2",num:6,team:"opp",x:46,y:62},{id:"o3",num:8,team:"opp",x:66,y:50},
      {id:"og",num:1,team:"oppgk",x:92,y:50},
    ],
    steps:[
      { note:"低位 10 号回撤到中场线接球：中卫 6 号纠结——跟出来中路就空。",
        moves:[{id:10,x:56,y:56,type:"run"},{id:"b",x:52,y:64,type:"pass"},{id:"o2",x:52,y:58,type:"run"}] },
      { note:"10 号接球的瞬间，高位 9 号斜插身后——贴着 10 号的肩穿过去。",
        moves:[{id:9,x:74,y:30,type:"run"},{id:10,x:56,y:56,type:"run"}] },
      { note:"10 号脚弓直塞身后——6 号回头追已经慢两拍。",
        moves:[{id:"b",x:74,y:30,type:"pass"},{id:"o2",x:58,y:56,type:"run"}] },
      { note:"9 号反越位成功单刀，冷静推远角。",
        moves:[{id:9,x:84,y:32,type:"run"},{id:"b",x:90,y:38,type:"shot"}] },
      { note:"若门将扑出：回撤的 10 号已跟到弧顶收二点——高低位的第二波永远有人接应。",
        moves:[{id:"b",x:62,y:40,type:"pass"},{id:10,x:64,y:46,type:"run"},{id:"og",x:91,y:44,type:"run"}] },
    ],
  },
  {
    id:"fa-second", gameType:"futsal", phase:"atk", formation:"any", styles:["fast","pivot"],
    title:"第二波进攻 · 补射意识", difficulty:1,
    summary:"射门被扑不是进攻结束：五人制射门弹回率高，1-2 人跟进补射+其余人控制二点，是最低成本的额外得分来源。",
    refs:["fifa-manual","fa-fp"],
    keyPoints:[
      "射门必须有跟进：近门 1 人包抄补射，这是可教的习惯",
      "其余人不是围观：远端 1 人收二点，2 人防反击",
      "补射时机：球离脚瞬间就启动，不是看到被扑才动",
      "补射脚法：半高球凌空或轻轻一垫，不求大力",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:8,y:50},{id:4,num:4,team:"own",x:26,y:50},{id:7,num:7,team:"own",x:48,y:26},
      {id:10,num:10,team:"own",x:48,y:74},{id:9,num:9,team:"own",x:72,y:50},
      {id:"b",team:"ball",x:48,y:74},
      {id:"o1",num:5,team:"opp",x:52,y:40},{id:"o2",num:6,team:"opp",x:60,y:62},{id:"o3",num:8,team:"opp",x:40,y:44},
      {id:"og",num:1,team:"oppgk",x:92,y:50},
    ],
    steps:[
      { note:"10 号左路传中，9 号前点抢射——门将侧扑将球挡向小禁区前沿。",
        moves:[{id:"b",x:76,y:44,type:"pass"},{id:9,x:80,y:46,type:"run"},{id:"og",x:89,y:44,type:"run"},{id:"b",x:82,y:42,type:"pass"}] },
      { note:"跟进的 7 号（射门瞬间已启动）迎弹回球凌空补射——这就是第二波。",
        moves:[{id:7,x:74,y:34,type:"run"},{id:"b",x:90,y:44,type:"shot"}] },
      { note:"若再被挡出：4 号控制二点，球权不丢，重新组织第二回合。",
        moves:[{id:"b",x:60,y:40,type:"pass"},{id:4,x:56,y:42,type:"run"},{id:"og",x:91,y:47,type:"run"}] },
      { note:"二次进攻耐心渗透：7 号 9 号交叉换位后再度射门。",
        moves:[{id:"b",x:78,y:50,type:"pass"},{id:7,x:70,y:44,type:"run"},{id:9,x:76,y:52,type:"run"},{id:"b",x:89,y:52,type:"shot"}] },
      { note:"球权终被解围：4 号、10 号立即落位防反击——第二波进攻的前提是丢球权后不失球。",
        moves:[{id:"b",x:30,y:30,type:"pass"},{id:4,x:30,y:46,type:"run"},{id:10,x:34,y:60,type:"run"},{id:"og",x:60,y:50,type:"run"}] },
    ],
  },
  {
    id:"fa-third", gameType:"futsal", phase:"atk", formation:"f-22", styles:["possession","pivot"],
    title:"第三人跑动 · 隐形一击", difficulty:3,
    summary:"传给 A、A 回给 B，真正的杀机是没人盯防的第三人 C——绕过防线的“隐形”跑位。",
    refs:["laliga-pos","fa-cap"],
    keyPoints:[
      "第三人跑动的本质：用两次简单传球让防守的注意力“过站”",
      "前两人都是诱饵：接球是为了让第三人的防守人看球",
      "第三人从防守人视线死角启动——永远从身后绕",
      "这是西班牙青训 Rondo 的实战化：三人在局部永远比防守多一人",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:8,y:50},{id:4,num:4,team:"own",x:24,y:32},{id:5,num:5,team:"own",x:24,y:68},
      {id:9,num:9,team:"own",x:52,y:34},{id:10,num:10,team:"own",x:56,y:66},
      {id:"b",team:"ball",x:24,y:68},
      {id:"o1",num:6,team:"opp",x:40,y:60},{id:"o2",num:7,team:"opp",x:46,y:36},{id:"o3",num:8,team:"opp",x:70,y:50},
      {id:"og",num:1,team:"oppgk",x:92,y:50},
    ],
    steps:[
      { note:"5 号传给背身接应的 10 号，10 号回做吸引对方 6 号上抢——第一层诱饵完成。",
        moves:[{id:10,x:52,y:62,type:"run"},{id:"b",x:52,y:62,type:"pass"}] },
      { note:"10 号一脚回敲 4 号，防守注意力全部转向中路。",
        moves:[{id:"b",x:30,y:36,type:"pass"},{id:10,x:56,y:64,type:"run"},{id:"o1",x:48,y:56,type:"run"}] },
      { note:"真正的杀机：9 号（第三人）从对方 7 号视线死角绕身后斜插。",
        moves:[{id:9,x:72,y:40,type:"run"},{id:"o2",x:44,y:40,type:"run"}] },
      { note:"4 号不停球直塞第三人——防守回头时球已到身后。",
        moves:[{id:"b",x:72,y:40,type:"pass"}] },
      { note:"9 号面对出击门将横敲中路空当——10 号包抄推空门。",
        moves:[{id:"b",x:80,y:56,type:"pass"},{id:10,x:80,y:60,type:"run"},{id:"b",x:90,y:58,type:"shot"}] },
    ],
  },
];

const FUTSAL_DEFENSE = [
  {
    id:"fd-press", gameType:"futsal", phase:"def", formation:"any", styles:["press"],
    title:"全场人盯人压迫", difficulty:3,
    summary:"从对方门将发球起 1v1 全场盯防，用压迫角度把球逼进“口袋”里完成围抢。",
    refs:["fifa-manual","uefa-tg"],
    keyPoints:[
      "压迫角度：曲线跑位，封内侧放外侧——把球往边线和底线赶",
      "每人必须“人球之间”站位：永远站在对手和对方球门之间",
      "就近两人形成口袋，第三人切断回传线路",
      "门将站位随整体前压上提，充当清道夫防身后",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:8,y:50},{id:2,num:2,team:"own",x:26,y:36},{id:4,num:4,team:"own",x:24,y:58},
      {id:7,num:7,team:"own",x:48,y:30},{id:9,num:9,team:"own",x:46,y:66},
      {id:"o1",num:1,team:"oppgk",x:6,y:50},
      {id:"o2",num:5,team:"opp",x:56,y:38},{id:"o3",num:6,team:"opp",x:52,y:66},{id:"o4",num:8,team:"opp",x:76,y:50},
      {id:"b",team:"ball",x:52,y:66},
    ],
    steps:[
      { note:"触发：对方门将把球交给 6 号——距离最近的 9 号 2 秒内曲线逼上，封内放外。",
        moves:[{id:9,x:44,y:62,type:"run"},{id:"b",x:52,y:66,type:"pass"},{id:"o3",x:52,y:66,type:"run"}] },
      { note:"第二人 4 号切断 6 号向中路回传的线路，口袋合拢。",
        moves:[{id:4,x:40,y:58,type:"run"},{id:9,x:46,y:70,type:"run"}] },
      { note:"7 号横移盯死另一侧接应点 5 号，让对方“看得见队友传不过去”。",
        moves:[{id:7,x:60,y:36,type:"run"},{id:2,x:36,y:44,type:"run"}] },
      { note:"压迫成功：6 号被迫横传边线方向，7 号预判断球——就地转入进攻。",
        moves:[{id:"b",x:62,y:34,type:"pass"},{id:7,x:60,y:32,type:"run"}] },
      { note:"断球瞬间整体前压：由守转攻只给对方 3 秒反应时间。",
        moves:[{id:"b",x:78,y:30,type:"carry"},{id:7,x:70,y:28,type:"carry"},{id:9,x:60,y:62,type:"run"}] },
    ],
  },
  {
    id:"fd-zone", gameType:"futsal", phase:"def", formation:"any", styles:["zone"],
    title:"2-2 区域联防", difficulty:1,
    summary:"两人一组看守四个“象限”，球到哪整体移到哪——用站位纪律代替个人对抗。",
    refs:["fifa-manual"],
    keyPoints:[
      "每人只对“自己区域里的人”负责，不追球出区域",
      "整体移动像一块地毯：一人动，四人动，间距保持 3-4 米",
      "球在边路时同侧二人收缩夹角，弱侧二人保护中路",
      "门将是指挥官：大声喊“右！收！压！”——区域防守靠嘴",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:8,y:50},{id:2,num:2,team:"own",x:30,y:28},{id:4,num:4,team:"own",x:30,y:72},
      {id:7,num:7,team:"own",x:52,y:28},{id:9,num:9,team:"own",x:52,y:72},
      {id:"o1",num:1,team:"oppgk",x:6,y:50},
      {id:"o2",num:5,team:"opp",x:60,y:30},{id:"o3",num:6,team:"opp",x:58,y:62},{id:"o4",num:8,team:"opp",x:76,y:50},
      {id:"b",team:"ball",x:58,y:62},
    ],
    steps:[
      { note:"球进入 9 号的右下区域：9 号上抢持球人，同侧的 7 号收缩保护角度。",
        moves:[{id:9,x:54,y:64,type:"run"},{id:7,x:50,y:34,type:"run"},{id:"o3",x:58,y:62,type:"run"}] },
      { note:"对面的 2 号、4 号整体左移半格——永远保持四点成方块，不散架。",
        moves:[{id:2,x:26,y:34,type:"run"},{id:4,x:26,y:66,type:"run"}] },
      { note:"6 号横传转移，整体像地毯一样横移：7 号接手压迫，9 号归位。",
        moves:[{id:"b",x:60,y:30,type:"pass"},{id:7,x:56,y:28,type:"run"},{id:9,x:50,y:66,type:"run"},{id:"o2",x:60,y:30,type:"run"}] },
      { note:"5 号（对方）被迫回传门将，全队上提压缩——把对手摁回半场。",
        moves:[{id:"b",x:12,y:46,type:"pass"},{id:9,x:56,y:66,type:"run"},{id:7,x:56,y:28,type:"run"},{id:4,x:36,y:70,type:"run"},{id:2,x:36,y:30,type:"run"}] },
      { note:"压缩的火候：门将开大脚——9 号、7 号预判第一落点，区域联防的第一反击从落点判断开始。",
        moves:[{id:"b",x:40,y:36,type:"pass"},{id:9,x:44,y:34,type:"run"},{id:7,x:48,y:30,type:"run"}] },
    ],
  },
  {
    id:"fd-mix", gameType:"futsal", phase:"def", formation:"any", styles:["press","zone"],
    title:"混合防守 · 一压三保", difficulty:2,
    summary:"一人全场跟防持球人，三人落成菱形区域保护——盯人的凶 + 区域的稳。",
    refs:["fifa-manual","uefa-tg"],
    keyPoints:[
      "“压迫者”只追球不追人：谁持球追谁，队友自动补他的区域",
      "菱形保护点永远位于持球人与球门连线上",
      "压迫者体能消耗极大，准备 2-3 人轮换这个角色",
      "对方突破压迫者时，就近保护人上抢，压迫者回撤换位",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:8,y:50},{id:2,num:2,team:"own",x:28,y:50},{id:4,num:4,team:"own",x:42,y:26},
      {id:7,num:7,team:"own",x:42,y:74},{id:9,num:9,team:"own",x:60,y:50},
      {id:"o1",num:1,team:"oppgk",x:6,y:50},
      {id:"o2",num:5,team:"opp",x:58,y:34},{id:"o3",num:6,team:"opp",x:54,y:66},{id:"o4",num:8,team:"opp",x:78,y:50},
      {id:"b",team:"ball",x:6,y:50},
    ],
    steps:[
      { note:"对方门将发球：指定的压迫者 9 号全程跟随持球人，干扰每一脚出球。",
        moves:[{id:9,x:56,y:62,type:"run"},{id:"b",x:54,y:66,type:"pass"},{id:"o3",x:54,y:66,type:"run"}] },
      { note:"其余三人落成菱形：2 号殿后，4 号、7 号护住两肋——不参与上抢。",
        moves:[{id:2,x:26,y:52,type:"run"},{id:4,x:38,y:32,type:"run"},{id:7,x:38,y:68,type:"run"}] },
      { note:"9 号把持球人逼向边线，4 号横移准备断传向中路的线路。",
        moves:[{id:9,x:50,y:68,type:"run"},{id:4,x:44,y:44,type:"run"}] },
      { note:"被迫长传转移：压迫者 9 号立刻去追新持球人，菱形整体旋转——防守形状不变。",
        moves:[{id:"b",x:60,y:34,type:"pass"},{id:9,x:56,y:36,type:"run"},{id:4,x:34,y:56,type:"run"},{id:7,x:40,y:62,type:"run"}] },
      { note:"旋转完成检查：2 号始终是最后一道闸——一压三保的「三保」从未散开，这就是混合防守的底盘。",
        moves:[{id:2,x:24,y:50,type:"run"},{id:7,x:46,y:58,type:"run"},{id:1,x:12,y:50,type:"run"}] },
    ],
  },
  {
    id:"fd-low", gameType:"futsal", phase:"def", formation:"any", styles:["block"],
    title:"低位 3-1 收缩 · 保护近门柱", difficulty:1,
    summary:"整体退守禁区弧顶，三人封堵中路打门角度，Pivo 退防充当第四人——领先时守住胜局的标准答案。",
    refs:["fifa-manual"],
    keyPoints:[
      "低位的两件事：封堵射门角度 + 保护近门柱横传点",
      "所有人 goal-side（人球之间），绝不从持球人身后绕",
      "解围方向：向边线踢、往高踢、往远踢——绝不在中路横传",
      "得球后别急着堆上去：3 秒观察，先保证球权再推进",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:6,y:50},{id:2,num:2,team:"own",x:20,y:30},{id:4,num:4,team:"own",x:16,y:50},
      {id:7,num:7,team:"own",x:20,y:70},{id:9,num:9,team:"own",x:30,y:50},
      {id:"o1",num:1,team:"oppgk",x:90,y:50},
      {id:"o2",num:5,team:"opp",x:56,y:36},{id:"o3",num:6,team:"opp",x:52,y:64},{id:"o4",num:8,team:"opp",x:72,y:50},
      {id:"b",team:"ball",x:52,y:64},
    ],
    steps:[
      { note:"对手控球推进，全队退守：三人封锁中路打门角度，9 号回撤成第四人。",
        moves:[{id:9,x:26,y:50,type:"run"},{id:2,x:18,y:34,type:"run"},{id:7,x:18,y:66,type:"run"}] },
      { note:"6 号试图横传找 8 号：9 号横移封堵这条传球线。",
        moves:[{id:9,x:30,y:44,type:"run"},{id:"o3",x:52,y:64,type:"run"}] },
      { note:"8 号被迫转移到弱侧，4 号外扩顶出去干扰，其余人不动——低位的纪律就是不冒进。",
        moves:[{id:"b",x:56,y:36,type:"pass"},{id:4,x:24,y:46,type:"run"},{id:"o2",x:56,y:36,type:"run"}] },
      { note:"对方勉强远射，门将近角封死将球压住——低位防守胜利。",
        moves:[{id:"b",x:14,y:48,type:"shot"},{id:1,x:8,y:50,type:"run"}] },
      { note:"压住球只是及格：门将指挥全队前压造越位线，把防线从禁区推回中场——低位的终点是重新夺回纵深。",
        moves:[{id:2,x:30,y:36,type:"run"},{id:4,x:28,y:52,type:"run"},{id:7,x:30,y:64,type:"run"},{id:1,x:12,y:50,type:"run"}] },
    ],
  },
  {
    id:"fd-cp", gameType:"futsal", phase:"def", formation:"any", styles:["press","fast"],
    title:"丢球反抢 · 5 秒窗口", difficulty:2,
    summary:"丢球瞬间是全场最脆弱也最强的时刻：就近者立即反抢，其他人 5 秒内切断所有向前线路。",
    refs:["uefa-tg","laliga-pos"],
    keyPoints:[
      "反抢窗口只有 5 秒：对方刚拿球、抬头找人的瞬间最怕逼抢",
      "分工：最近的人上抢，第二人封回传，其他人切向前线路",
      "反抢投入的人数不超过三人——抢不回立刻退回 2-2，绝不拖泥带水",
      "五人制场地小，反抢成功率远高于十一人制，这是五人制的灵魂",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:8,y:50},{id:2,num:2,team:"own",x:26,y:40},{id:4,num:4,team:"own",x:22,y:64},
      {id:7,num:7,team:"own",x:52,y:34},{id:9,num:9,team:"own",x:48,y:60},
      {id:"o1",num:1,team:"oppgk",x:6,y:50},
      {id:"o2",num:5,team:"opp",x:60,y:50},{id:"o3",num:6,team:"opp",x:74,y:36},{id:"o4",num:8,team:"opp",x:70,y:68},
      {id:"b",team:"ball",x:74,y:36},
    ],
    steps:[
      { note:"我方丢球！对方 6 号刚拿球：最近的 9 号 2 秒内扑上——不给抬头观察的时间。",
        moves:[{id:9,x:68,y:40,type:"run"}] },
      { note:"7 号切断 6 号的出球线路，4 号、2 号守住中路——口袋在对方半场合拢。",
        moves:[{id:7,x:66,y:32,type:"run"},{id:4,x:48,y:54,type:"run"},{id:2,x:38,y:46,type:"run"}] },
      { note:"6 号仓促转移边路，7 号早已预判线路启动。",
        moves:[{id:"b",x:70,y:28,type:"pass"},{id:7,x:68,y:30,type:"run"}] },
      { note:"7 号断球成功——丢球 4 秒重新拿回球权，对方防线还散着。",
        moves:[{id:"b",x:72,y:24,type:"carry"},{id:7,x:70,y:26,type:"carry"}] },
      { note:"7 号直塞前插的 9 号：反抢直接转换成单刀。",
        moves:[{id:"b",x:82,y:34,type:"pass"},{id:9,x:78,y:38,type:"run"}] },
    ],
  },
  {
    id:"fd-delay", gameType:"futsal", phase:"def", formation:"any", styles:["fast"],
    title:"由攻转守 · 就地延缓", difficulty:2,
    summary:"丢球后最近的人第一任务不是抢，是延缓：贴住持球人给队友 3 秒回位时间——五人制丢球最快的死法是全员扑抢。",
    refs:["laliga-pos","uefa-tg"],
    keyPoints:[
      "延缓三要素：侧身站位、封内侧线路、不轻易出脚",
      "给全队 3 秒：3 秒内其他人退回球门一侧的站位",
      "延缓者的目的：把持球人往边线和底线赶",
      "队友落位后延缓者可选择上抢——那时才变成压迫",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:8,y:50},{id:2,num:2,team:"own",x:24,y:40},{id:4,num:4,team:"own",x:20,y:64},
      {id:7,num:7,team:"own",x:46,y:30},{id:9,num:9,team:"own",x:50,y:66},
      {id:"o1",num:1,team:"oppgk",x:6,y:50},
      {id:"o2",num:4,team:"opp",x:60,y:50},{id:"o3",num:6,team:"opp",x:74,y:36},{id:"o4",num:8,team:"opp",x:70,y:66},
      {id:"b",team:"ball",x:56,y:62},
    ],
    steps:[
      { note:"我方丢球（模拟）：最近的 9 号不扑球，而是侧身贴住持球人 6 号——封住向中路的线路。",
        moves:[{id:"b",x:58,y:60,type:"pass"},{id:9,x:50,y:58,type:"run"},{id:"o3",x:74,y:36,type:"run"}] },
      { note:"9 号小碎步跟随，把 6 号往边线方向「引」——不求断球，只求拖 3 秒。",
        moves:[{id:9,x:52,y:62,type:"run"},{id:"o2",x:62,y:56,type:"run"},{id:"b",x:62,y:56,type:"carry"}] },
      { note:"这 3 秒里：2 号、4 号、7 号全部退到球门一侧落位——防线成型。",
        moves:[{id:2,x:30,y:44,type:"run"},{id:4,x:28,y:58,type:"run"},{id:7,x:40,y:36,type:"run"},{id:1,x:12,y:50,type:"run"}] },
      { note:"落位完成，9 号升级为压迫：全力上抢，队友封线——从延缓转为围抢。",
        moves:[{id:9,x:56,y:60,type:"run"},{id:4,x:42,y:56,type:"run"},{id:7,x:52,y:40,type:"run"},{id:"b",x:64,y:52,type:"pass"}] },
      { note:"围抢夺球：9 号断球后不粘球，第一时间敲给 7 号——由守转攻的三秒内完成身份切换。",
        moves:[{id:"b",x:50,y:36,type:"pass"},{id:9,x:66,y:58,type:"run"},{id:7,x:60,y:36,type:"run"}] },
    ],
  },
  {
    id:"fd-kickin", gameType:"futsal", phase:"def", formation:"any", styles:["zone"],
    title:"边线球防守 · 封两点", difficulty:1,
    summary:"对方边线球的两种威胁：发球人进场接回传、最近接应点——一人封发球人、一人贴接应点、第三人收保护，全场其他人对位。",
    refs:["fifa-laws","fifa-manual"],
    keyPoints:[
      "4 秒规则是防守的朋友：发球方只有 4 秒，拖住他的接应跑位",
      "最近防守人距球 2 米站位：让快发不可行，又不过分贴近",
      "重点封「发球人进场后的回传线路」——很多人忽视这一点",
      "球发出后立刻转为正常防守站位，不追着发球人看",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:8,y:50},{id:2,num:2,team:"own",x:22,y:44},{id:4,num:4,team:"own",x:24,y:66},
      {id:7,num:7,team:"own",x:46,y:28},{id:9,num:9,team:"own",x:56,y:58},
      {id:"o1",num:1,team:"oppgk",x:6,y:50},
      {id:"o2",num:4,team:"opp",x:52,y:44},{id:"o3",num:6,team:"opp",x:44,y:70},{id:"o4",num:8,team:"opp",x:74,y:50},
      {id:"b",team:"ball",x:2,y:30},
    ],
    steps:[
      { note:"对方在左侧边线罚球：2 号距球 2 米站位封快发，4 号贴住最近接应点 6 号。",
        moves:[{id:2,x:6,y:32,type:"run"},{id:4,x:22,y:56,type:"run"},{id:"o3",x:26,y:52,type:"run"}] },
      { note:"4 秒压力下发球：只能传给回撤要球的 4 号——发球人 8 号会进场接回传。",
        moves:[{id:"b",x:28,y:50,type:"pass"},{id:"o3",x:28,y:52,type:"run"},{id:"o4",x:64,y:46,type:"run"}] },
      { note:"关键动作：9 号早已卡在 8 号进场的接球线路上——回传被预判。",
        moves:[{id:9,x:48,y:48,type:"run"},{id:"b",x:34,y:48,type:"pass"},{id:"o4",x:40,y:46,type:"run"}] },
      { note:"9 号断下回传——就地推进，防守直接变进球机会。",
        moves:[{id:"b",x:66,y:44,type:"carry"},{id:9,x:56,y:46,type:"carry"}] },
      { note:"断球后的快速决策：4 号、7 号两侧散开给 9 号传球选项——边线球防守的终点是一次三打二。",
        moves:[{id:"b",x:78,y:38,type:"pass"},{id:4,x:44,y:52,type:"run"},{id:7,x:56,y:26,type:"run"},{id:"o1",x:90,y:46,type:"run"}] },
    ],
  },
  {
    id:"fd-gkarea", gameType:"futsal", phase:"def", formation:"any", styles:["block"],
    title:"门将指挥的阵地防守", difficulty:2,
    summary:"五人制门将是全场唯一能看穿阵型的人：防守站位、压迫时机、危险提示全由门将口令驱动——训练门将就是训练整条防线。",
    refs:["fifa-manual","fifa-laws"],
    keyPoints:[
      "门将三句口令：「压！」（上抢信号）「收！」（退防信号）「右边！」（球在哪侧）",
      "门将站位：跟着球移动，永远在球与球门连线上，距门 3-5 米",
      "出击时机：对方接球背对球门、球弹起超过膝盖、单刀球——门将决定",
      "外场人必须回头确认门将手势——防线靠眼睛和耳朵同时工作",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:10,y:50},{id:2,num:2,team:"own",x:26,y:34},{id:4,num:4,team:"own",x:24,y:58},
      {id:7,num:7,team:"own",x:44,y:28},{id:9,num:9,team:"own",x:44,y:70},
      {id:"o1",num:1,team:"oppgk",x:6,y:50},
      {id:"o2",num:4,team:"opp",x:58,y:36},{id:"o3",num:6,team:"opp",x:56,y:62},{id:"o4",num:8,team:"opp",x:76,y:50},
      {id:"b",team:"ball",x:58,y:62},
    ],
    steps:[
      { note:"对方阵地战渗透：门将喊「右边！收！」——全队随球向右收，封中放边。",
        moves:[{id:2,x:30,y:40,type:"run"},{id:4,x:28,y:62,type:"run"},{id:7,x:48,y:34,type:"run"},{id:9,x:50,y:68,type:"run"},{id:1,x:13,y:49,type:"run"}] },
      { note:"6 号试图直塞找 8 号：门将提前喊「中间堵！」4 号横移封线。",
        moves:[{id:4,x:38,y:56,type:"run"},{id:"b",x:76,y:50,type:"pass"},{id:"o4",x:76,y:50,type:"run"}] },
      { note:"8 号背对球门接球——门将喊「压！」：这是上抢信号，9 号曲线逼上。",
        moves:[{id:9,x:70,y:62,type:"run"},{id:7,x:58,y:40,type:"run"},{id:"o4",x:80,y:46,type:"run"}] },
      { note:"压迫成功夺球：门将第一时间喊「抬头！」——转换进攻从门将的声音开始。",
        moves:[{id:"b",x:56,y:40,type:"pass"},{id:7,x:62,y:38,type:"run"},{id:9,x:76,y:56,type:"run"}] },
      { note:"门将的声音贯穿全程：夺球后立刻喊「稳住！」——先保球权再推进，指挥防守的嘴同样是指挥进攻的嘴。",
        moves:[{id:"b",x:60,y:38,type:"carry"},{id:7,x:66,y:40,type:"carry"},{id:9,x:80,y:54,type:"run"}] },
    ],
  },
];

const FIELD8_ATTACK = [
  {
    id:"sa-over", gameType:"field8", phase:"atk", formation:"s-331", styles:["wing"],
    title:"边路超载 · 倒三角终结", difficulty:2,
    summary:"左路三人成组制造 3v2，下底后倒三角回传，后排中场插上推射——现代足球最高效的终结方式。",
    refs:["fa-dna","rfef-8"],
    keyPoints:[
      "超载三人组：边后卫 + 边中场 + 前腰/前锋斜插，局部永远多一人",
      "倒三角（Cutback）传中点：小禁区角附近，落地快、包抄点多",
      "后排插上时机：传中起脚瞬间启动，目标点是小禁区角（Timing）",
      "包抄三人就位：近门柱、小禁区角、远门柱各一人",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:6,y:50},{id:2,num:2,team:"own",x:20,y:24},{id:3,num:3,team:"own",x:17,y:50},
      {id:4,num:4,team:"own",x:20,y:76},{id:8,num:8,team:"own",x:44,y:24},{id:6,num:6,team:"own",x:40,y:50},
      {id:10,num:10,team:"own",x:44,y:76},{id:9,num:9,team:"own",x:66,y:50},
      {id:"b",team:"ball",x:17,y:50},
      {id:"o1",num:5,team:"opp",x:48,y:20},{id:"o2",num:7,team:"opp",x:50,y:53},{id:"o3",num:11,team:"opp",x:52,y:80},
      {id:"og",num:1,team:"oppgk",x:93,y:50},
    ],
    steps:[
      { note:"3 号（左中卫）带球推进引出对方 5 号，8 号（左中场）横向内收接应。",
        moves:[{id:3,x:26,y:38,type:"carry"},{id:"b",x:26,y:38,type:"carry"},{id:8,x:38,y:30,type:"run"}] },
      { note:"3 号传 8 号后套边超载——左路瞬间 3 打 2。",
        moves:[{id:"b",x:38,y:30,type:"pass"},{id:3,x:40,y:12,type:"run"},{id:"o1",x:42,y:26,type:"run"}] },
      { note:"8 号脚后跟/横敲套边的 3 号，自己转身切禁区。",
        moves:[{id:"b",x:40,y:12,type:"pass"},{id:8,x:52,y:26,type:"run"}] },
      { note:"3 号下底到底线，观察包抄点后倒三角回传——传小禁区角，不传门前高空球。",
        moves:[{id:3,x:72,y:14,type:"carry"},{id:"b",x:72,y:14,type:"carry"},{id:9,x:66,y:44,type:"run"}] },
      { note:"6 号从中路后排插上到位，不停球直接推射。",
        moves:[{id:"b",x:62,y:34,type:"pass"},{id:6,x:56,y:44,type:"run"},{id:"b",x:90,y:43,type:"shot"}] },
    ],
  },
  {
    id:"sa-overlap", gameType:"field8", phase:"atk", formation:"s-322", styles:["wing"],
    title:"边锋内切 · 后卫套边传中", difficulty:2,
    summary:"边锋内切带走对方边后卫，右后卫从身后套边接直塞下底传中，双前锋三点包抄。",
    refs:["rfef-8","fa-cap"],
    keyPoints:[
      "内切 + 套边是固定组合：边锋向内，身后空间留给套边后卫",
      "套边启动时机：边锋触球瞬间启动，传直塞才有提前量",
      "传中目标：近门柱 6 码区地滚球/半高球，不轻易起高球",
      "包抄层次：近门柱一人、点球点一人、后点一人，相互拉开间距",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:6,y:50},{id:2,num:2,team:"own",x:20,y:26},{id:3,num:3,team:"own",x:17,y:50},
      {id:4,num:4,team:"own",x:20,y:74},{id:6,num:6,team:"own",x:42,y:38},{id:8,num:8,team:"own",x:42,y:62},
      {id:11,num:11,team:"own",x:56,y:76},{id:9,num:9,team:"own",x:68,y:44},
      {id:"b",team:"ball",x:42,y:62},
      {id:"o1",num:7,team:"opp",x:50,y:66},{id:"o2",num:5,team:"opp",x:46,y:46},{id:"o3",num:10,team:"opp",x:62,y:50},
      {id:"og",num:1,team:"oppgk",x:93,y:50},
    ],
    steps:[
      { note:"11 号（右边锋）接 8 号传球后内切，把对方 7 号带进中路。",
        moves:[{id:11,x:56,y:64,type:"carry"},{id:"b",x:56,y:64,type:"pass"},{id:"o1",x:52,y:60,type:"run"}] },
      { note:"2 号（右后卫）沿边线套边——11 号触球瞬间启动，不早不晚。",
        moves:[{id:2,x:52,y:86,type:"run"},{id:11,x:60,y:60,type:"run"}] },
      { note:"11 号一脚直塞给套边的 2 号，穿过整条防线。",
        moves:[{id:"b",x:62,y:84,type:"pass"},{id:2,x:62,y:86,type:"run"},{id:"o1",x:58,y:68,type:"run"}] },
      { note:"2 号下底观察：9 号冲近门柱，8 号到点球点，11 号包后点。",
        moves:[{id:2,x:78,y:84,type:"carry"},{id:"b",x:78,y:84,type:"carry"},{id:9,x:78,y:48,type:"run"},{id:8,x:62,y:52,type:"run"}] },
      { note:"地滚球扫向近门柱，9 号抢在门将前铲射入网。",
        moves:[{id:"b",x:84,y:46,type:"pass"},{id:"b",x:91,y:47,type:"shot"},{id:9,x:84,y:46,type:"run"}] },
    ],
  },
  {
    id:"sa-build", gameType:"field8", phase:"atk", formation:"s-331", styles:["central","possession"],
    title:"三线推进 · 穿线传球", difficulty:3,
    summary:"门将-三中卫-后腰-前场三角形推进，用“穿线传球”直接打穿对方第一道压迫——西班牙位置足球的八人制教材。",
    refs:["laliga-pos","rfef-8"],
    keyPoints:[
      "三角形网络：持球人永远要有两个接应角度，像三角形一样滚动前进",
      "穿线传球（entre líneas）：一脚传球同时穿过两名防守人，价值最高",
      "引压再打：先横传引对方上抢，身后才是传球通道（Deception）",
      "推进慢不可怕，回传也不丢人——丢球权才是罪过",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:6,y:50},{id:2,num:2,team:"own",x:20,y:24},{id:3,num:3,team:"own",x:17,y:50},
      {id:4,num:4,team:"own",x:20,y:76},{id:6,num:6,team:"own",x:40,y:50},{id:8,num:8,team:"own",x:44,y:24},
      {id:10,num:10,team:"own",x:44,y:76},{id:9,num:9,team:"own",x:68,y:50},
      {id:"b",team:"ball",x:6,y:50},
      {id:"o1",num:7,team:"opp",x:40,y:26},{id:"o2",num:5,team:"opp",x:38,y:50},{id:"o3",num:11,team:"opp",x:40,y:74},
      {id:"og",num:1,team:"oppgk",x:93,y:50},
    ],
    steps:[
      { note:"门将开球给 3 号，2 号横向拉开——第一线出球三人组成型。",
        moves:[{id:"b",x:17,y:50,type:"pass"},{id:2,x:22,y:16,type:"run"}] },
      { note:"3 号横传 2 号，引动对方 7 号上抢，中路被拉开一条缝。",
        moves:[{id:"b",x:22,y:16,type:"pass"},{id:"o1",x:30,y:20,type:"run"}] },
      { note:"2 号直接穿线传球：一脚穿透上抢人与中路防守人，找到 6 号。",
        moves:[{id:"b",x:40,y:50,type:"pass"},{id:6,x:40,y:50,type:"run"},{id:"o2",x:44,y:48,type:"run"}] },
      { note:"6 号转身（扫一眼后再触球），8 号已从肋部前插接应。",
        moves:[{id:8,x:56,y:30,type:"run"},{id:6,x:48,y:50,type:"carry"},{id:"b",x:48,y:50,type:"carry"}] },
      { note:"6 号直塞 8 号，8 号下底传中——9 号包抄近点。",
        moves:[{id:"b",x:56,y:30,type:"pass"},{id:8,x:70,y:24,type:"run"},{id:"b",x:70,y:24,type:"carry"}] },
      { note:"横传中路，9 号推射空门。",
        moves:[{id:"b",x:82,y:46,type:"pass"},{id:"b",x:90,y:47,type:"shot"},{id:9,x:82,y:48,type:"run"}] },
    ],
  },
  {
    id:"sa-third", gameType:"field8", phase:"atk", formation:"s-331", styles:["central"],
    title:"第三人跑动 · 肋部直塞", difficulty:3,
    summary:"前锋回做当诱饵，真正的杀机是肋部前插的中场——用第三人跑动打穿中路防线。",
    refs:["fa-cap","laliga-pos"],
    keyPoints:[
      "回做前锋是诱饵：他的触球让对方的 3 号（盯人中卫）看球",
      "第三人（8 号）从中卫的视线盲区（肋部）斜插",
      "直塞提前量：往人跑的方向传，不往人现在的位置传",
      "注意越位：8 号启动时机在传球出脚的瞬间（Timing）",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:6,y:50},{id:2,num:2,team:"own",x:20,y:24},{id:3,num:3,team:"own",x:17,y:50},
      {id:4,num:4,team:"own",x:20,y:76},{id:6,num:6,team:"own",x:38,y:50},{id:8,num:8,team:"own",x:44,y:24},
      {id:10,num:10,team:"own",x:44,y:76},{id:9,num:9,team:"own",x:64,y:50},
      {id:"b",team:"ball",x:38,y:50},
      {id:"o1",num:7,team:"opp",x:50,y:24},{id:"o2",num:5,team:"opp",x:52,y:48},{id:"o3",num:11,team:"opp",x:50,y:72},
      {id:"og",num:1,team:"oppgk",x:93,y:50},
    ],
    steps:[
      { note:"6 号直传 9 号（回做点），9 号背身接球，对方 5 号上前逼抢。",
        moves:[{id:"b",x:64,y:50,type:"pass"},{id:"o2",x:58,y:50,type:"run"}] },
      { note:"9 号一脚回敲 6 号——防守的注意力全部被这次回传吸住。",
        moves:[{id:"b",x:38,y:50,type:"pass"},{id:9,x:60,y:48,type:"run"}] },
      { note:"真正的杀机：8 号从对方 5 号的视线盲区沿肋部斜插——这就是第三人。",
        moves:[{id:8,x:66,y:30,type:"run"},{id:"o1",x:54,y:28,type:"run"}] },
      { note:"6 号不停球直塞肋部——传的是 8 号将要到达的空当。",
        moves:[{id:"b",x:70,y:30,type:"pass"},{id:8,x:72,y:32,type:"run"}] },
      { note:"8 号形成半单刀，观察后横传后点，10 号包抄推射。",
        moves:[{id:"b",x:84,y:58,type:"pass"},{id:10,x:82,y:60,type:"run"},{id:"b",x:90,y:56,type:"shot"}] },
    ],
  },
  {
    id:"sa-counter", gameType:"field8", phase:"atk", formation:"s-322", styles:["counter","fast"],
    title:"快速反击 · 3v2 六秒战", difficulty:2,
    summary:"断球后 6 秒内的黄金反击窗口：第一时间直塞，双前锋斜线冲刺，第三人居中跟进。",
    refs:["uefa-tg","fa-dna"],
    keyPoints:[
      "6 秒原则：断球后 6 秒内完成射门，否则对手落位",
      "第一时间出球：断球人不粘球，抬头第一眼就找前锋",
      "跑位形状：双前锋一前一后斜线拉开，让 2 名防守人不能同时顾两人",
      "跟进第三人：断球人自己随后插上，做二点保护",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:6,y:50},{id:2,num:2,team:"own",x:24,y:30},{id:4,num:4,team:"own",x:24,y:70},
      {id:3,num:3,team:"own",x:17,y:50},{id:6,num:6,team:"own",x:40,y:50},
      {id:8,num:8,team:"own",x:44,y:62},{id:9,num:9,team:"own",x:56,y:36},{id:11,num:11,team:"own",x:58,y:64},
      {id:"b",team:"ball",x:40,y:50},
      {id:"o1",num:4,team:"opp",x:56,y:50},{id:"o2",num:5,team:"opp",x:66,y:50},
      {id:"og",num:1,team:"oppgk",x:93,y:50},
    ],
    steps:[
      { note:"6 号中场断球！第一时间抬头——两个前锋已经在跑。",
        moves:[{id:6,x:42,y:48,type:"run"}] },
      { note:"9 号斜线冲左肋、11 号冲右肋——把两名防守人向两侧拉开。",
        moves:[{id:9,x:64,y:26,type:"run"},{id:11,x:64,y:72,type:"run"},{id:"o1",x:60,y:44,type:"run"},{id:"o2",x:62,y:56,type:"run"}] },
      { note:"6 号直塞冲得最快的 9 号——穿过两名防守人中间的缝。",
        moves:[{id:"b",x:68,y:24,type:"pass"},{id:9,x:70,y:22,type:"run"}] },
      { note:"9 号带球突入禁区，吸引出击的门将。",
        moves:[{id:9,x:80,y:28,type:"carry"},{id:"b",x:80,y:28,type:"carry"},{id:"og",x:90,y:44,type:"run"}] },
      { note:"横敲中路空门，11 号跟进推射——断球到射门仅用 6 秒。",
        moves:[{id:"b",x:86,y:52,type:"pass"},{id:11,x:84,y:56,type:"run"},{id:"b",x:92,y:52,type:"shot"}] },
    ],
  },
  {
    id:"sa-gkplus", gameType:"field8", phase:"atk", formation:"s-331", styles:["possession","central"],
    title:"门将 +1 · 破高压构建", difficulty:3,
    summary:"对方全员压上时，门将是天然的人数优势（+1）：三中卫拉满宽度，门将成为自由人完成转移。",
    refs:["laliga-pos","rfef-8"],
    keyPoints:[
      "被压时第一原则：把宽度拉到极限——三中卫分别贴边线",
      "门将是 +1：对方 7 人压 7 人，多出来的门将永远自由",
      "两脚内出球：门将拿球不超过 3 秒，转移或推进绝不回传横传失误",
      "破压成功后第一时间向前：高压的身后是全世界最大的空间",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:6,y:50},{id:2,num:2,team:"own",x:22,y:14},{id:3,num:3,team:"own",x:19,y:50},
      {id:4,num:4,team:"own",x:22,y:86},{id:6,num:6,team:"own",x:38,y:50},{id:8,num:8,team:"own",x:50,y:30},
      {id:10,num:10,team:"own",x:50,y:70},{id:9,num:9,team:"own",x:62,y:50},
      {id:"b",team:"ball",x:6,y:50},
      {id:"o1",num:7,team:"opp",x:36,y:18},{id:"o2",num:5,team:"opp",x:34,y:50},{id:"o3",num:8,team:"opp",x:36,y:82},
      {id:"o4",num:10,team:"opp",x:50,y:34},{id:"o5",num:11,team:"opp",x:56,y:62},{id:"og",num:1,team:"oppgk",x:93,y:50},
    ],
    steps:[
      { note:"对方 5 人压过半场。三中卫贴边线拉满宽度，6 号回撤接应，8 号、10 号压住对方两肋。",
        moves:[{id:2,x:18,y:8,type:"run"},{id:4,x:18,y:85,type:"run"},{id:6,x:32,y:50,type:"run"}] },
      { note:"门将持球邀压，等对方 5 号上抢——这就是“钓”。",
        moves:[{id:"o2",x:24,y:50,type:"run"}] },
      { note:"门将横传给已拉开的 2 号——越过上抢人的头顶。",
        moves:[{id:"b",x:18,y:8,type:"pass"},{id:1,x:10,y:44,type:"run"}] },
      { note:"2 号发现中路大空当：6 号身前无人，直传 6 号。",
        moves:[{id:"b",x:36,y:50,type:"pass"},{id:6,x:42,y:50,type:"run"}] },
      { note:"6 号转身推进，9 号前插带走中卫，8 号从肋部接应到位——破压完成，进入进攻三区。",
        moves:[{id:6,x:56,y:50,type:"carry"},{id:"b",x:56,y:50,type:"carry"},{id:9,x:72,y:44,type:"run"},{id:8,x:60,y:32,type:"run"}] },
    ],
  },
];

const FIELD8_DEFENSE = [
  {
    id:"sd-hp", gameType:"field8", phase:"def", formation:"s-331", styles:["press"],
    title:"高位逼抢 · 引向边路围剿", difficulty:3,
    summary:"以前锋逼抢为触发器，全队像一块地毯整体移动：封中路、放边路，在边线完成围剿。",
    refs:["uefa-tg","fa-dna"],
    keyPoints:[
      "逼抢触发器（Trigger）：对方后卫接门将回传球、停大、背对进攻方向——任一出现就全员启动",
      "曲线跑封内放外：逼球人跑弧线，把持球人往边线“赶”",
      "整体移动像一块地毯：前锋压、中场跟、后卫线整体前压 5 米",
      "边线围剿：边后卫上抢 + 边中场内收关门，两分钟内解决战斗",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:14,y:50},{id:2,num:2,team:"own",x:28,y:28},{id:3,num:3,team:"own",x:26,y:50},
      {id:4,num:4,team:"own",x:28,y:72},{id:8,num:8,team:"own",x:48,y:30},{id:6,num:6,team:"own",x:46,y:50},
      {id:10,num:10,team:"own",x:48,y:70},{id:9,num:9,team:"own",x:66,y:50},
      {id:"o1",num:1,team:"oppgk",x:6,y:50},
      {id:"o2",num:7,team:"opp",x:20,y:20},{id:"o3",num:5,team:"opp",x:18,y:50},{id:"o4",num:11,team:"opp",x:20,y:80},
      {id:"b",team:"ball",x:20,y:80},
    ],
    steps:[
      { note:"触发器出现：对方门将回传 11 号。9 号立刻启动曲线跑——封中路、放边路。",
        moves:[{id:"b",x:20,y:80,type:"pass"},{id:9,x:28,y:70,type:"run"}] },
      { note:"全队像地毯一样前压：中场三人各跟一人，后卫线整体上提 5 米。",
        moves:[{id:6,x:52,y:44,type:"run"},{id:10,x:54,y:64,type:"run"},{id:2,x:34,y:22,type:"run"},{id:4,x:34,y:66,type:"run"},{id:3,x:32,y:48,type:"run"},{id:1,x:22,y:50,type:"run"}] },
      { note:"11 号被逼向边线，10 号内收准备关门，边后卫 4 号上抢。",
        moves:[{id:"o4",x:14,y:86,type:"carry"},{id:"b",x:14,y:86,type:"carry"},{id:10,x:40,y:78,type:"run"},{id:4,x:36,y:80,type:"run"}] },
      { note:"口袋合拢：持球人传球线路全被封死，仓促大脚被 3 号顶回。",
        moves:[{id:"b",x:34,y:64,type:"pass"},{id:3,x:38,y:58,type:"run"}] },
      { note:"二点球拿下就地反击——对方刚压上，身后全是空当。",
        moves:[{id:"b",x:56,y:44,type:"pass"},{id:6,x:56,y:46,type:"run"},{id:9,x:66,y:36,type:"run"}] },
    ],
  },
  {
    id:"sd-mid", gameType:"field8", phase:"def", formation:"s-331", styles:["mid","block"],
    title:"中场拦截 · 紧凑 mid-block", difficulty:1,
    summary:"中线后 5-10 米落位，三线间距 8-10 米：不冒进上抢，用紧凑的阵型把中路挤成“堵墙”。",
    refs:["fa-dna","uefa-tg"],
    keyPoints:[
      "三线间距 8-10 米：线与线之间站不下一个进攻人，就没有渗透空间",
      "第一抢由中场发起，后卫线只封堵不上抢——不冒进是纪律",
      "球到边路同侧压、中路收，弱侧边中场内收保护肋部",
      "对手横传回传是好事：时间在我这边，等他犯错",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:10,y:50},{id:2,num:2,team:"own",x:30,y:28},{id:3,num:3,team:"own",x:28,y:50},
      {id:4,num:4,team:"own",x:30,y:72},{id:8,num:8,team:"own",x:48,y:32},{id:6,num:6,team:"own",x:45,y:50},
      {id:10,num:10,team:"own",x:48,y:68},{id:9,num:9,team:"own",x:56,y:50},
      {id:"o1",num:1,team:"oppgk",x:6,y:50},
      {id:"o2",num:7,team:"opp",x:56,y:30},{id:"o3",num:5,team:"opp",x:54,y:50},{id:"o4",num:11,team:"opp",x:56,y:70},
      {id:"b",team:"ball",x:54,y:50},
    ],
    steps:[
      { note:"对方推进过中线：全队在中线后落位，三线间距 8-10 米，阵型像“三堵墙”。",
        moves:[{id:9,x:50,y:50,type:"run"}] },
      { note:"球进中路：6 号、8 号同时向持球人收缩夹角，9 号切断回做线路。",
        moves:[{id:"o3",x:46,y:50,type:"carry"},{id:"b",x:46,y:50,type:"carry"},{id:6,x:52,y:46,type:"run"},{id:8,x:56,y:36,type:"run"}] },
      { note:"对方只能横向转移：同侧的 10 号立刻接手压迫，其他人横移半格。",
        moves:[{id:"b",x:44,y:70,type:"pass"},{id:10,x:52,y:66,type:"run"},{id:6,x:46,y:52,type:"run"},{id:8,x:44,y:34,type:"run"}] },
      { note:"中卫 3 号指挥防线整体横移，始终把中路堵死——对方的渗透空间为零。",
        moves:[{id:2,x:36,y:24,type:"run"},{id:3,x:34,y:50,type:"run"},{id:4,x:36,y:74,type:"run"}] },
      { note:"对方回传门将，全队上提压缩——把压迫线重新推回中线。",
        moves:[{id:"b",x:12,y:46,type:"pass"},{id:9,x:60,y:50,type:"run"},{id:8,x:54,y:34,type:"run"},{id:10,x:56,y:66,type:"run"}] },
    ],
  },
  {
    id:"sd-low", gameType:"field8", phase:"def", formation:"s-421", styles:["low","block"],
    title:"低位区域 · 保护禁区", difficulty:1,
    summary:"整体退到禁区前沿，双中场护住弧顶，边后卫内收变五后卫：对手控球我守门。",
    refs:["fa-dna"],
    keyPoints:[
      "低位三任务：封射门角度、防传中落点、保护二点球",
      "边后卫内收：禁区内形成 5 人密集，但弧顶必须有人（双中场）",
      "第一延缓（Delay）：就近球员贴住持球人不抢，为队友退防赢时间",
      "解围纪律：向边线、向高、向远——中路绝不横传",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:6,y:50},{id:2,num:2,team:"own",x:18,y:20},{id:4,num:4,team:"own",x:15,y:40},
      {id:5,num:5,team:"own",x:15,y:60},{id:3,num:3,team:"own",x:18,y:80},{id:6,num:6,team:"own",x:30,y:38},
      {id:8,num:8,team:"own",x:30,y:62},{id:9,num:9,team:"own",x:44,y:50},
      {id:"o1",num:1,team:"oppgk",x:92,y:50},
      {id:"o2",num:7,team:"opp",x:56,y:24},{id:"o3",num:10,team:"opp",x:52,y:50},{id:"o4",num:11,team:"opp",x:56,y:76},
      {id:"b",team:"ball",x:52,y:50},
    ],
    steps:[
      { note:"全队退守：四后卫横排封禁区，双中场护弧顶，9 号退回第一延缓线。",
        moves:[{id:9,x:38,y:50,type:"run"},{id:6,x:26,y:40,type:"run"},{id:8,x:26,y:60,type:"run"}] },
      { note:"9 号贴住持球人只贴不抢（Delay），为他身后队友退防赢 3 秒。",
        moves:[{id:9,x:46,y:48,type:"run"},{id:"o3",x:46,y:50,type:"run"}] },
      { note:"对方转移边路：2 号外扩顶传中点，6 号横移补肋部空当。",
        moves:[{id:"b",x:56,y:24,type:"pass"},{id:2,x:30,y:16,type:"run"},{id:6,x:32,y:30,type:"run"},{id:"o2",x:56,y:24,type:"run"}] },
      { note:"传中进禁区：门将指挥近门柱有人，中卫 5 号抢前点解围。",
        moves:[{id:"b",x:26,y:40,type:"pass"},{id:5,x:20,y:46,type:"run"},{id:1,x:8,y:48,type:"run"}] },
      { note:"解围向边线踢出，危险解除——重新组织第二波防守。",
        moves:[{id:"b",x:60,y:10,type:"pass"},{id:9,x:44,y:44,type:"run"}] },
      { note:"解围后的 3 秒最危险：门将指挥全队前压造越位线，把防线从禁区推回中场——低位的终点是重新夺回纵深。",
        moves:[{id:2,x:30,y:36,type:"run"},{id:4,x:28,y:50,type:"run"},{id:8,x:30,y:64,type:"run"},{id:1,x:12,y:50,type:"run"}] },
    ],
  },
  {
    id:"sd-trap", gameType:"field8", phase:"def", formation:"s-331", styles:["press","mid"],
    title:"边路围剿陷阱 · 关门", difficulty:2,
    summary:"故意把持球人“请”到边线，触线瞬间两人关门一人切线路——提前设计好的捕兽夹。",
    refs:["uefa-tg","fa-cap"],
    keyPoints:[
      "陷阱的耐心：先“放”他前进，急吼吼上抢就打草惊蛇",
      "关门时机：持球人触球/低头瞬间的合围，两人动作要同一拍",
      "第三人提前切所有出球线路，让陷阱里的人只能犯错",
      "抢下后第一时间从边路直塞前锋——对方防线还没回位",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:14,y:50},{id:2,num:2,team:"own",x:30,y:26},{id:3,num:3,team:"own",x:27,y:50},
      {id:4,num:4,team:"own",x:30,y:74},{id:8,num:8,team:"own",x:50,y:30},{id:6,num:6,team:"own",x:46,y:50},
      {id:10,num:10,team:"own",x:52,y:70},{id:9,num:9,team:"own",x:64,y:50},
      {id:"o1",num:1,team:"oppgk",x:6,y:50},
      {id:"o2",num:7,team:"opp",x:48,y:40},{id:"o3",num:5,team:"opp",x:44,y:50},{id:"o4",num:11,team:"opp",x:52,y:78},
      {id:"b",team:"ball",x:44,y:50},
    ],
    steps:[
      { note:"设局：10 号故意让出外侧通道，只封内线——把对方 11 号往边线“请”。",
        moves:[{id:10,x:56,y:74,type:"run"},{id:"b",x:52,y:78,type:"pass"},{id:"o4",x:52,y:78,type:"run"}] },
      { note:"11 号带球触线瞬间：10 号、2 号同一拍关门——口袋收口。",
        moves:[{id:"o4",x:44,y:84,type:"carry"},{id:"b",x:44,y:84,type:"carry"},{id:10,x:48,y:82,type:"run"},{id:2,x:34,y:66,type:"run"}] },
      { note:"第三人 6 号早已切掉中路回传线路——陷阱里的人没有任何出口。",
        moves:[{id:6,x:52,y:58,type:"run"},{id:"o2",x:46,y:48,type:"run"}] },
      { note:"被迫传向中路，6 号提前半步断球——陷阱捕获成功。",
        moves:[{id:"b",x:52,y:56,type:"pass"},{id:6,x:54,y:54,type:"run"}] },
      { note:"就地反击：6 号直塞反跑的 9 号，对方防线还没回位。",
        moves:[{id:"b",x:70,y:44,type:"pass"},{id:9,x:72,y:46,type:"run"}] },
    ],
  },
  {
    id:"sd-cp", gameType:"field8", phase:"def", formation:"s-331", styles:["press","fast"],
    title:"由守转攻 · 6 秒反抢窗口", difficulty:2,
    summary:"丢球瞬间就近两人合围、全队切线路，6 秒内夺回球权；抢不回则整体退守 mid-block——一套完整的转换预案。",
    refs:["laliga-pos","uefa-tg"],
    keyPoints:[
      "丢球后 6 秒是黄金窗口：对方刚拿球阵型散开，立刻扑上去",
      "就近两人合围持球人，其他人 3 秒内切断所有向前线路",
      "6 秒抢不回：全员体面退守中场 block，绝不追着球满场跑",
      "反抢成功就地反击——对方由攻转守的阵型还没搭起来",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:14,y:50},{id:2,num:2,team:"own",x:30,y:28},{id:3,num:3,team:"own",x:27,y:50},
      {id:4,num:4,team:"own",x:30,y:72},{id:8,num:8,team:"own",x:50,y:30},{id:6,num:6,team:"own",x:48,y:50},
      {id:10,num:10,team:"own",x:50,y:70},{id:9,num:9,team:"own",x:64,y:50},
      {id:"o1",num:1,team:"oppgk",x:6,y:50},
      {id:"o2",num:7,team:"opp",x:56,y:38},{id:"o3",num:5,team:"opp",x:62,y:56},{id:"o4",num:11,team:"opp",x:44,y:60},
      {id:"b",team:"ball",x:44,y:60},
    ],
    steps:[
      { note:"丢球！最近的 6 号、10 号两秒内合围持球人 11 号——立刻反抢。",
        moves:[{id:6,x:48,y:56,type:"run"},{id:10,x:48,y:64,type:"run"}] },
      { note:"11 号被迫横传 7 号：8 号切断向中路的线路，9 号回追身后的接应点。",
        moves:[{id:"b",x:56,y:38,type:"pass"},{id:8,x:52,y:36,type:"run"},{id:9,x:60,y:44,type:"run"}] },
      { note:"7 号被迫转移 5 号，9 号预判启动——反抢范围扩大。",
        moves:[{id:"b",x:56,y:56,type:"pass"},{id:9,x:62,y:52,type:"run"},{id:"o3",x:60,y:54,type:"run"}] },
      { note:"9 号断球成功——丢球后第 4 秒重新拿回球权。",
        moves:[{id:"b",x:64,y:44,type:"carry"},{id:9,x:64,y:44,type:"carry"}] },
      { note:"直塞前插的 10 号——反抢直接转换为得分机会。",
        moves:[{id:"b",x:74,y:50,type:"pass"},{id:10,x:74,y:52,type:"run"}] },
    ],
  },
  {
    id:"sa-throw", gameType:"field8", phase:"atk", formation:"any", styles:["fast"],
    title:"界外球战术 · 快发与掷球配合", difficulty:1,
    summary:"八人制界外球是无越位年龄组最被浪费的进攻资源：快发直接打身后，大力掷球掷进禁区就是一次传中。",
    refs:["fa-dna","rfef-8"],
    keyPoints:[
      "快发判断：附近没有防守人压上来就立刻发——转身慢的防线最怕这个",
      "掷球规则：双手过顶、球从脑后经头顶掷出、双脚不离地",
      "长掷战术：一个大力掷手 + 禁区三点包抄，等于一次角球",
      "接掷球第一选择向前：回传只在没有向前空间时使用",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:6,y:50},{id:2,num:2,team:"own",x:20,y:26},{id:3,num:3,team:"own",x:17,y:50},
      {id:4,num:4,team:"own",x:20,y:74},{id:6,num:6,team:"own",x:38,y:50},
      {id:8,num:8,team:"own",x:52,y:40},{id:9,num:9,team:"own",x:58,y:60},
      {id:11,num:11,team:"own",x:70,y:30},
      {id:"b",team:"ball",x:2,y:34},
      {id:"o1",num:5,team:"opp",x:24,y:36},{id:"o2",num:3,team:"opp",x:22,y:52},{id:"o3",num:4,team:"opp",x:50,y:52},
      {id:"og",num:1,team:"oppgk",x:93,y:50},
    ],
    steps:[
      { note:"11 号在中前场边线捡球：对方 5 号还没贴上来——快发！掷给启动的 8 号。",
        moves:[{id:11,x:3,y:34,type:"run"},{id:"b",x:3,y:34,type:"pass"},{id:8,x:56,y:36,type:"run"}] },
      { note:"8 号胸部停球转身，正面带球推进——防线没组织好。",
        moves:[{id:8,x:60,y:36,type:"carry"},{id:"b",x:60,y:36,type:"carry"},{id:"o1",x:34,y:38,type:"run"}] },
      { note:"9 号斜插跑位带走 3 号，11 号发完球已经前插到边路接应。",
        moves:[{id:9,x:70,y:52,type:"run"},{id:11,x:56,y:22,type:"run"},{id:"o2",x:30,y:54,type:"run"}] },
      { note:"8 号直塞插上的 11 号——界外球三秒变单刀。",
        moves:[{id:"b",x:72,y:24,type:"pass"},{id:11,x:74,y:22,type:"run"}] },
      { note:"11 号横传中路，9 号包抄推射。",
        moves:[{id:"b",x:82,y:44,type:"pass"},{id:9,x:80,y:50,type:"run"},{id:"b",x:90,y:47,type:"shot"}] },
    ],
  },
  {
    id:"sa-corner", gameType:"field8", phase:"atk", formation:"any", styles:["wing"],
    title:"角球进攻 · 近远点+回做", difficulty:2,
    summary:"角球三威胁：近点一人抢前、远点两人层次包抄、弧顶一人收二点回做远射——每个角球都是一次阵地战资源。",
    refs:["fa-dna","uefa-tg"],
    keyPoints:[
      "分工固定：近点 1 人、远点 2 人（一前一后）、弧顶 1 人、后场留 3 人防反击",
      "开球脚法：内脚背弧线找近点，力量够越过第一步防守",
      "二点球是角球的一半：弧顶回做后的远射威胁极大",
      "无越位年龄组大胆站门前；有越位规则组注意启动时机",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:10,y:50},{id:2,num:2,team:"own",x:30,y:30},{id:3,num:3,team:"own",x:28,y:66},
      {id:6,num:6,team:"own",x:56,y:34},{id:8,num:8,team:"own",x:62,y:66},
      {id:9,num:9,team:"own",x:86,y:44},{id:10,num:10,team:"own",x:87,y:56},
      {id:7,num:7,team:"own",x:114,y:84},
      {id:"b",team:"ball",x:116,y:84},
      {id:"o1",num:5,team:"opp",x:84,y:34},{id:"o2",num:3,team:"opp",x:82,y:52},{id:"o3",num:4,team:"opp",x:84,y:68},
      {id:"og",num:1,team:"oppgk",x:94,y:50},
    ],
    steps:[
      { note:"7 号开角球：9 号冲近点，10 号埋伏远点，6 号 8 号准备抢二点。",
        moves:[{id:9,x:88,y:42,type:"run"},{id:6,x:60,y:38,type:"run"},{id:8,x:66,y:62,type:"run"}] },
      { note:"弧线球开向近点：9 号前点头球/脚尖一蹭改变方向。",
        moves:[{id:"b",x:88,y:42,type:"pass"},{id:9,x:89,y:45,type:"run"},{id:"og",x:92,y:45,type:"run"}] },
      { note:"球被顶出禁区弧顶——6 号早就在那等二点，不停球直接远射。",
        moves:[{id:"b",x:56,y:36,type:"pass"},{id:6,x:58,y:38,type:"run"},{id:"b",x:88,y:46,type:"shot"}] },
      { note:"被挡出底线？没关系，这已经是第二次角球威胁——对方防线越来越乱。",
        moves:[{id:"b",x:86,y:60,type:"pass"},{id:10,x:88,y:58,type:"run"},{id:"og",x:93,y:52,type:"run"}] },
      { note:"球权终被门将没收：2、3、6 号第一时间回撤落位防反击——角球的最后一项任务是别被反向打爆。",
        moves:[{id:"b",x:50,y:40,type:"pass"},{id:2,x:30,y:30,type:"run"},{id:3,x:28,y:52,type:"run"},{id:6,x:44,y:44,type:"run"}] },
    ],
  },
  {
    id:"sa-break", gameType:"field8", phase:"atk", formation:"s-331", styles:["possession","central"],
    title:"破密集防守 · 转移+斜插", difficulty:3,
    summary:"对手收回来打 5-2 低位怎么办：横向大范围转移拉开宽度，等防线移动的瞬间向弱侧肋部斜插——密集防守怕的是耐心和宽度。",
    refs:["laliga-pos","uefa-tg"],
    keyPoints:[
      "密集防守两条纪律：第一转移要快（2 脚内换边），第二不着急往里塞",
      "转移的意义：防线横移时必然出现肋部裂缝，斜插就在那时",
      "远射也是破密集武器：弧顶有人敢射，防线才敢出来",
      "两翼留宽度：边路的人不内收，宽度就是拉开蜂群的针",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:6,y:50},{id:2,num:2,team:"own",x:22,y:20},{id:3,num:3,team:"own",x:18,y:50},
      {id:4,num:4,team:"own",x:22,y:80},{id:6,num:6,team:"own",x:42,y:50},
      {id:8,num:8,team:"own",x:62,y:18},{id:10,num:10,team:"own",x:60,y:50},{id:9,num:9,team:"own",x:70,y:74},
      {id:"b",team:"ball",x:22,y:80},
      {id:"o1",num:2,team:"opp",x:44,y:34},{id:"o2",num:3,team:"opp",x:46,y:50},{id:"o3",num:4,team:"opp",x:44,y:66},
      {id:"og",num:1,team:"oppgk",x:93,y:50},
    ],
    steps:[
      { note:"对方中路三人密集落位。4 号持球，10 号回接做轴——第一脚快速转移开始。",
        moves:[{id:"b",x:20,y:80,type:"pass"},{id:10,x:56,y:50,type:"run"},{id:"o2",x:48,y:50,type:"run"}] },
      { note:"10 号一脚敲回 6 号，6 号抬头已看到左路大空当——2 脚内换边。",
        moves:[{id:"b",x:42,y:50,type:"pass"},{id:10,x:60,y:50,type:"run"}] },
      { note:"6 号长距离横转移 8 号——防线整体向右扑，左肋出现裂缝。",
        moves:[{id:"b",x:60,y:20,type:"pass"},{id:8,x:64,y:18,type:"run"},{id:"o1",x:56,y:30,type:"run"},{id:"o3",x:52,y:62,type:"run"}] },
      { note:"8 号不传中：内切两步斜塞左肋——9 号从密集区拉出来斜插裂缝。",
        moves:[{id:8,x:70,y:26,type:"carry"},{id:"b",x:70,y:26,type:"carry"},{id:9,x:62,y:66,type:"run"}] },
      { note:"9 号肋部单刀推远角——密集防守被一次转移+一次斜插解决。",
        moves:[{id:"b",x:76,y:56,type:"pass"},{id:9,x:78,y:56,type:"run"},{id:"b",x:89,y:52,type:"shot"}] },
    ],
  },
  {
    id:"sa-gkthrow", gameType:"field8", phase:"atk", formation:"any", styles:["counter","fast"],
    title:"门将手抛快攻", difficulty:2,
    summary:"对方全线压上时的黄金反击：门将没收球后 3 秒内手抛发动，两翼提前散开，前锋回头招手要球——手抛比开大脚精准十倍。",
    refs:["uefa-tg","fa-dna"],
    keyPoints:[
      "门将拿到球先抬头：对方阵型压上=身后有一个半场",
      "手抛选择：地滚球给最近的边后卫启动，或抛过头顶给前插中场",
      "两翼任务：门将持球瞬间边路立刻散开到边线——宽度是反击的跑道",
      "3 秒原则：门将持球超过 3 秒，对方已经回位",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:8,y:50},{id:2,num:2,team:"own",x:20,y:26},{id:3,num:3,team:"own",x:17,y:50},
      {id:4,num:4,team:"own",x:20,y:74},{id:6,num:6,team:"own",x:36,y:50},
      {id:8,num:8,team:"own",x:44,y:30},{id:9,num:9,team:"own",x:56,y:44},
      {id:11,num:11,team:"own",x:52,y:70},
      {id:"b",team:"ball",x:8,y:50},
      {id:"o1",num:5,team:"opp",x:40,y:36},{id:"o2",num:3,team:"opp",x:44,y:52},{id:"o3",num:4,team:"opp",x:40,y:68},
      {id:"og",num:1,team:"oppgk",x:93,y:50},
    ],
    steps:[
      { note:"门将没收对方传中：抬头看——对方压上一半，身后全是草地。两翼开始散开。",
        moves:[{id:2,x:14,y:14,type:"run"},{id:4,x:14,y:86,type:"run"},{id:8,x:52,y:22,type:"run"}] },
      { note:"门将手抛地滚球给右侧 8 号（最近的边路），反击启动只用 2 秒。",
        moves:[{id:"b",x:50,y:22,type:"pass"},{id:1,x:14,y:50,type:"run"}] },
      { note:"8 号沿边线推进，9 号从中路斜跑到右肋招手要球——一前一后两条冲刺线。",
        moves:[{id:8,x:66,y:20,type:"carry"},{id:"b",x:66,y:20,type:"carry"},{id:9,x:68,y:38,type:"run"},{id:"o1",x:54,y:30,type:"run"}] },
      { note:"8 号观察中路：11 号已经插到远门柱线，6 号在中场跟上保护。",
        moves:[{id:11,x:78,y:64,type:"run"},{id:6,x:48,y:46,type:"run"},{id:"o2",x:58,y:48,type:"run"}] },
      { note:"横传远门柱，11 号推空门——从没收球到进球不到 12 秒。",
        moves:[{id:"b",x:82,y:50,type:"pass"},{id:11,x:84,y:52,type:"run"},{id:"b",x:91,y:52,type:"shot"}] },
    ],
  },
  {
    id:"sd-offside", gameType:"field8", phase:"def", formation:"s-331", styles:["mid"],
    title:"整体防线与造越位", difficulty:3,
    summary:"有越位规则组的必修课：防线三人像一条线一样整体前压后撤，用统一的移动把对方前锋按在越位位置上。",
    refs:["uefa-tg","fa-dna"],
    keyPoints:[
      "造越位是全防线的合奏：居中中卫喊口令，三人同一拍前压",
      "压出时机：对方前锋背对球门接球、传球人摆腿瞬间——传出的那一刻压",
      "绝对纪律：三人中任何一个迟疑，越位陷阱就变单刀",
      "U11 以下无越位组不练此套路，重点练整体退防保护",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:10,y:50},{id:2,num:2,team:"own",x:36,y:28},{id:3,num:3,team:"own",x:34,y:50},
      {id:4,num:4,team:"own",x:36,y:72},{id:6,num:6,team:"own",x:50,y:50},
      {id:8,num:8,team:"own",x:62,y:32},{id:10,num:10,team:"own",x:62,y:68},
      {id:9,num:9,team:"own",x:74,y:50},
      {id:"o1",num:1,team:"oppgk",x:6,y:50},
      {id:"o2",num:2,team:"opp",x:56,y:30},{id:"o3",num:3,team:"opp",x:54,y:50},
      {id:"o4",num:9,team:"opp",x:56,y:70},
      {id:"b",team:"ball",x:56,y:30},
    ],
    steps:[
      { note:"对方中路组织：2 号持球观察，他的前锋 9 号贴着防线游弋找身后。",
        moves:[{id:"o4",x:58,y:66,type:"run"},{id:6,x:52,y:50,type:"run"}] },
      { note:"2 号摆腿要传身后的瞬间——防线口令「压！」三人同一拍向前冲。",
        moves:[{id:2,x:54,y:30,type:"run"},{id:2,x:36,y:28,type:"run"},{id:2,x:34,y:50,type:"run"},{id:2,x:36,y:72,type:"run"}] },
      { note:"传球出脚那刻防线已前压 5 米：9 号接球瞬间处于越位位置。",
        moves:[{id:"b",x:66,y:62,type:"pass"},{id:"o4",x:66,y:64,type:"run"}] },
      { note:"裁判鸣哨越位：门将开球，一次陷阱捕获——注意若没吹哨门将已出击清球。",
        moves:[{id:1,x:20,y:50,type:"run"},{id:"b",x:40,y:50,type:"pass"}] },
      { note:"陷阱的保险丝：若裁判没吹、9 号拿到了球——6 号后腰已经落在他回接线路上，中卫立刻回追，双保险不赌哨。",
        moves:[{id:"b",x:60,y:56,type:"pass"},{id:6,x:56,y:56,type:"run"},{id:3,x:44,y:50,type:"run"}] },
    ],
  },
  {
    id:"sd-freekick", gameType:"field8", phase:"def", formation:"any", styles:["block"],
    title:"任意球防守 · 人墙与盯人", difficulty:1,
    summary:"禁区前沿任意球防守三件事：人墙封近角上角、门将站远角视线位、其余人一对一看人不看球——细节决定这只丢不丢分。",
    refs:["fa-dna","uefa-tg"],
    keyPoints:[
      "人墙：距球 9.15m（规则），人数 2-3 人封近门柱上角",
      "门将站位：人墙封近上角，门将站远半边视线开阔处",
      "其他人一对一面朝球侧身盯人，站在人球之间",
      "二点保护：弧顶必须留一人——解围出来的二点球最危险",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:8,y:50},{id:2,num:2,team:"own",x:34,y:44},{id:3,num:3,team:"own",x:34,y:48},
      {id:4,num:4,team:"own",x:34,y:52},{id:6,num:6,team:"own",x:52,y:36},
      {id:8,num:8,team:"own",x:44,y:66},{id:9,num:9,team:"own",x:64,y:40},
      {id:10,num:10,team:"own",x:58,y:60},
      {id:"o1",num:1,team:"oppgk",x:6,y:50},
      {id:"o2",num:3,team:"opp",x:70,y:30},{id:"o3",num:4,team:"opp",x:72,y:58},
      {id:"b",team:"ball",x:72,y:44},
    ],
    steps:[
      { note:"禁区前沿任意球：2、3、4 号组三人墙封近门柱上角，门将站远角位。",
        moves:[{id:2,x:36,y:44,type:"run"},{id:3,x:36,y:48,type:"run"},{id:4,x:36,y:52,type:"run"},{id:1,x:12,y:52,type:"run"}] },
      { note:"其余人一对一看人：6 号盯 3 号后插上，8 号收弧顶保护二点。",
        moves:[{id:6,x:58,y:38,type:"run"},{id:8,x:50,y:54,type:"run"},{id:"o3",x:66,y:56,type:"run"}] },
      { note:"直接射门：人墙跳起封堵——近上角被封死，球被人墙挡出。",
        moves:[{id:"b",x:40,y:47,type:"pass"},{id:"o2",x:70,y:30,type:"run"}] },
      { note:"二点球落在弧顶：8 号提前站位第一时间解围——防守任务完整闭环。",
        moves:[{id:"b",x:54,y:52,type:"pass"},{id:8,x:54,y:54,type:"run"},{id:"b",x:74,y:14,type:"pass"}] },
      { note:"解围后重新出发：9 号前压逼对方中卫，防线整体上提 10 米——任意球防守的终点是把防线推回中场。",
        moves:[{id:9,x:74,y:40,type:"run"},{id:2,x:44,y:44,type:"run"},{id:3,x:42,y:50,type:"run"},{id:4,x:44,y:56,type:"run"}] },
    ],
  },
  {
    id:"sd-transition", gameType:"field8", phase:"def", formation:"any", styles:["fast"],
    title:"由攻转守 · 6 秒落位", difficulty:2,
    summary:"丢球后的 6 秒决定这波防守的生死：就近 2 人反抢、1 人保护、其余人按「先回中路再回位置」的顺序落位——争的不是一个球，是整条防线的时间。",
    refs:["laliga-pos","uefa-tg"],
    keyPoints:[
      "丢球瞬间角色自动分配：最近 2 人抢、第三人保护、边路人先回中路",
      "回位顺序：先回中路通道（堵中间），再回自己的位置",
      "6 秒没抢回：全员落位转 mid-block，绝不拖泥带水",
      "门将参与指挥：喊「落位」而不是喊「抢」——稳字当头",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:14,y:50},{id:2,num:2,team:"own",x:32,y:28},{id:3,num:3,team:"own",x:28,y:50},
      {id:4,num:4,team:"own",x:32,y:72},{id:6,num:6,team:"own",x:48,y:40},
      {id:8,num:8,team:"own",x:52,y:62},{id:10,num:10,team:"own",x:66,y:34},
      {id:11,num:11,team:"own",x:68,y:70},
      {id:"o1",num:1,team:"oppgk",x:6,y:50},
      {id:"o2",num:2,team:"opp",x:60,y:44},{id:"o3",num:3,team:"opp",x:70,y:58},{id:"o4",num:4,team:"opp",x:76,y:40},
      {id:"b",team:"ball",x:62,y:56},
    ],
    steps:[
      { note:"前场丢球（模拟被断）：最近的 10 号、6 号立即反抢，8 号保护身位。",
        moves:[{id:"b",x:60,y:44,type:"pass"},{id:"o2",x:60,y:44,type:"run"},{id:10,x:62,y:36,type:"run"},{id:6,x:52,y:44,type:"run"}] },
      { note:"8 号不做第三个人：退守中路通道——「先回中路」原则。",
        moves:[{id:8,x:44,y:54,type:"run"},{id:10,x:58,y:40,type:"run"},{id:6,x:54,y:42,type:"run"}] },
      { note:"门将喊「落位！」：边路 2、4 号回中路收紧，防线 3 号居中指挥。",
        moves:[{id:2,x:34,y:34,type:"run"},{id:4,x:34,y:66,type:"run"},{id:3,x:32,y:50,type:"run"},{id:1,x:18,y:50,type:"run"}] },
      { note:"6 秒到：抢回失败即整体落位 mid-block——对方推进面对的是成型的墙。",
        moves:[{id:"b",x:66,y:50,type:"pass"},{id:"o3",x:66,y:56,type:"run"},{id:10,x:52,y:34,type:"run"},{id:6,x:46,y:50,type:"run"}] },
      { note:"落位后的第一反击机会：10 号在前场的反抢哪怕只逼对方回传一次，都为身后的落位多买 2 秒——反抢与落位从来不是二选一。",
        moves:[{id:"b",x:56,y:34,type:"pass"},{id:10,x:58,y:32,type:"run"},{id:11,x:60,y:64,type:"run"}] },
    ],
  },
];

/* ============================================================
   训练课主题库
   结构：热身 → 技术练习 → 技能练习 → 主题对抗 SSG → 整理与提问
   ============================================================ */
/* THEMES moved to js/themes.js (28 enhanced themes) */

/* ============================================================
   训练要求元数据（教案的"图与表"数据层）
   dg  布置图：模板|场地尺寸|图内说明
   std 成功标准（量化，训练中可当场检验）
   err 常见错误 → 纠正方法
   ============================================================ */
/* DRILL_META moved to js/drillmeta.js (112 enhanced entries) */

const TIPS = [
  "热身一定带球做：基础阶段每名球员训练 60 分钟，触球目标不低于 600 次。",
  "讲解不超过 20 秒——超过 20 秒，孩子们的耳朵就关闭了。",
  "每项练习结束用 1-2 个提问收尾：问出来的，比讲进去的记得牢。",
  "练“传了就跑”比练“传准”更重要：跑动是免费的，球权是珍贵的。",
  "小场地（4v4）触球量是 11 人制的 3 倍以上——多打小场。",
  "表扬具体行为，不表扬天赋：说“你回做了那一下很棒”，别说“你真有天赋”。",
  "一次训练只解决一个主题：热身、技术、对抗全围绕同一个词。",
  "门将要练脚：五人制门将是第十名外场球员，出球从 U10 就开始练。",
  "输球日先谈进步再谈失误——心理社交是四角模型的一角。",
  "把「倒三角」设为全队标配：它是青训阶段性价比最高的终结方式。",
];

/* ---------- 汇总 ---------- */
const FORMATIONS = [...FUTSAL_FORMATIONS, ...FIELD8_FORMATIONS];
const PATTERNS = [...FUTSAL_ATTACK, ...FUTSAL_DEFENSE, ...FIELD8_ATTACK, ...FIELD8_DEFENSE];

const STYLE_LABELS = {
  futsal:{ atk:{possession:"控制渗透",pivot:"支点战术",fast:"快速转换"}, def:{press:"高压逼抢",zone:"区域联防",block:"收缩保护",fast:"转换反抢"} },
  field8:{ atk:{wing:"边路为主",central:"中路渗透",counter:"快速反击",possession:"控球推进",fast:"快速转换"}, def:{press:"高位逼抢",mid:"中场拦截",low:"低位保护",block:"紧凑落位",fast:"转换反抢"} },
};
