/* ============================================================
   TacticLab 内容库
   坐标约定：x 0-100（左→右，己方进攻方向），y 0-100（上→下）
   球员 team：own 己方 / gk 己方门将 / opp 对方 / oppgk 对方门将 / ball 球
   动作 type：run 跑位(虚线) / pass 传球(实线) / carry 运球(实粗) / shot 射门(橙粗)
   依据标签 refs → 见 REFS
   ============================================================ */
"use strict";

/* ---------- 权威依据 ---------- */
const REFS = [
  { id:"fa-dna", name:"英格兰 DNA（England DNA）", org:"The FA · England Football Learning",
    url:"https://learn.englandfootball.com", tag:"英格兰",
    note:"英格兰各级国字号统一的踢球与执教哲学，五大支柱：我们是谁 / 我们怎么踢 / 未来的英格兰球员 / 我们怎么执教 / 我们怎么支持。本应用的进攻理念（控球、创造、勇敢）与执教流程（引导提问）均以此为准。" },
  { id:"fa-cap", name:"六大核心能力", org:"The FA · England Football Learning",
    url:"https://learn.englandfootball.com/articles-and-resources/coaching", tag:"英格兰",
    note:"Scanning 观察 · Timing 时机 · Movement 跑动 · Positioning 站位 · Deception 伪装 · Techniques 技术。本应用每个战术步骤的“指导要点”都尽量落到这六项能力上，而不是空喊口号。" },
  { id:"fa-4corner", name:"四角模型（Four Corner Model）", org:"The FA 教练员培训体系",
    url:"https://learn.englandfootball.com", tag:"英格兰",
    note:"技术 / 战术 / 身体 / 心理社交 四角同训。本应用生成的训练课，每项练习至少覆盖两角，并在指导要点中注明。" },
  { id:"fa-fp", name:"基础阶段要求（5-11 岁）", org:"The FA · Age Phase Priorities",
    url:"https://www.thefa.com", tag:"英格兰",
    note:"持球时：Stay on the ball, master the ball（先敢于持球，再谈配合）；Excite with the ball。U8-U10 训练以大量触球、1v1、乐趣为第一优先级，讲解不超过 20 秒。" },
  { id:"rfef-8", name:"西班牙基层赛制（Fútbol 8）", org:"RFEF 及大区足协竞赛规程",
    url:"https://rfef.es", tag:"西班牙",
    note:"西班牙 8-12 岁（Benjamín / Alevín 组）长期采用 7/8 人制小场地赛制，目标就是让每名球员在“真实比赛形状”里获得更多触球与决策。本应用八人制内容对应西班牙 alevín 组训练逻辑。" },
  { id:"laliga-pos", name:"位置足球与 Rondo", org:"LaLiga 青训方法论 · 拉玛西亚传统",
    url:"https://www.laliga.com", tag:"西班牙",
    note:"抢圈（Rondo）、位置轮转、穿线传球（entre líneas）、以人数围绕球——西班牙青训的传控基因。技术练习模块大量采用 rondo 与位置游戏。" },
  { id:"fifa-manual", name:"FIFA 五人制足球教练手册", org:"FIFA 官方出版物",
    url:"https://www.fifa.com", tag:"五人制",
    note:"五人制专项体系：4-0 / 3-1 / 2-2 / 1-2-1 轮转体系、支点（Pivo）运用、快速攻防转换。本应用五人制阵型与进攻套路的骨架以此为准。" },
  { id:"fifa-laws", name:"FIFA 五人制竞赛规则", org:"FIFA",
    url:"https://www.fifa.com", tag:"五人制",
    note:"40×20m 场地、4 秒发球、门将出球后在本方半场不得再触球（除非球过半场或对方触球）、累积犯规。所有五人制套路均已核对规则合法性。" },
  { id:"uefa-tg", name:"UEFA Training Ground", org:"UEFA",
    url:"https://www.uefa.com", tag:"欧洲",
    note:"欧足联官方训练与技战术资源库，用于交叉印证压迫触发器、由守转攻等主题的通行做法。" },
];
const refName = id => (REFS.find(r => r.id === id) || {}).name || id;
const refTag  = id => (REFS.find(r => r.id === id) || {}).tag || "依据";

/* ---------- 五人制阵型 ---------- */
const FUTSAL_FORMATIONS = [
  {
    id:"f-121", gameType:"futsal", name:"1-2-1 菱形", en:"Diamond",
    desc:"五人制最经典的基石阵型：一名后卫（Fixo）、两名边路（Ala）、一名支点（Pivo），天然形成菱形传球网络，攻守转换顺畅。",
    roles:[
      { num:"1", label:"门将", desc:"第十名外场球员：出球是进攻第一发起，站位随时上提。" },
      { num:"4", label:"Fixo 后卫", desc:"出球组织者，横向调度，防守时殿后保护。" },
      { num:"7/10", label:"Ala 边路", desc:"两翼发动机：内收配合、套边推进、回防落位。" },
      { num:"9", label:"Pivo 支点", desc:"顶在对方防线身前的柱子：要位、回做、做墙。" },
    ],
    pros:["攻守平衡，纵向连接最快","菱形四点天然互相保护","是学习一切轮转的基础"],
    cons:["对 Ala 的往返体能要求极高","Pivo 被盯死时中路容易拥堵","两翼身后是对方反击通道"],
    use:"青训首选基础阵型；对手打 2-2 时中路占优。",
    refs:["fifa-manual","fa-cap"],
    players:[
      {id:1,num:1,team:"gk",x:8,y:50,label:"GK"},
      {id:4,num:4,team:"own",x:24,y:50,label:"Fixo"},
      {id:7,num:7,team:"own",x:46,y:22,label:"Ala"},
      {id:10,num:10,team:"own",x:46,y:78,label:"Ala"},
      {id:9,num:9,team:"own",x:70,y:50,label:"Pivo"},
    ],
  },
  {
    id:"f-40", gameType:"futsal", name:"4-0 轮转", en:"Four-Zero Rotation",
    desc:"四名外场球员排成一线，通过持续轮转让防守始终无法稳定对位。五人制最复杂也最成熟的进攻体系，西班牙、巴西与伊朗国家队的常用武器。",
    roles:[
      { num:"1", label:"门将", desc:"拖后保护与出球，随时提醒轮转方向。" },
      { num:"—", label:"四外场", desc:"无固定位置：有人带球、有人下拉、有人轮补，全部角色流动。" },
    ],
    pros:["持续轮转让盯人防守不断换人错位","任何位置都能形成 2v1","被逼抢时永远有接应点"],
    cons:["学习成本最高，需要长期训练","轮转断档瞬间易被反击","对球员无球跑动理解力要求高"],
    use:"技术较好、训练量有保证的队伍；破解全场紧逼。",
    refs:["fifa-manual","laliga-pos"],
    players:[
      {id:1,num:1,team:"gk",x:8,y:50,label:"GK"},
      {id:2,num:2,team:"own",x:24,y:50,label:""},
      {id:3,num:3,team:"own",x:42,y:24,label:""},
      {id:4,num:4,team:"own",x:42,y:76,label:""},
      {id:5,num:5,team:"own",x:60,y:50,label:""},
    ],
  },
  {
    id:"f-22", gameType:"futsal", name:"2-2 方块", en:"Square",
    desc:"两名后卫 + 两名前锋的方块结构，覆盖均衡、易于理解，是年轻队伍和刚建队队伍的稳妥起点。",
    roles:[
      { num:"1", label:"门将", desc:"指挥方块整体横移。" },
      { num:"4/5", label:"双后卫", desc:"横向拉开出球，保持互相保护距离。" },
      { num:"9/10", label:"双前锋", desc:"压住对方防线，接长传与二点球。" },
    ],
    pros:["结构简单、覆盖均衡、易教易学","由守转攻时两点直接顶前","边路空当天然存在利于突破"],
    cons:["中路只有两脚，人数优势不明显","进攻套路相对有限、易被预判","对阵 1-2-1 时中场被打穿"],
    use:"初学队伍、U8-U10 打基础；比赛落后的简单强攻。",
    refs:["fifa-manual"],
    players:[
      {id:1,num:1,team:"gk",x:8,y:50,label:"GK"},
      {id:4,num:4,team:"own",x:24,y:32,label:""},
      {id:5,num:5,team:"own",x:24,y:68,label:""},
      {id:9,num:9,team:"own",x:50,y:32,label:""},
      {id:10,num:10,team:"own",x:50,y:68,label:""},
    ],
  },
  {
    id:"f-31", gameType:"futsal", name:"3-1 单支点", en:"Three-One",
    desc:"三名后卫加一名支点：出球点多、破紧逼利器，把组织权交给 Pivo 一人做轴。",
    roles:[
      { num:"1", label:"门将", desc:"作为第四名“后卫”参与构建，邀请对方上抢。" },
      { num:"2/4/5", label:"三后卫", desc:"宽站位拉开，一人持球两人给角度。" },
      { num:"9", label:"Pivo", desc:"压住对方最后线，做轴回做或反跑。" },
    ],
    pros:["对全场紧逼出球点最多","三后卫横向覆盖反击通道","Pivo 单点战术清晰"],
    cons:["中场衔接弱，前后场易脱节","依赖 Pivo 的背身质量","进攻推进慢时对手能从容落位"],
    use:"对手高压逼抢时；需要控制节奏的比赛。",
    refs:["fifa-manual","fifa-laws"],
    players:[
      {id:1,num:1,team:"gk",x:8,y:50,label:"GK"},
      {id:2,num:2,team:"own",x:20,y:24,label:""},
      {id:4,num:4,team:"own",x:17,y:50,label:""},
      {id:5,num:5,team:"own",x:20,y:76,label:""},
      {id:9,num:9,team:"own",x:66,y:50,label:"Pivo"},
    ],
  },
  {
    id:"f-211", gameType:"futsal", name:"2-1-1 变形菱形", en:"Two-One-One",
    desc:"菱形的防守变体：双后卫殿后互相保护，一名自由边路居中串联，支点顶前——牺牲部分进攻宽度，换取防守稳定性。",
    roles:[
      { num:"4/5", label:"双 Fixo", desc:"横向互相保护，一人上抢一人补位。" },
      { num:"8", label:"自由 Ala", desc:"居中串联前后场，进攻的第一接应点。" },
      { num:"9", label:"Pivo", desc:"顶住对方防线，做轴与反跑。" },
    ],
    pros:["双后卫结构防守最稳","适合保护领先优势","自由人角色培养决策能力"],
    cons:["进攻宽度不足，依赖边路个人突破","自由人被盯死则前后脱节","阵地战套路相对单一"],
    use:"领先保护比分；对阵攻击强队时的稳健选择。",
    refs:["fifa-manual"],
    players:[
      {id:1,num:1,team:"gk",x:8,y:50,label:"GK"},
      {id:4,num:4,team:"own",x:26,y:36,label:""},
      {id:5,num:5,team:"own",x:26,y:64,label:""},
      {id:8,num:8,team:"own",x:48,y:50,label:"8"},
      {id:9,num:9,team:"own",x:70,y:50,label:"9"},
    ],
  },
];

/* ---------- 八人制阵型 ---------- */
const FIELD8_FORMATIONS = [
  {
    id:"s-331", gameType:"field8", name:"3-3-1", en:"Three-Three-One",
    desc:"八人制最均衡的结构：三中卫保宽度与深度，三中场连接前后，单前锋压制对方防线。西班牙 alevín 组与英格兰青训都以此为教学首选。",
    roles:[
      { num:"1", label:"门将", desc:"出球第一发起人，充当 +1 人数。" },
      { num:"2/3/4", label:"三中卫", desc:"居中者拖后，两侧拉开宽度，持球推进。" },
      { num:"6/8/10", label:"三中场", desc:"6 号殿后保护，8 号盒-to-盒，10 号前插组织。" },
      { num:"9", label:"单前锋", desc:"顶住中卫做支点，反跑身后。" },
    ],
    pros:["三角形传球网络遍布全场","三条线人数均衡，攻守转换顺","天然教会球员“线”的概念"],
    cons:["两肋是唯一弱点，需边中卫补位","单前锋孤军时需要中场成组插上","对中场三人纪律性要求高"],
    use:"建队首选与长期主阵型；教学比赛默认阵型。",
    refs:["rfef-8","fa-dna"],
    players:[
      {id:1,num:1,team:"gk",x:6,y:50,label:"GK"},
      {id:2,num:2,team:"own",x:20,y:24,label:""},
      {id:3,num:3,team:"own",x:17,y:50,label:""},
      {id:4,num:4,team:"own",x:20,y:76,label:""},
      {id:6,num:6,team:"own",x:42,y:50,label:"6"},
      {id:8,num:8,team:"own",x:46,y:24,label:"8"},
      {id:10,num:10,team:"own",x:46,y:76,label:"10"},
      {id:9,num:9,team:"own",x:70,y:50,label:"9"},
    ],
  },
  {
    id:"s-322", gameType:"field8", name:"3-2-2", en:"Three-Two-Two",
    desc:"双前锋结构：中路终结点多，反击锋线成对，适合身体对抗强、直接打法为主的队伍。",
    roles:[
      { num:"2/3/4", label:"三中卫", desc:"出球三人组，居中者指挥。" },
      { num:"6/8", label:"双中场", desc:"一攻一守：6 号拖后，8 号前插。" },
      { num:"9/11", label:"双前锋", desc:"一高一快或一前一后，交叉跑位。" },
    ],
    pros:["锋线两人互相掩护，反击锐利","边路可放手交给中卫拉开","双中场有层次"],
    cons:["边路中场空缺，宽度全靠翼中卫","被压半场时中场只有两人","两翼身后易被打身后"],
    use:"以快攻与对抗为主的队伍；对阵控球型对手打反击。",
    refs:["rfef-8"],
    players:[
      {id:1,num:1,team:"gk",x:6,y:50,label:"GK"},
      {id:2,num:2,team:"own",x:20,y:26,label:""},
      {id:3,num:3,team:"own",x:17,y:50,label:""},
      {id:4,num:4,team:"own",x:20,y:74,label:""},
      {id:6,num:6,team:"own",x:44,y:38,label:"6"},
      {id:8,num:8,team:"own",x:44,y:62,label:"8"},
      {id:9,num:9,team:"own",x:70,y:38,label:"9"},
      {id:11,num:11,team:"own",x:70,y:62,label:"11"},
    ],
  },
  {
    id:"s-232", gameType:"field8", name:"2-3-2", en:"Two-Three-Two",
    desc:"攻击性最强的八人制结构：五名中前场球员形成横排控制，英格兰 9 人制前身、西班牙也常用于领先后的控制阶段。",
    roles:[
      { num:"2/3", label:"双后卫", desc:"宽度担当，一人上抢一人保护。" },
      { num:"7/8/10", label:"三中场", desc:"居中者掌控节奏，两翼内收配合。" },
      { num:"9/10", label:"双前锋", desc:"顶住防线，为中场前插让出空间。" },
    ],
    pros:["中场人数最多，控制力强","进攻端五人联动套路丰富","落后追分的高效选择"],
    cons:["只有两名后卫，防守宽度告急","边路身前大片空当","被反击时非常脆弱"],
    use:"领先控制节奏或落后强攻；队员技术较好时。",
    refs:["rfef-8"],
    players:[
      {id:1,num:1,team:"gk",x:6,y:50,label:"GK"},
      {id:2,num:2,team:"own",x:22,y:34,label:""},
      {id:3,num:3,team:"own",x:22,y:66,label:""},
      {id:7,num:7,team:"own",x:46,y:20,label:"7"},
      {id:8,num:8,team:"own",x:42,y:50,label:"8"},
      {id:10,num:10,team:"own",x:46,y:80,label:"10"},
      {id:9,num:9,team:"own",x:70,y:38,label:"9"},
      {id:11,num:11,team:"own",x:70,y:62,label:"11"},
    ],
  },
  {
    id:"s-313", gameType:"field8", name:"3-1-3", en:"Three-One-Three",
    desc:"镜像三前锋：单后腰居中调度，三名攻击手顶上，最强控场与施压结构，酷似十一人制的 4-3-3 缩影。",
    roles:[
      { num:"2/3/4", label:"三中卫", desc:"三人组出球，后腰回接成菱形。" },
      { num:"6", label:"单后腰", desc:"全场节拍器：接应、转身、转移。" },
      { num:"7/9/11", label:"三前锋", desc:"占住宽与深，压迫时分别逼三人。" },
    ],
    pros:["高位压迫时结构天然对位","三前锋拉满宽度与纵深","培养位置足球的最佳模板"],
    cons:["单后腰被冻结则全场瘫痪","三前锋回防少，防守 7 人变 5 人","对 6 号要求极高"],
    use:"控球流队伍；对阵弱旅演练压迫。",
    refs:["laliga-pos","rfef-8"],
    players:[
      {id:1,num:1,team:"gk",x:6,y:50,label:"GK"},
      {id:2,num:2,team:"own",x:20,y:26,label:""},
      {id:3,num:3,team:"own",x:17,y:50,label:""},
      {id:4,num:4,team:"own",x:20,y:74,label:""},
      {id:6,num:6,team:"own",x:40,y:50,label:"6"},
      {id:7,num:7,team:"own",x:66,y:20,label:"7"},
      {id:9,num:9,team:"own",x:68,y:50,label:"9"},
      {id:11,num:11,team:"own",x:66,y:80,label:"11"},
    ],
  },
  {
    id:"s-421", gameType:"field8", name:"4-2-1", en:"Four-Two-One",
    desc:"四后卫稳健结构：两条人墙保中路，双中场清扫，适合防守反击和年轻队伍建立防守安全感。",
    roles:[
      { num:"2/3/4/5", label:"四后卫", desc:"边后卫上前要果断，中卫互补位。" },
      { num:"6/8", label:"双中场", desc:"防线身前的双闸：拦截后第一时间向前。" },
      { num:"9", label:"单前锋", desc:"反击支点，回接做球。" },
    ],
    pros:["防守厚度最高，失球少","结构简单，年轻队伍有安全感","反击通道明确"],
    cons:["进攻人数少，推进依赖边后卫","中场创造力不足时易被围攻","单前锋需要极强背身能力"],
    use:"防守反击打法；保护年轻队伍建立信心。",
    refs:["fa-dna"],
    players:[
      {id:1,num:1,team:"gk",x:6,y:50,label:"GK"},
      {id:2,num:2,team:"own",x:22,y:16,label:""},
      {id:4,num:4,team:"own",x:19,y:39,label:""},
      {id:5,num:5,team:"own",x:19,y:61,label:""},
      {id:3,num:3,team:"own",x:22,y:84,label:""},
      {id:6,num:6,team:"own",x:44,y:38,label:"6"},
      {id:8,num:8,team:"own",x:44,y:62,label:"8"},
      {id:9,num:9,team:"own",x:70,y:50,label:"9"},
    ],
  },
  {
    id:"s-241", gameType:"field8", name:"2-4-1", en:"Two-Four-One",
    desc:"中场菱形控制：四名中场形成菱形（1 后腰 + 2 内收边路 + 1 前腰），最大化学传递网络。",
    roles:[
      { num:"2/3", label:"双后卫", desc:"边后卫随时外扩补宽度。" },
      { num:"4/8/7/10", label:"菱形四中场", desc:"4 号拖后、7/10 边路内收、10 号前腰。" },
      { num:"9", label:"单前锋", desc:"牵制中卫，为前腰腾出十号位空间。" },
    ],
    pros:["传球网络最密、控球率天然高","菱形教会球员不同角度接应","中场反抢人数多"],
    cons:["边路防守完全依赖边后卫冲刺","菱形横向覆盖窄","对球员跑位默契要求高"],
    use:"传控风格成型后的进阶阵型。",
    refs:["laliga-pos"],
    players:[
      {id:1,num:1,team:"gk",x:6,y:50,label:"GK"},
      {id:2,num:2,team:"own",x:22,y:34,label:""},
      {id:3,num:3,team:"own",x:22,y:66,label:""},
      {id:4,num:4,team:"own",x:40,y:50,label:"4"},
      {id:7,num:7,team:"own",x:52,y:18,label:"7"},
      {id:10,num:10,team:"own",x:52,y:82,label:"10"},
      {id:8,num:8,team:"own",x:60,y:50,label:"8"},
      {id:9,num:9,team:"own",x:74,y:50,label:"9"},
    ],
  },
];

/* ============================================================
   战术套路库
   ============================================================ */
const FUTSAL_ATTACK = [
  {
    id:"fa-rot", gameType:"futsal", phase:"atk", formation:"f-40", styles:["possession"],
    title:"4-0 轮转 · 横传拉扯二打一", difficulty:3,
    summary:"一线站位横向传导，把防守整体“调”起来，在轮转错位瞬间打穿边路。",
    refs:["fifa-manual","laliga-pos"],
    keyPoints:[
      "横传不是倒脚：每一次转移都要让防守整体移动，谁动谁露缝",
      "轮转三原则：有人上、有人补、有人拉——永远保持一线四点",
      "转移最多两脚完成，第三脚必须改变进攻区域",
      "接球人先观察（Scanning）再触球，眼睛比脚快",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:8,y:50},{id:2,num:2,team:"own",x:24,y:50},{id:3,num:3,team:"own",x:40,y:24},
      {id:4,num:4,team:"own",x:40,y:76},{id:5,num:5,team:"own",x:58,y:50},
      {id:"b",team:"ball",x:24,y:50},
      {id:"o1",num:6,team:"opp",x:48,y:40},{id:"o2",num:7,team:"opp",x:48,y:62},{id:"o3",num:8,team:"opp",x:60,y:50},
      {id:"og",num:1,team:"oppgk",x:92,y:50},
    ],
    steps:[
      { note:"一线横传：2 号与 3 号横向倒脚，吸引防守整体向有球侧移动。",
        moves:[{id:2,x:34,y:42,type:"run"},{id:3,x:44,y:28,type:"run"},{id:"b",x:44,y:28,type:"pass"}] },
      { note:"3 号回敲 2 号，同时 5 号下拉到深位接应——防守人开始犹豫跟谁。",
        moves:[{id:3,x:50,y:22,type:"run"},{id:5,x:62,y:64,type:"run"},{id:"b",x:34,y:42,type:"pass"}] },
      { note:"2 号两脚内转移弱侧 4 号：防守横移不到，右侧出现 2v1。",
        moves:[{id:4,x:46,y:70,type:"run"},{id:"b",x:46,y:70,type:"pass"},{id:2,x:40,y:46,type:"run"}] },
      { note:"4 号带球内收吸引对方 7 号上抢，为 5 号让出中路通道。",
        moves:[{id:4,x:56,y:62,type:"carry"},{id:"b",x:56,y:62,type:"carry"},{id:"o2",x:52,y:66,type:"run"}] },
      { note:"4 号直塞 5 号反跑空当——打穿第一道防线，形成单刀。",
        moves:[{id:5,x:74,y:52,type:"run"},{id:"b",x:74,y:52,type:"pass"}] },
      { note:"5 号面对出击的门将推远角，终结。",
        moves:[{id:5,x:82,y:49,type:"run"},{id:"b",x:90,y:44,type:"shot"}] },
    ],
  },
  {
    id:"fa-pivot", gameType:"futsal", phase:"atk", formation:"f-121", styles:["possession","pivot"],
    title:"支点回做 · 后排插上射门", difficulty:2,
    summary:"Pivo 背身要位回做，Fixo 从后排突然插上完成远射——五人制最实用的中路终结配合。",
    refs:["fifa-manual","fa-cap"],
    keyPoints:[
      "Pivo 要位：张开手臂隔开防守人，掌心向队友示意传球线路（Deception）",
      "回做力度：脚弓推地滚球，力度刚好让插上人不用停球",
      "插上时机：Pivo 触球瞬间启动，早一步越位、晚一步被封堵（Timing）",
      "射门第一选择：打远角贴地，门将扑近角重心已偏",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:8,y:50},{id:4,num:4,team:"own",x:24,y:50},{id:7,num:7,team:"own",x:46,y:22},
      {id:10,num:10,team:"own",x:46,y:78},{id:9,num:9,team:"own",x:68,y:50},
      {id:"b",team:"ball",x:24,y:50},
      {id:"o1",num:5,team:"opp",x:52,y:40},{id:"o2",num:6,team:"opp",x:52,y:62},{id:"o3",num:8,team:"opp",x:74,y:44},
      {id:"og",num:1,team:"oppgk",x:92,y:50},
    ],
    steps:[
      { note:"4 号（Fixo）横传右路 10 号，把防守吸引到有球侧。",
        moves:[{id:10,x:54,y:74,type:"run"},{id:"b",x:54,y:74,type:"pass"}] },
      { note:"10 号推进两步传给背身要位的 Pivo（9 号），防守收缩包夹支点。",
        moves:[{id:9,x:66,y:46,type:"run"},{id:"b",x:66,y:46,type:"pass"},{id:"o3",x:70,y:48,type:"run"}] },
      { note:"Pivo 触球瞬间，4 号从后排突然启动插上——防守全在盯球。",
        moves:[{id:4,x:48,y:34,type:"run"},{id:9,x:63,y:50,type:"run"}] },
      { note:"Pivo 脚弓回做，地滚球精准送到插上线路，4 号不做停球直接跟进。",
        moves:[{id:"b",x:48,y:34,type:"pass"},{id:4,x:56,y:36,type:"run"}] },
      { note:"4 号不停球直接远射——贴地斩打远角。",
        moves:[{id:"b",x:90,y:42,type:"shot"},{id:4,x:62,y:37,type:"run"}] },
    ],
  },
  {
    id:"fa-wall", gameType:"futsal", phase:"atk", formation:"f-121", styles:["possession","fast"],
    title:"二过一穿越 · Ala 斜插单刀", difficulty:2,
    summary:"边路（Ala）与 Pivo 的墙式二过一，用一次撞墙打穿边路第一道防线。",
    refs:["fifa-manual","fa-fp"],
    keyPoints:[
      "墙式配合的第一传要“喂到脚下”，让做墙人一触即回",
      "传球后立即加速——传跑是同一个动作（Movement）",
      "做墙人可以脚后跟或外脚背让球变线，增加欺骗性（Deception）",
      "U10 以下先在 2v1 里练会“传了就跑”，再加防守人",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:8,y:50},{id:4,num:4,team:"own",x:24,y:50},{id:7,num:7,team:"own",x:46,y:22},
      {id:10,num:10,team:"own",x:44,y:78},{id:9,num:9,team:"own",x:66,y:50},
      {id:"b",team:"ball",x:44,y:78},
      {id:"o1",num:5,team:"opp",x:50,y:68},{id:"o2",num:6,team:"opp",x:62,y:60},{id:"o3",num:8,team:"opp",x:56,y:44},
      {id:"og",num:1,team:"oppgk",x:92,y:50},
    ],
    steps:[
      { note:"10 号（Ala）带球内收，把对方 5 号引出来形成 1v1 局面。",
        moves:[{id:10,x:54,y:70,type:"carry"},{id:"b",x:54,y:70,type:"carry"},{id:"o1",x:52,y:66,type:"run"}] },
      { note:"敲给 Pivo 做墙——球一出脚立刻起步，不要回头看球。",
        moves:[{id:9,x:62,y:56,type:"run"},{id:"b",x:62,y:56,type:"pass"},{id:10,x:60,y:76,type:"run"}] },
      { note:"Pivo 顺势直塞，10 号从对方 5 号身后穿插而过。",
        moves:[{id:"b",x:72,y:70,type:"pass"},{id:10,x:70,y:72,type:"run"},{id:"o1",x:56,y:64,type:"run"}] },
      { note:"10 号单刀突入，观察门将站位后推远角。",
        moves:[{id:10,x:80,y:60,type:"run"},{id:"b",x:80,y:60,type:"carry"}] },
      { note:"冷静推射远角完成终结。",
        moves:[{id:"b",x:91,y:56,type:"shot"}] },
    ],
  },
  {
    id:"fa-gk", gameType:"futsal", phase:"atk", formation:"f-31", styles:["possession"],
    title:"门将发动 · 破全场紧逼", difficulty:3,
    summary:"面对人盯人全场紧逼：门将持球邀压，三后卫拉开接应，Pivo 身后一击。",
    refs:["fifa-laws","fifa-manual"],
    keyPoints:[
      "规则要点：门将出球后在己方半场不得再触球（除非球过半场或对方触球），门将只做第一次出球",
      "持球 4 秒规则：邀压时间最多 3 秒，出球前给队友完整喊话",
      "三后卫呈宽三角形站位，永远保持两个出球角度",
      "被逼急了就踢出边线——拿到界外球重新组织，好过在本方禁区丢球",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:8,y:50},{id:2,num:2,team:"own",x:20,y:24},{id:4,num:4,team:"own",x:16,y:50},
      {id:5,num:5,team:"own",x:20,y:76},{id:9,num:9,team:"own",x:62,y:50},
      {id:"b",team:"ball",x:8,y:50},
      {id:"o1",num:6,team:"opp",x:30,y:32},{id:"o2",num:7,team:"opp",x:28,y:54},{id:"o3",num:8,team:"opp",x:30,y:70},
      {id:"og",num:1,team:"oppgk",x:92,y:50},
    ],
    steps:[
      { note:"对方全场人盯人上抢。门将持球邀压 3 秒，三后卫向两翼拉开——把场子撑大。",
        moves:[{id:2,x:16,y:18,type:"run"},{id:5,x:16,y:82,type:"run"},{id:4,x:18,y:48,type:"run"}] },
      { note:"门将手抛球给位置最稳的 4 号（Fixo），不传被盯死的一侧。",
        moves:[{id:"b",x:18,y:48,type:"pass"},{id:"o2",x:24,y:50,type:"run"}] },
      { note:"4 号回敲 2 号（第三人有角度），吸引对方 6 号继续上抢。",
        moves:[{id:"b",x:16,y:18,type:"pass"},{id:"o1",x:22,y:22,type:"run"}] },
      { note:"2 号斜长传转移弱侧 5 号——压迫被一次性甩开，完成破逼抢。",
        moves:[{id:5,x:34,y:74,type:"run"},{id:"b",x:34,y:74,type:"pass"}] },
      { note:"5 号带球推进，Pivo 已在防线身后启动反跑。",
        moves:[{id:9,x:74,y:44,type:"run"},{id:5,x:44,y:70,type:"carry"},{id:"b",x:44,y:70,type:"carry"}] },
      { note:"5 号直塞 Pivo，单刀终结。",
        moves:[{id:"b",x:78,y:46,type:"pass"},{id:9,x:78,y:46,type:"run"}] },
    ],
  },
  {
    id:"fa-switch", gameType:"futsal", phase:"atk", formation:"f-121", styles:["fast","possession"],
    title:"换边转移 · 弱侧 Ala 内切终结", difficulty:2,
    summary:"强侧吸引包夹后一脚长传转移，弱侧 Ala 内切与 Pivo 墙式配合完成射门。",
    refs:["fifa-manual","fa-cap"],
    keyPoints:[
      "转移前必须先“卖”强侧：至少两次横向倒脚把防守拉过去",
      "弱侧 Ala 提前启动半拍——转移球到之前你已经在跑",
      "转移脚法：脚背平抽地滚球，2 秒内横穿全场",
      "弱侧接球第一动作向中路带（进入射门区域），不是沿着边线走",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:8,y:50},{id:4,num:4,team:"own",x:24,y:50},{id:7,num:7,team:"own",x:46,y:22},
      {id:10,num:10,team:"own",x:48,y:78},{id:9,num:9,team:"own",x:66,y:50},
      {id:"b",team:"ball",x:48,y:78},
      {id:"o1",num:5,team:"opp",x:54,y:70},{id:"o2",num:6,team:"opp",x:60,y:80},{id:"o3",num:8,team:"opp",x:40,y:40},
      {id:"og",num:1,team:"oppgk",x:92,y:50},
    ],
    steps:[
      { note:"右路 10 号持球，对方 5 号、6 号形成包夹——强侧已经“做局”。",
        moves:[{id:10,x:56,y:76,type:"carry"},{id:"b",x:56,y:76,type:"carry"},{id:"o2",x:56,y:82,type:"run"}] },
      { note:"10 号回敲 4 号（Fixo），包夹随球移动。",
        moves:[{id:"b",x:30,y:52,type:"pass"},{id:10,x:60,y:72,type:"run"}] },
      { note:"4 号一脚长传转移弱侧 7 号——防守重心还在右侧。",
        moves:[{id:7,x:50,y:28,type:"run"},{id:"b",x:50,y:28,type:"pass"}] },
      { note:"7 号不沿边线走，直接向中路禁区弧内切。",
        moves:[{id:7,x:60,y:38,type:"carry"},{id:"b",x:60,y:38,type:"carry"}] },
      { note:"与 Pivo 撞墙：7 号敲 9 号再前插，撕开肋部。",
        moves:[{id:9,x:68,y:48,type:"run"},{id:"b",x:68,y:48,type:"pass"},{id:7,x:70,y:40,type:"run"}] },
      { note:"9 号做墙回做，7 号近角爆射。",
        moves:[{id:"b",x:72,y:40,type:"pass"},{id:"b",x:90,y:36,type:"shot"}] },
    ],
  },
  {
    id:"fa-third", gameType:"futsal", phase:"atk", formation:"f-22", styles:["possession","pivot"],
    title:"第三人跑动 · 隐形一击", difficulty:3,
    summary:"传给 A、A 回给 B，真正的杀机是没人盯防的第三人 C——绕过防线的“隐形”跑位。",
    refs:["laliga-pos","fa-cap"],
    keyPoints:[
      "第三人跑动的本质：用两次简单传球让防守的注意力“过站”",
      "前两人都是诱饵：接球是为了让第三人的防守人看球",
      "第三人从防守人视线死角启动——永远从身后绕",
      "这是西班牙青训 Rondo 的实战化：三人在局部永远比防守多一人",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:8,y:50},{id:4,num:4,team:"own",x:24,y:32},{id:5,num:5,team:"own",x:24,y:68},
      {id:9,num:9,team:"own",x:52,y:34},{id:10,num:10,team:"own",x:56,y:66},
      {id:"b",team:"ball",x:24,y:68},
      {id:"o1",num:6,team:"opp",x:40,y:60},{id:"o2",num:7,team:"opp",x:46,y:36},{id:"o3",num:8,team:"opp",x:70,y:50},
      {id:"og",num:1,team:"oppgk",x:92,y:50},
    ],
    steps:[
      { note:"5 号传给背身接应的 10 号，10 号回做吸引对方 6 号上抢——第一层诱饵完成。",
        moves:[{id:10,x:52,y:62,type:"run"},{id:"b",x:52,y:62,type:"pass"}] },
      { note:"10 号一脚回敲 4 号，防守注意力全部转向中路。",
        moves:[{id:"b",x:30,y:36,type:"pass"},{id:10,x:56,y:64,type:"run"},{id:"o1",x:48,y:56,type:"run"}] },
      { note:"真正的杀机：9 号（第三人）从对方 7 号视线死角绕身后斜插。",
        moves:[{id:9,x:72,y:40,type:"run"},{id:"o2",x:44,y:40,type:"run"}] },
      { note:"4 号不停球直塞第三人——防守回头时球已到身后。",
        moves:[{id:"b",x:72,y:40,type:"pass"}] },
      { note:"9 号面对出击门将横敲中路空当——10 号包抄推空门。",
        moves:[{id:"b",x:80,y:56,type:"pass"},{id:10,x:80,y:60,type:"run"},{id:"b",x:90,y:58,type:"shot"}] },
    ],
  },
];

const FUTSAL_DEFENSE = [
  {
    id:"fd-press", gameType:"futsal", phase:"def", formation:"any", styles:["press"],
    title:"全场人盯人压迫", difficulty:3,
    summary:"从对方门将发球起 1v1 全场盯防，用压迫角度把球逼进“口袋”里完成围抢。",
    refs:["fifa-manual","uefa-tg"],
    keyPoints:[
      "压迫角度：曲线跑位，封内侧放外侧——把球往边线和底线赶",
      "每人必须“人球之间”站位：永远站在对手和对方球门之间",
      "就近两人形成口袋，第三人切断回传线路",
      "门将站位随整体前压上提，充当清道夫防身后",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:8,y:50},{id:2,num:2,team:"own",x:26,y:36},{id:4,num:4,team:"own",x:24,y:58},
      {id:7,num:7,team:"own",x:48,y:30},{id:9,num:9,team:"own",x:46,y:66},
      {id:"o1",num:1,team:"oppgk",x:6,y:50},
      {id:"o2",num:5,team:"opp",x:56,y:38},{id:"o3",num:6,team:"opp",x:52,y:66},{id:"o4",num:8,team:"opp",x:76,y:50},
      {id:"b",team:"ball",x:52,y:66},
    ],
    steps:[
      { note:"触发：对方门将把球交给 6 号——距离最近的 9 号 2 秒内曲线逼上，封内放外。",
        moves:[{id:9,x:44,y:62,type:"run"},{id:"b",x:52,y:66,type:"pass"},{id:"o3",x:52,y:66,type:"run"}] },
      { note:"第二人 4 号切断 6 号向中路回传的线路，口袋合拢。",
        moves:[{id:4,x:40,y:58,type:"run"},{id:9,x:46,y:70,type:"run"}] },
      { note:"7 号横移盯死另一侧接应点 5 号，让对方“看得见队友传不过去”。",
        moves:[{id:7,x:60,y:36,type:"run"},{id:2,x:36,y:44,type:"run"}] },
      { note:"压迫成功：6 号被迫横传边线方向，7 号预判断球——就地转入进攻。",
        moves:[{id:"b",x:62,y:34,type:"pass"},{id:7,x:60,y:32,type:"run"}] },
      { note:"断球瞬间整体前压：由守转攻只给对方 3 秒反应时间。",
        moves:[{id:"b",x:78,y:30,type:"carry"},{id:7,x:70,y:28,type:"carry"},{id:9,x:60,y:62,type:"run"}] },
    ],
  },
  {
    id:"fd-zone", gameType:"futsal", phase:"def", formation:"any", styles:["zone"],
    title:"2-2 区域联防", difficulty:1,
    summary:"两人一组看守四个“象限”，球到哪整体移到哪——用站位纪律代替个人对抗。",
    refs:["fifa-manual"],
    keyPoints:[
      "每人只对“自己区域里的人”负责，不追球出区域",
      "整体移动像一块地毯：一人动，四人动，间距保持 3-4 米",
      "球在边路时同侧二人收缩夹角，弱侧二人保护中路",
      "门将是指挥官：大声喊“右！收！压！”——区域防守靠嘴",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:8,y:50},{id:2,num:2,team:"own",x:30,y:28},{id:4,num:4,team:"own",x:30,y:72},
      {id:7,num:7,team:"own",x:52,y:28},{id:9,num:9,team:"own",x:52,y:72},
      {id:"o1",num:1,team:"oppgk",x:6,y:50},
      {id:"o2",num:5,team:"opp",x:60,y:30},{id:"o3",num:6,team:"opp",x:58,y:62},{id:"o4",num:8,team:"opp",x:76,y:50},
      {id:"b",team:"ball",x:58,y:62},
    ],
    steps:[
      { note:"球进入 9 号的右下区域：9 号上抢持球人，同侧的 7 号收缩保护角度。",
        moves:[{id:9,x:54,y:64,type:"run"},{id:7,x:50,y:34,type:"run"},{id:"o3",x:58,y:62,type:"run"}] },
      { note:"对面的 2 号、4 号整体左移半格——永远保持四点成方块，不散架。",
        moves:[{id:2,x:26,y:34,type:"run"},{id:4,x:26,y:66,type:"run"}] },
      { note:"6 号横传转移，整体像地毯一样横移：7 号接手压迫，9 号归位。",
        moves:[{id:"b",x:60,y:30,type:"pass"},{id:7,x:56,y:28,type:"run"},{id:9,x:50,y:66,type:"run"},{id:"o2",x:60,y:30,type:"run"}] },
      { note:"5 号（对方）被迫回传门将，全队上提压缩——把对手摁回半场。",
        moves:[{id:"b",x:10,y:44,type:"pass"},{id:2,x:38,y:30,type:"run"},{id:4,x:38,y:70,type:"run"},{id:7,x:62,y:32,type:"run"},{id:9,x:62,y:68,type:"run"}] },
    ],
  },
  {
    id:"fd-mix", gameType:"futsal", phase:"def", formation:"any", styles:["press","zone"],
    title:"混合防守 · 一压三保", difficulty:2,
    summary:"一人全场跟防持球人，三人落成菱形区域保护——盯人的凶 + 区域的稳。",
    refs:["fifa-manual","uefa-tg"],
    keyPoints:[
      "“压迫者”只追球不追人：谁持球追谁，队友自动补他的区域",
      "菱形保护点永远位于持球人与球门连线上",
      "压迫者体能消耗极大，准备 2-3 人轮换这个角色",
      "对方突破压迫者时，就近保护人上抢，压迫者回撤换位",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:8,y:50},{id:2,num:2,team:"own",x:28,y:50},{id:4,num:4,team:"own",x:42,y:26},
      {id:7,num:7,team:"own",x:42,y:74},{id:9,num:9,team:"own",x:60,y:50},
      {id:"o1",num:1,team:"oppgk",x:6,y:50},
      {id:"o2",num:5,team:"opp",x:58,y:34},{id:"o3",num:6,team:"opp",x:54,y:66},{id:"o4",num:8,team:"opp",x:78,y:50},
      {id:"b",team:"ball",x:6,y:50},
    ],
    steps:[
      { note:"对方门将发球：指定的压迫者 9 号全程跟随持球人，干扰每一脚出球。",
        moves:[{id:9,x:56,y:62,type:"run"},{id:"b",x:54,y:66,type:"pass"},{id:"o3",x:54,y:66,type:"run"}] },
      { note:"其余三人落成菱形：2 号殿后，4 号、7 号护住两肋——不参与上抢。",
        moves:[{id:2,x:26,y:52,type:"run"},{id:4,x:38,y:32,type:"run"},{id:7,x:38,y:68,type:"run"}] },
      { note:"9 号把持球人逼向边线，4 号横移准备断传向中路的线路。",
        moves:[{id:9,x:50,y:68,type:"run"},{id:4,x:44,y:44,type:"run"}] },
      { note:"被迫长传转移：压迫者 9 号立刻去追新持球人，菱形整体旋转——防守形状不变。",
        moves:[{id:"b",x:60,y:34,type:"pass"},{id:9,x:56,y:36,type:"run"},{id:4,x:34,y:56,type:"run"},{id:7,x:40,y:62,type:"run"}] },
    ],
  },
  {
    id:"fd-low", gameType:"futsal", phase:"def", formation:"any", styles:["block"],
    title:"低位 3-1 收缩 · 保护近门柱", difficulty:1,
    summary:"整体退守禁区弧顶，三人封堵中路打门角度，Pivo 退防充当第四人——领先时守住胜局的标准答案。",
    refs:["fifa-manual"],
    keyPoints:[
      "低位的两件事：封堵射门角度 + 保护近门柱横传点",
      "所有人 goal-side（人球之间），绝不从持球人身后绕",
      "解围方向：向边线踢、往高踢、往远踢——绝不在中路横传",
      "得球后别急着堆上去：3 秒观察，先保证球权再推进",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:6,y:50},{id:2,num:2,team:"own",x:20,y:30},{id:4,num:4,team:"own",x:16,y:50},
      {id:7,num:7,team:"own",x:20,y:70},{id:9,num:9,team:"own",x:30,y:50},
      {id:"o1",num:1,team:"oppgk",x:90,y:50},
      {id:"o2",num:5,team:"opp",x:56,y:36},{id:"o3",num:6,team:"opp",x:52,y:64},{id:"o4",num:8,team:"opp",x:72,y:50},
      {id:"b",team:"ball",x:52,y:64},
    ],
    steps:[
      { note:"对手控球推进，全队退守：三人封锁中路打门角度，9 号回撤成第四人。",
        moves:[{id:9,x:26,y:50,type:"run"},{id:2,x:18,y:34,type:"run"},{id:7,x:18,y:66,type:"run"}] },
      { note:"6 号试图横传找 8 号：9 号横移封堵这条传球线。",
        moves:[{id:9,x:30,y:44,type:"run"},{id:"o3",x:52,y:64,type:"run"}] },
      { note:"8 号被迫转移到弱侧，4 号外扩顶出去干扰，其余人不动——低位的纪律就是不冒进。",
        moves:[{id:"b",x:56,y:36,type:"pass"},{id:4,x:24,y:46,type:"run"},{id:"o2",x:56,y:36,type:"run"}] },
      { note:"对方勉强远射，门将近角封死将球压住——低位防守胜利。",
        moves:[{id:"b",x:14,y:48,type:"shot"},{id:1,x:8,y:50,type:"run"}] },
    ],
  },
  {
    id:"fd-cp", gameType:"futsal", phase:"def", formation:"any", styles:["press","fast"],
    title:"丢球反抢 · 5 秒窗口", difficulty:2,
    summary:"丢球瞬间是全场最脆弱也最强的时刻：就近者立即反抢，其他人 5 秒内切断所有向前线路。",
    refs:["uefa-tg","laliga-pos"],
    keyPoints:[
      "反抢窗口只有 5 秒：对方刚拿球、抬头找人的瞬间最怕逼抢",
      "分工：最近的人上抢，第二人封回传，其他人切向前线路",
      "反抢投入的人数不超过三人——抢不回立刻退回 2-2，绝不拖泥带水",
      "五人制场地小，反抢成功率远高于十一人制，这是五人制的灵魂",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:8,y:50},{id:2,num:2,team:"own",x:26,y:40},{id:4,num:4,team:"own",x:22,y:64},
      {id:7,num:7,team:"own",x:52,y:34},{id:9,num:9,team:"own",x:48,y:60},
      {id:"o1",num:1,team:"oppgk",x:6,y:50},
      {id:"o2",num:5,team:"opp",x:60,y:50},{id:"o3",num:6,team:"opp",x:74,y:36},{id:"o4",num:8,team:"opp",x:70,y:68},
      {id:"b",team:"ball",x:74,y:36},
    ],
    steps:[
      { note:"我方丢球！对方 6 号刚拿球：最近的 9 号 2 秒内扑上——不给抬头观察的时间。",
        moves:[{id:9,x:68,y:40,type:"run"}] },
      { note:"7 号切断 6 号的出球线路，4 号、2 号守住中路——口袋在对方半场合拢。",
        moves:[{id:7,x:66,y:32,type:"run"},{id:4,x:48,y:54,type:"run"},{id:2,x:38,y:46,type:"run"}] },
      { note:"6 号仓促转移边路，7 号早已预判线路启动。",
        moves:[{id:"b",x:70,y:28,type:"pass"},{id:7,x:68,y:30,type:"run"}] },
      { note:"7 号断球成功——丢球 4 秒重新拿回球权，对方防线还散着。",
        moves:[{id:"b",x:72,y:24,type:"carry"},{id:7,x:70,y:26,type:"carry"}] },
      { note:"7 号直塞前插的 9 号：反抢直接转换成单刀。",
        moves:[{id:"b",x:82,y:34,type:"pass"},{id:9,x:78,y:38,type:"run"}] },
    ],
  },
];

const FIELD8_ATTACK = [
  {
    id:"sa-over", gameType:"field8", phase:"atk", formation:"s-331", styles:["wing"],
    title:"边路超载 · 倒三角终结", difficulty:2,
    summary:"左路三人成组制造 3v2，下底后倒三角回传，后排中场插上推射——现代足球最高效的终结方式。",
    refs:["fa-dna","rfef-8"],
    keyPoints:[
      "超载三人组：边后卫 + 边中场 + 前腰/前锋斜插，局部永远多一人",
      "倒三角（Cutback）传中点：小禁区角附近，落地快、包抄点多",
      "后排插上时机：传中起脚瞬间启动，目标点是小禁区角（Timing）",
      "包抄三人就位：近门柱、小禁区角、远门柱各一人",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:6,y:50},{id:2,num:2,team:"own",x:20,y:24},{id:3,num:3,team:"own",x:17,y:50},
      {id:4,num:4,team:"own",x:20,y:76},{id:8,num:8,team:"own",x:44,y:24},{id:6,num:6,team:"own",x:40,y:50},
      {id:10,num:10,team:"own",x:44,y:76},{id:9,num:9,team:"own",x:66,y:50},
      {id:"b",team:"ball",x:17,y:50},
      {id:"o1",num:5,team:"opp",x:48,y:20},{id:"o2",num:7,team:"opp",x:44,y:50},{id:"o3",num:11,team:"opp",x:48,y:72},
      {id:"og",num:1,team:"oppgk",x:93,y:50},
    ],
    steps:[
      { note:"3 号（左中卫）带球推进引出对方 5 号，8 号（左中场）横向内收接应。",
        moves:[{id:3,x:26,y:38,type:"carry"},{id:"b",x:26,y:38,type:"carry"},{id:8,x:38,y:30,type:"run"}] },
      { note:"3 号传 8 号后套边超载——左路瞬间 3 打 2。",
        moves:[{id:"b",x:38,y:30,type:"pass"},{id:3,x:40,y:12,type:"run"},{id:"o1",x:42,y:26,type:"run"}] },
      { note:"8 号脚后跟/横敲套边的 3 号，自己转身切禁区。",
        moves:[{id:"b",x:40,y:12,type:"pass"},{id:8,x:52,y:26,type:"run"}] },
      { note:"3 号下底到底线，观察包抄点后倒三角回传——传小禁区角，不传门前高空球。",
        moves:[{id:3,x:72,y:14,type:"carry"},{id:"b",x:72,y:14,type:"carry"},{id:9,x:66,y:44,type:"run"}] },
      { note:"6 号从中路后排插上到位，不停球直接推射。",
        moves:[{id:"b",x:62,y:34,type:"pass"},{id:6,x:56,y:44,type:"run"},{id:"b",x:86,y:44,type:"shot"}] },
    ],
  },
  {
    id:"sa-overlap", gameType:"field8", phase:"atk", formation:"s-322", styles:["wing"],
    title:"边锋内切 · 后卫套边传中", difficulty:2,
    summary:"边锋内切带走对方边后卫，右后卫从身后套边接直塞下底传中，双前锋三点包抄。",
    refs:["rfef-8","fa-cap"],
    keyPoints:[
      "内切 + 套边是固定组合：边锋向内，身后空间留给套边后卫",
      "套边启动时机：边锋触球瞬间启动，传直塞才有提前量",
      "传中目标：近门柱 6 码区地滚球/半高球，不轻易起高球",
      "包抄层次：近门柱一人、点球点一人、后点一人，相互拉开间距",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:6,y:50},{id:2,num:2,team:"own",x:20,y:26},{id:3,num:3,team:"own",x:17,y:50},
      {id:4,num:4,team:"own",x:20,y:74},{id:6,num:6,team:"own",x:42,y:38},{id:8,num:8,team:"own",x:42,y:62},
      {id:11,num:11,team:"own",x:56,y:76},{id:9,num:9,team:"own",x:68,y:44},
      {id:"b",team:"ball",x:42,y:62},
      {id:"o1",num:7,team:"opp",x:50,y:66},{id:"o2",num:5,team:"opp",x:46,y:46},{id:"o3",num:10,team:"opp",x:62,y:50},
      {id:"og",num:1,team:"oppgk",x:93,y:50},
    ],
    steps:[
      { note:"11 号（右边锋）接 8 号传球后内切，把对方 7 号带进中路。",
        moves:[{id:11,x:56,y:64,type:"carry"},{id:"b",x:56,y:64,type:"pass"},{id:"o1",x:52,y:60,type:"run"}] },
      { note:"2 号（右后卫）沿边线套边——11 号触球瞬间启动，不早不晚。",
        moves:[{id:2,x:52,y:86,type:"run"},{id:11,x:60,y:60,type:"run"}] },
      { note:"11 号一脚直塞给套边的 2 号，穿过整条防线。",
        moves:[{id:"b",x:62,y:84,type:"pass"},{id:2,x:62,y:86,type:"run"},{id:"o1",x:58,y:68,type:"run"}] },
      { note:"2 号下底观察：9 号冲近门柱，8 号到点球点，11 号包后点。",
        moves:[{id:2,x:78,y:84,type:"carry"},{id:"b",x:78,y:84,type:"carry"},{id:9,x:78,y:48,type:"run"},{id:8,x:62,y:52,type:"run"}] },
      { note:"地滚球扫向近门柱，9 号抢在门将前铲射入网。",
        moves:[{id:"b",x:84,y:46,type:"pass"},{id:"b",x:91,y:47,type:"shot"},{id:9,x:84,y:46,type:"run"}] },
    ],
  },
  {
    id:"sa-build", gameType:"field8", phase:"atk", formation:"s-331", styles:["central","possession"],
    title:"三线推进 · 穿线传球", difficulty:3,
    summary:"门将-三中卫-后腰-前场三角形推进，用“穿线传球”直接打穿对方第一道压迫——西班牙位置足球的八人制教材。",
    refs:["laliga-pos","rfef-8"],
    keyPoints:[
      "三角形网络：持球人永远要有两个接应角度，像三角形一样滚动前进",
      "穿线传球（entre líneas）：一脚传球同时穿过两名防守人，价值最高",
      "引压再打：先横传引对方上抢，身后才是传球通道（Deception）",
      "推进慢不可怕，回传也不丢人——丢球权才是罪过",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:6,y:50},{id:2,num:2,team:"own",x:20,y:24},{id:3,num:3,team:"own",x:17,y:50},
      {id:4,num:4,team:"own",x:20,y:76},{id:6,num:6,team:"own",x:40,y:50},{id:8,num:8,team:"own",x:44,y:24},
      {id:10,num:10,team:"own",x:44,y:76},{id:9,num:9,team:"own",x:68,y:50},
      {id:"b",team:"ball",x:6,y:50},
      {id:"o1",num:7,team:"opp",x:40,y:26},{id:"o2",num:5,team:"opp",x:38,y:50},{id:"o3",num:11,team:"opp",x:40,y:74},
      {id:"og",num:1,team:"oppgk",x:93,y:50},
    ],
    steps:[
      { note:"门将开球给 3 号，2 号横向拉开——第一线出球三人组成型。",
        moves:[{id:"b",x:17,y:50,type:"pass"},{id:2,x:22,y:16,type:"run"}] },
      { note:"3 号横传 2 号，引动对方 7 号上抢，中路被拉开一条缝。",
        moves:[{id:"b",x:22,y:16,type:"pass"},{id:"o1",x:30,y:20,type:"run"}] },
      { note:"2 号直接穿线传球：一脚穿透上抢人与中路防守人，找到 6 号。",
        moves:[{id:"b",x:40,y:50,type:"pass"},{id:6,x:40,y:50,type:"run"},{id:"o2",x:44,y:48,type:"run"}] },
      { note:"6 号转身（扫一眼后再触球），8 号已从肋部前插接应。",
        moves:[{id:8,x:56,y:30,type:"run"},{id:6,x:48,y:50,type:"carry"},{id:"b",x:48,y:50,type:"carry"}] },
      { note:"6 号直塞 8 号，8 号下底传中——9 号包抄近点。",
        moves:[{id:"b",x:56,y:30,type:"pass"},{id:8,x:70,y:24,type:"run"},{id:"b",x:70,y:24,type:"carry"}] },
      { note:"横传中路，9 号推射空门。",
        moves:[{id:"b",x:82,y:46,type:"pass"},{id:"b",x:90,y:47,type:"shot"},{id:9,x:82,y:48,type:"run"}] },
    ],
  },
  {
    id:"sa-third", gameType:"field8", phase:"atk", formation:"s-331", styles:["central"],
    title:"第三人跑动 · 肋部直塞", difficulty:3,
    summary:"前锋回做当诱饵，真正的杀机是肋部前插的中场——用第三人跑动打穿中路防线。",
    refs:["fa-cap","laliga-pos"],
    keyPoints:[
      "回做前锋是诱饵：他的触球让对方的 3 号（盯人中卫）看球",
      "第三人（8 号）从中卫的视线盲区（肋部）斜插",
      "直塞提前量：往人跑的方向传，不往人现在的位置传",
      "注意越位：8 号启动时机在传球出脚的瞬间（Timing）",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:6,y:50},{id:2,num:2,team:"own",x:20,y:24},{id:3,num:3,team:"own",x:17,y:50},
      {id:4,num:4,team:"own",x:20,y:76},{id:6,num:6,team:"own",x:38,y:50},{id:8,num:8,team:"own",x:44,y:24},
      {id:10,num:10,team:"own",x:44,y:76},{id:9,num:9,team:"own",x:64,y:50},
      {id:"b",team:"ball",x:38,y:50},
      {id:"o1",num:7,team:"opp",x:50,y:24},{id:"o2",num:5,team:"opp",x:52,y:48},{id:"o3",num:11,team:"opp",x:50,y:72},
      {id:"og",num:1,team:"oppgk",x:93,y:50},
    ],
    steps:[
      { note:"6 号直传 9 号（回做点），9 号背身接球，对方 5 号上前逼抢。",
        moves:[{id:"b",x:64,y:50,type:"pass"},{id:"o2",x:58,y:50,type:"run"}] },
      { note:"9 号一脚回敲 6 号——防守的注意力全部被这次回传吸住。",
        moves:[{id:"b",x:38,y:50,type:"pass"},{id:9,x:60,y:48,type:"run"}] },
      { note:"真正的杀机：8 号从对方 5 号的视线盲区沿肋部斜插——这就是第三人。",
        moves:[{id:8,x:66,y:30,type:"run"},{id:"o1",x:54,y:28,type:"run"}] },
      { note:"6 号不停球直塞肋部——传的是 8 号将要到达的空当。",
        moves:[{id:"b",x:70,y:30,type:"pass"},{id:8,x:72,y:32,type:"run"}] },
      { note:"8 号形成半单刀，观察后横传后点，10 号包抄推射。",
        moves:[{id:"b",x:84,y:58,type:"pass"},{id:10,x:82,y:60,type:"run"},{id:"b",x:90,y:56,type:"shot"}] },
    ],
  },
  {
    id:"sa-counter", gameType:"field8", phase:"atk", formation:"s-322", styles:["counter","fast"],
    title:"快速反击 · 3v2 六秒战", difficulty:2,
    summary:"断球后 6 秒内的黄金反击窗口：第一时间直塞，双前锋斜线冲刺，第三人居中跟进。",
    refs:["uefa-tg","fa-dna"],
    keyPoints:[
      "6 秒原则：断球后 6 秒内完成射门，否则对手落位",
      "第一时间出球：断球人不粘球，抬头第一眼就找前锋",
      "跑位形状：双前锋一前一后斜线拉开，让 2 名防守人不能同时顾两人",
      "跟进第三人：断球人自己随后插上，做二点保护",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:6,y:50},{id:2,num:2,team:"own",x:24,y:30},{id:4,num:4,team:"own",x:24,y:70},
      {id:3,num:3,team:"own",x:17,y:50},{id:6,num:6,team:"own",x:40,y:50},
      {id:8,num:8,team:"own",x:44,y:62},{id:9,num:9,team:"own",x:56,y:36},{id:11,num:11,team:"own",x:58,y:64},
      {id:"b",team:"ball",x:40,y:50},
      {id:"o1",num:4,team:"opp",x:56,y:50},{id:"o2",num:5,team:"opp",x:66,y:50},
      {id:"og",num:1,team:"oppgk",x:93,y:50},
    ],
    steps:[
      { note:"6 号中场断球！第一时间抬头——两个前锋已经在跑。",
        moves:[{id:6,x:42,y:48,type:"run"}] },
      { note:"9 号斜线冲左肋、11 号冲右肋——把两名防守人向两侧拉开。",
        moves:[{id:9,x:64,y:26,type:"run"},{id:11,x:64,y:72,type:"run"},{id:"o1",x:60,y:44,type:"run"},{id:"o2",x:62,y:56,type:"run"}] },
      { note:"6 号直塞冲得最快的 9 号——穿过两名防守人中间的缝。",
        moves:[{id:"b",x:68,y:24,type:"pass"},{id:9,x:70,y:22,type:"run"}] },
      { note:"9 号带球突入禁区，吸引出击的门将。",
        moves:[{id:9,x:80,y:28,type:"carry"},{id:"b",x:80,y:28,type:"carry"},{id:"og",x:90,y:44,type:"run"}] },
      { note:"横敲中路空门，11 号跟进推射——断球到射门仅用 6 秒。",
        moves:[{id:"b",x:86,y:52,type:"pass"},{id:11,x:84,y:56,type:"run"},{id:"b",x:92,y:52,type:"shot"}] },
    ],
  },
  {
    id:"sa-gkplus", gameType:"field8", phase:"atk", formation:"s-331", styles:["possession","central"],
    title:"门将 +1 · 破高压构建", difficulty:3,
    summary:"对方全员压上时，门将是天然的人数优势（+1）：三中卫拉满宽度，门将成为自由人完成转移。",
    refs:["laliga-pos","rfef-8"],
    keyPoints:[
      "被压时第一原则：把宽度拉到极限——三中卫分别贴边线",
      "门将是 +1：对方 7 人压 7 人，多出来的门将永远自由",
      "两脚内出球：门将拿球不超过 3 秒，转移或推进绝不回传横传失误",
      "破压成功后第一时间向前：高压的身后是全世界最大的空间",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:6,y:50},{id:2,num:2,team:"own",x:22,y:14},{id:3,num:3,team:"own",x:19,y:50},
      {id:4,num:4,team:"own",x:22,y:86},{id:6,num:6,team:"own",x:38,y:50},{id:8,num:8,team:"own",x:50,y:30},
      {id:10,num:10,team:"own",x:50,y:70},{id:9,num:9,team:"own",x:62,y:50},
      {id:"b",team:"ball",x:6,y:50},
      {id:"o1",num:7,team:"opp",x:36,y:18},{id:"o2",num:5,team:"opp",x:34,y:50},{id:"o3",num:8,team:"opp",x:36,y:82},
      {id:"o4",num:10,team:"opp",x:50,y:34},{id:"o5",num:11,team:"opp",x:56,y:62},{id:"og",num:1,team:"oppgk",x:93,y:50},
    ],
    steps:[
      { note:"对方 5 人压过半场。三中卫贴边线拉满宽度，6 号回撤接应，8 号、10 号压住对方两肋。",
        moves:[{id:2,x:18,y:8,type:"run"},{id:4,x:18,y:85,type:"run"},{id:6,x:32,y:50,type:"run"}] },
      { note:"门将持球邀压，等对方 5 号上抢——这就是“钓”。",
        moves:[{id:"o2",x:24,y:50,type:"run"}] },
      { note:"门将横传给已拉开的 2 号——越过上抢人的头顶。",
        moves:[{id:"b",x:18,y:8,type:"pass"},{id:1,x:10,y:44,type:"run"}] },
      { note:"2 号发现中路大空当：6 号身前无人，直传 6 号。",
        moves:[{id:"b",x:36,y:50,type:"pass"},{id:6,x:42,y:50,type:"run"}] },
      { note:"6 号转身推进，9 号前插带走中卫，8 号从肋部接应到位——破压完成，进入进攻三区。",
        moves:[{id:6,x:56,y:50,type:"carry"},{id:"b",x:56,y:50,type:"carry"},{id:9,x:72,y:44,type:"run"},{id:8,x:60,y:32,type:"run"}] },
    ],
  },
];

const FIELD8_DEFENSE = [
  {
    id:"sd-hp", gameType:"field8", phase:"def", formation:"s-331", styles:["press"],
    title:"高位逼抢 · 引向边路围剿", difficulty:3,
    summary:"以前锋逼抢为触发器，全队像一块地毯整体移动：封中路、放边路，在边线完成围剿。",
    refs:["uefa-tg","fa-dna"],
    keyPoints:[
      "逼抢触发器（Trigger）：对方后卫接门将回传球、停大、背对进攻方向——任一出现就全员启动",
      "曲线跑封内放外：逼球人跑弧线，把持球人往边线“赶”",
      "整体移动像一块地毯：前锋压、中场跟、后卫线整体前压 5 米",
      "边线围剿：边后卫上抢 + 边中场内收关门，两分钟内解决战斗",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:14,y:50},{id:2,num:2,team:"own",x:28,y:28},{id:3,num:3,team:"own",x:26,y:50},
      {id:4,num:4,team:"own",x:28,y:72},{id:8,num:8,team:"own",x:48,y:30},{id:6,num:6,team:"own",x:46,y:50},
      {id:10,num:10,team:"own",x:48,y:70},{id:9,num:9,team:"own",x:66,y:50},
      {id:"o1",num:1,team:"oppgk",x:6,y:50},
      {id:"o2",num:7,team:"opp",x:20,y:20},{id:"o3",num:5,team:"opp",x:18,y:50},{id:"o4",num:11,team:"opp",x:20,y:80},
      {id:"b",team:"ball",x:20,y:80},
    ],
    steps:[
      { note:"触发器出现：对方门将回传 11 号。9 号立刻启动曲线跑——封中路、放边路。",
        moves:[{id:"b",x:20,y:80,type:"pass"},{id:9,x:28,y:70,type:"run"}] },
      { note:"全队像地毯一样前压：中场三人各跟一人，后卫线整体上提 5 米。",
        moves:[{id:6,x:52,y:44,type:"run"},{id:10,x:54,y:64,type:"run"},{id:2,x:34,y:22,type:"run"},{id:4,x:34,y:66,type:"run"},{id:3,x:32,y:48,type:"run"},{id:1,x:22,y:50,type:"run"}] },
      { note:"11 号被逼向边线，10 号内收准备关门，边后卫 4 号上抢。",
        moves:[{id:"o4",x:14,y:86,type:"carry"},{id:"b",x:14,y:86,type:"carry"},{id:10,x:40,y:78,type:"run"},{id:4,x:36,y:80,type:"run"}] },
      { note:"口袋合拢：持球人传球线路全被封死，仓促大脚被 3 号顶回。",
        moves:[{id:"b",x:34,y:64,type:"pass"},{id:3,x:38,y:58,type:"run"}] },
      { note:"二点球拿下就地反击——对方刚压上，身后全是空当。",
        moves:[{id:"b",x:56,y:44,type:"pass"},{id:6,x:56,y:46,type:"run"},{id:9,x:66,y:36,type:"run"}] },
    ],
  },
  {
    id:"sd-mid", gameType:"field8", phase:"def", formation:"s-331", styles:["mid","block"],
    title:"中场拦截 · 紧凑 mid-block", difficulty:1,
    summary:"中线后 5-10 米落位，三线间距 8-10 米：不冒进上抢，用紧凑的阵型把中路挤成“堵墙”。",
    refs:["fa-dna","uefa-tg"],
    keyPoints:[
      "三线间距 8-10 米：线与线之间站不下一个进攻人，就没有渗透空间",
      "第一抢由中场发起，后卫线只封堵不上抢——不冒进是纪律",
      "球到边路同侧压、中路收，弱侧边中场内收保护肋部",
      "对手横传回传是好事：时间在我这边，等他犯错",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:10,y:50},{id:2,num:2,team:"own",x:30,y:28},{id:3,num:3,team:"own",x:28,y:50},
      {id:4,num:4,team:"own",x:30,y:72},{id:8,num:8,team:"own",x:48,y:32},{id:6,num:6,team:"own",x:45,y:50},
      {id:10,num:10,team:"own",x:48,y:68},{id:9,num:9,team:"own",x:56,y:50},
      {id:"o1",num:1,team:"oppgk",x:6,y:50},
      {id:"o2",num:7,team:"opp",x:56,y:30},{id:"o3",num:5,team:"opp",x:54,y:50},{id:"o4",num:11,team:"opp",x:56,y:70},
      {id:"b",team:"ball",x:54,y:50},
    ],
    steps:[
      { note:"对方推进过中线：全队在中线后落位，三线间距 8-10 米，阵型像“三堵墙”。",
        moves:[{id:9,x:50,y:50,type:"run"}] },
      { note:"球进中路：6 号、8 号同时向持球人收缩夹角，9 号切断回做线路。",
        moves:[{id:"o3",x:46,y:50,type:"carry"},{id:"b",x:46,y:50,type:"carry"},{id:6,x:52,y:46,type:"run"},{id:8,x:56,y:36,type:"run"}] },
      { note:"对方只能横向转移：同侧的 10 号立刻接手压迫，其他人横移半格。",
        moves:[{id:"b",x:44,y:70,type:"pass"},{id:10,x:52,y:66,type:"run"},{id:6,x:46,y:52,type:"run"},{id:8,x:44,y:34,type:"run"}] },
      { note:"中卫 3 号指挥防线整体横移，始终把中路堵死——对方的渗透空间为零。",
        moves:[{id:2,x:36,y:24,type:"run"},{id:3,x:34,y:50,type:"run"},{id:4,x:36,y:74,type:"run"}] },
      { note:"对方回传门将，全队上提压缩——把压迫线重新推回中线。",
        moves:[{id:"b",x:12,y:46,type:"pass"},{id:9,x:60,y:50,type:"run"},{id:8,x:54,y:34,type:"run"},{id:10,x:56,y:66,type:"run"}] },
    ],
  },
  {
    id:"sd-low", gameType:"field8", phase:"def", formation:"s-421", styles:["low","block"],
    title:"低位区域 · 保护禁区", difficulty:1,
    summary:"整体退到禁区前沿，双中场护住弧顶，边后卫内收变五后卫：对手控球我守门。",
    refs:["fa-dna"],
    keyPoints:[
      "低位三任务：封射门角度、防传中落点、保护二点球",
      "边后卫内收：禁区内形成 5 人密集，但弧顶必须有人（双中场）",
      "第一延缓（Delay）：就近球员贴住持球人不抢，为队友退防赢时间",
      "解围纪律：向边线、向高、向远——中路绝不横传",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:6,y:50},{id:2,num:2,team:"own",x:18,y:20},{id:4,num:4,team:"own",x:15,y:40},
      {id:5,num:5,team:"own",x:15,y:60},{id:3,num:3,team:"own",x:18,y:80},{id:6,num:6,team:"own",x:30,y:38},
      {id:8,num:8,team:"own",x:30,y:62},{id:9,num:9,team:"own",x:44,y:50},
      {id:"o1",num:1,team:"oppgk",x:92,y:50},
      {id:"o2",num:7,team:"opp",x:56,y:24},{id:"o3",num:10,team:"opp",x:52,y:50},{id:"o4",num:11,team:"opp",x:56,y:76},
      {id:"b",team:"ball",x:52,y:50},
    ],
    steps:[
      { note:"全队退守：四后卫横排封禁区，双中场护弧顶，9 号退回第一延缓线。",
        moves:[{id:9,x:38,y:50,type:"run"},{id:6,x:26,y:40,type:"run"},{id:8,x:26,y:60,type:"run"}] },
      { note:"9 号贴住持球人只贴不抢（Delay），为他身后队友退防赢 3 秒。",
        moves:[{id:9,x:46,y:48,type:"run"},{id:"o3",x:46,y:50,type:"run"}] },
      { note:"对方转移边路：2 号外扩顶传中点，6 号横移补肋部空当。",
        moves:[{id:"b",x:56,y:24,type:"pass"},{id:2,x:30,y:16,type:"run"},{id:6,x:32,y:30,type:"run"},{id:"o2",x:56,y:24,type:"run"}] },
      { note:"传中进禁区：门将指挥近门柱有人，中卫 5 号抢前点解围。",
        moves:[{id:"b",x:26,y:40,type:"pass"},{id:5,x:20,y:46,type:"run"},{id:1,x:8,y:48,type:"run"}] },
      { note:"解围向边线踢出，危险解除——重新组织第二波防守。",
        moves:[{id:"b",x:60,y:10,type:"pass"},{id:9,x:44,y:44,type:"run"}] },
    ],
  },
  {
    id:"sd-trap", gameType:"field8", phase:"def", formation:"s-331", styles:["press","mid"],
    title:"边路围剿陷阱 · 关门", difficulty:2,
    summary:"故意把持球人“请”到边线，触线瞬间两人关门一人切线路——提前设计好的捕兽夹。",
    refs:["uefa-tg","fa-cap"],
    keyPoints:[
      "陷阱的耐心：先“放”他前进，急吼吼上抢就打草惊蛇",
      "关门时机：持球人触球/低头瞬间的合围，两人动作要同一拍",
      "第三人提前切所有出球线路，让陷阱里的人只能犯错",
      "抢下后第一时间从边路直塞前锋——对方防线还没回位",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:14,y:50},{id:2,num:2,team:"own",x:30,y:26},{id:3,num:3,team:"own",x:27,y:50},
      {id:4,num:4,team:"own",x:30,y:74},{id:8,num:8,team:"own",x:50,y:30},{id:6,num:6,team:"own",x:46,y:50},
      {id:10,num:10,team:"own",x:52,y:70},{id:9,num:9,team:"own",x:64,y:50},
      {id:"o1",num:1,team:"oppgk",x:6,y:50},
      {id:"o2",num:7,team:"opp",x:48,y:40},{id:"o3",num:5,team:"opp",x:44,y:50},{id:"o4",num:11,team:"opp",x:52,y:78},
      {id:"b",team:"ball",x:44,y:50},
    ],
    steps:[
      { note:"设局：10 号故意让出外侧通道，只封内线——把对方 11 号往边线“请”。",
        moves:[{id:10,x:56,y:74,type:"run"},{id:"b",x:52,y:78,type:"pass"},{id:"o4",x:52,y:78,type:"run"}] },
      { note:"11 号带球触线瞬间：10 号、2 号同一拍关门——口袋收口。",
        moves:[{id:"o4",x:44,y:84,type:"carry"},{id:"b",x:44,y:84,type:"carry"},{id:10,x:48,y:82,type:"run"},{id:2,x:34,y:66,type:"run"}] },
      { note:"第三人 6 号早已切掉中路回传线路——陷阱里的人没有任何出口。",
        moves:[{id:6,x:52,y:58,type:"run"},{id:"o2",x:46,y:48,type:"run"}] },
      { note:"被迫传向中路，6 号提前半步断球——陷阱捕获成功。",
        moves:[{id:"b",x:52,y:56,type:"pass"},{id:6,x:54,y:54,type:"run"}] },
      { note:"就地反击：6 号直塞反跑的 9 号，对方防线还没回位。",
        moves:[{id:"b",x:70,y:44,type:"pass"},{id:9,x:72,y:46,type:"run"}] },
    ],
  },
  {
    id:"sd-cp", gameType:"field8", phase:"def", formation:"s-331", styles:["press","fast"],
    title:"由守转攻 · 6 秒反抢窗口", difficulty:2,
    summary:"丢球瞬间就近两人合围、全队切线路，6 秒内夺回球权；抢不回则整体退守 mid-block——一套完整的转换预案。",
    refs:["laliga-pos","uefa-tg"],
    keyPoints:[
      "丢球后 6 秒是黄金窗口：对方刚拿球阵型散开，立刻扑上去",
      "就近两人合围持球人，其他人 3 秒内切断所有向前线路",
      "6 秒抢不回：全员体面退守中场 block，绝不追着球满场跑",
      "反抢成功就地反击——对方由攻转守的阵型还没搭起来",
    ],
    setup:[
      {id:1,num:1,team:"gk",x:14,y:50},{id:2,num:2,team:"own",x:30,y:28},{id:3,num:3,team:"own",x:27,y:50},
      {id:4,num:4,team:"own",x:30,y:72},{id:8,num:8,team:"own",x:50,y:30},{id:6,num:6,team:"own",x:48,y:50},
      {id:10,num:10,team:"own",x:50,y:70},{id:9,num:9,team:"own",x:64,y:50},
      {id:"o1",num:1,team:"oppgk",x:6,y:50},
      {id:"o2",num:7,team:"opp",x:56,y:38},{id:"o3",num:5,team:"opp",x:62,y:56},{id:"o4",num:11,team:"opp",x:44,y:60},
      {id:"b",team:"ball",x:44,y:60},
    ],
    steps:[
      { note:"丢球！最近的 6 号、10 号两秒内合围持球人 11 号——立刻反抢。",
        moves:[{id:6,x:48,y:56,type:"run"},{id:10,x:48,y:64,type:"run"}] },
      { note:"11 号被迫横传 7 号：8 号切断向中路的线路，9 号回追身后的接应点。",
        moves:[{id:"b",x:56,y:38,type:"pass"},{id:8,x:52,y:36,type:"run"},{id:9,x:60,y:44,type:"run"}] },
      { note:"7 号被迫转移 5 号，9 号预判启动——反抢范围扩大。",
        moves:[{id:"b",x:56,y:56,type:"pass"},{id:9,x:62,y:52,type:"run"},{id:"o3",x:60,y:54,type:"run"}] },
      { note:"9 号断球成功——丢球后第 4 秒重新拿回球权。",
        moves:[{id:"b",x:64,y:44,type:"carry"},{id:9,x:64,y:44,type:"carry"}] },
      { note:"直塞前插的 10 号——反抢直接转换为得分机会。",
        moves:[{id:"b",x:74,y:50,type:"pass"},{id:10,x:74,y:52,type:"run"}] },
    ],
  },
];

/* ============================================================
   训练课主题库
   结构：热身 → 技术练习 → 技能练习 → 主题对抗 SSG → 整理与提问
   ============================================================ */
const THEMES = [
  /* ---------- 五人制 ---------- */
  {
    id:"t-f-rot", gameType:"futsal", title:"4-0 轮转与接应", focus:"轮转意识 · 无球跑动 · 一线站位",
    refs:["fifa-manual","laliga-pos"],
    warm:{ name:"带球热身 + 双色接应游戏", org:"20×20m 区域，每人一球。① 5 分钟自由带球+听口令变向；② 两人一组相距 8m，互相传球后必须跑到“新的角度”再接回传——不许原地接球。", points:["接球前先扭头观察（Scanning）","传球后永远移动到新角度，不站在原地"] },
    tech:{ name:"4-0 轮转走位（无防守）", org:"半场 20×10m。四人一线站位（2 左翼、1 中、1 右翼），按“传-轮”节奏走位：横向传球 → 持球人下拉，相邻人补位。教练喊方向轮转，8 分钟一轮换。", points:["永远保持一线四点，不叠不散","轮转三字诀：有人上、有人补、有人拉","接球人张开身体，两点接球"] },
    skill:{ name:"3v2 + 第三人轮转", org:"20×14m 场地 + 小门两个。攻方 3 人对守方 2 人，进球前必须完成一次“下拉接应”（接应人从中路下拉到深位接球）。", prog:"加 1 名回追防守人变 3v3", reg:"去掉下拉条件，先自由打", points:["下拉接应制造出传球角度","利用 2v1 的瞬间做决定"] },
    ssg:{ name:"轮转计分赛 4v4", org:"半场 4v4 + 门将。规则：进球前全队完成 3 次轮转走位（教练判定）算 2 球；原地站桩传球进球只算 1 球。", points:["防守人一犹豫就是空当","被逼抢时轮转本身就是解法"] },
    ask:["刚才那次进球前，谁的跑动让防守最难受？为什么？","什么时候你觉得“没地方传球”了？那时候缺的是角度还是人？"],
  },
  {
    id:"t-f-pivo", gameType:"futsal", title:"支点运用：要位与回做", focus:"背身技术 · 做墙配合 · 后排插上",
    refs:["fifa-manual","fa-cap"],
    warm:{ name:"影子对练 + 背身保护球", org:"15×15m，两人一球。① 互相抛接地滚球；② 一人背身护球 5 秒对抗一人，交换。加“手不许张开推人”规则。", points:["护球用身体不用手","低重心、张手臂感知防守人位置"] },
    tech:{ name:"Pivo 要位三角游戏", org:"10×10m 三角形区域。Pivo 在顶点背身卡位，两侧轮流喂球，Pivo 一脚回做后转身反跑接直塞。每 3 组轮换。", points:["要位：横臂卡人、掌心示意传球侧","回做：脚弓推地滚球，力道刚好","回做后立刻转身——下一回合的杀机"] },
    skill:{ name:"2v1 支点墙式配合", org:"20×12m 通道 + 小门。Attacker 传给背身 Pivo 后前插，Pivo 回做或直塞二选一。防守人 8/10 强度。", prog:"防守人可预判回做线路", reg:"Pivo 允许两脚触球", points:["传跑同一动作：传完就跑（Movement）","Pivo 触球瞬间是启动信号（Timing）"] },
    ssg:{ name:"支点得分赛 4v4", org:"半场 4v4 + 门将。规则：经由 Pivo 回做后的进球算 3 分，普通进球 1 分。", points:["全队的进攻都要“经过支点”过一遍脑子","Pivo 是全队攻防转换的枢纽"] },
    ask:["Pivo 被两人包夹时，谁是空出来的那个人？","回做球的力度快了还是慢了？怎么判断？"],
  },
  {
    id:"t-f-wall", gameType:"futsal", title:"二过一与穿越配合", focus:"撞墙配合 · 直塞时机 · 传跑同步",
    refs:["fa-fp","fifa-manual"],
    warm:{ name:"传接球大师赛", org:"15×15m。两人一组 5 米对传 → 8 米一脚传球 → 10 米+移动中传接。最后 3 分钟“只能一脚触球”挑战。", points:["脚弓传球前的最后一步要踩到位","一脚传球的关键是提前观察（Scanning）"] },
    tech:{ name:"三角撞墙循环", org:"10×10m 三人三角。A 传 B 后前插接 B 的墙式回做，再传给 C 重复。先无防守 2 脚触球，再限 1 脚触球。", points:["传球脚法：地滚球、推内侧","传了就跑，跑的方向是“墙”的身后"] },
    skill:{ name:"2v1 穿越通道", org:"20×12m 三条通道 + 小门。进攻 2v1，得分要求：必须有一次撞墙配合穿透防守人。", prog:"防守人可回追补位", reg:"防守半强度（只封堵不抢断）", points:["撞墙时机：防守人重心压向持球人时","直塞提前量传向跑动方向"] },
    ssg:{ name:"二过一加倍赛", org:"半场 4v4 + 门将。经二过一配合后的进球翻倍计分。", points:["二过一是“两个人打一个人”的数学题","鼓励冒险：宁可失误也要尝试穿越传球"] },
    ask:["哪次二过一最漂亮？传球人做了什么让防守人上当？","防守人什么时候最容易被穿过？"],
  },
  {
    id:"t-f-build", gameType:"futsal", title:"破紧逼：门将参与构建", focus:"出球选择 · 门将脚法 · 压迫应对",
    refs:["fifa-laws","fifa-manual"],
    warm:{ name:"门将脚法专项 + 圆圈传抢", org:"① 门将单独练手抛/脚踢精度（外场练绕杆带球）；② 8 人圆圈 5v2 抢圈，两脚触球。", points:["门将出球 4 秒内完成决策","抢圈里被抢的两人才是练得最多的——那是财富"] },
    tech:{ name:"5v3 破压出球", org:"25×20m。守方 5 人（含门将）对压方 3 人，守方 10 脚传球得 1 分。门将只许出球不许再接（讲解回传规则）。", prog:"压方加 1 人变 5v4", reg:"压方减 1 人", points:["宽站位：把场子撑到最大","第三人有角度：传球-移动-再接应","被逼急了踢边线，重组织"] },
    skill:{ name:"4v4 逼抢对决", org:"半场 4v4 + 门将，守方出球过半场得 1 分；攻方 8 秒内夺回球权得 2 分。攻守 4 分钟一换。", points:["出球人要敢用弱侧脚","压迫方的重点不是抢球，是封线路"] },
    ssg:{ name:"破压得分赛", org:"半场 4v4。规则：从本方半场完成“门将-外场-射门”完整链条的进球算 3 分。", points:["门将是第十名外场球员","面对紧逼，冷静比技术更重要"] },
    ask:["对方高压时，场上最空的地方在哪？","我们丢球最多发生在什么情况下？怎么改？"],
  },
  {
    id:"t-f-trans", gameType:"futsal", title:"由守转攻：5 秒反抢", focus:"反抢意识 · 转换速度 · 就地反击",
    refs:["laliga-pos","uefa-tg"],
    warm:{ name:"反应追逐游戏", org:"20×20m。教练持球中央，四周球员听信号冲抢——练启动反应与第一步爆发。随后 3v1 抢圈热身。", points:["丢球后的第一步是心态问题，不是技术问题","抢圈用 2 脚触球模拟比赛节奏"] },
    tech:{ name:"反抢角色分工演练", org:"20×15m。4v4 断球演练：教练抛球启动，丢球方 5 秒内完成“最近上抢+第二人封线+第三人保护”。轮换角色。", points:["最近的人 2 秒内必到","反抢最多 3 人投入，其余人切线路"] },
    skill:{ name:"4v4+2 转换赛", org:"半场 4v4+2 名中立球员帮持球方。断球后 8 秒内射门成功算 2 分。", points:["断球瞬间抬头——那是对手最散的 6 秒","反击传球宁直不横"] },
    ssg:{ name:"全条件转换赛", org:"半场 4v4 + 门将。丢球方 5 秒内抢回得 2 分；抢回后 10 秒内进球再得 2 分。", points:["反抢是全队合同，不是个人英雄主义","抢不回就体面退防，别追着球满场跑"] },
    ask:["我们丢球后的第一反应是发愣还是反抢？","哪一次反抢最成功？谁先动的？"],
  },
  {
    id:"t-f-finish", gameType:"futsal", title:"终结与射门", focus:"射门技术 · 一脚终结 · 门将博弈",
    refs:["fa-fp","fifa-manual"],
    warm:{ name:"球感射门接力", org:"每人一球，带球绕 3 个标志碟后射小门；左右脚各 10 次。加入“喊出你要打的角度”口令。", points:["射门脚背绷紧、支撑脚指向目标","先练准再练狠"] },
    tech:{ name:"三种终结方式循环", org:"禁区前沿三点：① 接回做推远角；② 一次触球凌空/半凌空；③ 底线横传抢点。每点 8 球轮换。", points:["远角贴地球是成功率最高的选择","一脚终结的前提是提前观察门将位置"] },
    skill:{ name:"1v1+GK 对抗射门", org:"半场。进攻人接教练传球后 1v1 突破防守人射门，防守人 5 米外启动追防。", prog:"防守人 3 米外启动", reg:"防守人 8 米外启动", points:["利用假动作创造半步空间（Deception）","门将出击就横敲，不出击就打远角"] },
    ssg:{ name:"终结条款赛", org:"半场 4v4。进 1 球 1 分；一脚触球进球 2 分；远角进球再 +1。", points:["机会到来时犹豫就是丢机会","庆祝之前先想想能不能一脚解决"] },
    ask:["今天进的最漂亮的球是哪个？为什么能进？","门将最怕什么样的射门？"],
  },
  /* ---------- 八人制 ---------- */
  {
    id:"t-s-wing", gameType:"field8", title:"边路进攻与传中", focus:"超载配合 · 套边跑位 · 倒三角终结",
    refs:["fa-dna","rfef-8"],
    warm:{ name:"边路技术串烧", org:"40×25m。每人一球：直线带 10m → 变向内切 → 脚背横拨。两人组 15m 传接+套边跑位示范。", points:["内切变向用脚内侧拨球再加速","传中前的最后一步要减速稳住重心"] },
    tech:{ name:"边路 3 人组超载走位", org:"边路 25×15m 通道。边后卫-边中场-前锋三人按“内收-套边-斜插”固定轮转走位，教练持球发牌。", points:["三人组永远保持三角形","套边人沿着边线跑，把防守人留在内侧"] },
    skill:{ name:"4v3 边路攻击", org:"40×25m 边路区域+大目标门。4 名进攻人对 3 名防守人，要求经边路完成传中后由包抄人终结。", prog:"防守加 1 人", reg:"传中改为地滚球 easier", points:["下底线再传中：底线是倒三角的发球台","包抄三人就位：近门柱、点球点、后点"] },
    ssg:{ name:"倒三角加倍赛", org:"55×40m 7v7/8v8。倒三角回传（cutback）进球算 3 分。", points:["传中的最高目标不是门前高点，是倒三角","谁包抄、谁掩护、谁保护——各就各位"] },
    ask:["倒三角为什么比高球传中容易进球？","套边的时候你怎么知道队友会传？"],
  },
  {
    id:"t-s-central", gameType:"field8", title:"中路渗透与直塞", focus:"穿线传球 · 第三人跑动 · 肋部攻击",
    refs:["laliga-pos","fa-cap"],
    warm:{ name:"Rondo 三级挑战", org:"10×10m 抢圈 5v2 → 4v2 → 三秒一传挑战。被抢断的两人罚 5 个开合跳。", points:["抢圈练的就是“穿线”眼力和脚法","接球前的观察次数决定传球质量"] },
    tech:{ name:"穿线传球靶心练习", org:"20×15m。两名“防守人”站桩间距 3m，传球必须从两人之间穿过得 1 分；左右脚各 10 次。", points:["穿线传球路线：脚踝高度、贴地、有力","传向队友移动的方向，不是他站着的地方"] },
    skill:{ name:"第三人跑动破线", org:"30×20m 破线游戏。进攻方完成一次“第三人跑动”（A→B 回做，C 斜插接直塞）穿过中场线得 2 分。", prog:"防守自由移动", reg:"防守只许横向移动", points:["回做前锋是诱饵，第三人从盲区启动","直塞球提前量：宁大勿小"] },
    ssg:{ name:"穿线计分赛", org:"55×40m。任何一脚传球穿出“两人之间”且最终形成射门，该次进攻进球算 2 分。", points:["肋部是中路渗透的主战场","十次尝试里成功三次就是好的"] },
    ask:["今天的直塞球哪脚最好？传之前他看了哪里？","对方防线什么时候最容易被打穿？"],
  },
  {
    id:"t-s-prog", gameType:"field8", title:"整体推进：由后向前", focus:"构建组织 · 三角网络 · 门将出球",
    refs:["rfef-8","laliga-pos"],
    warm:{ name:"门将出球 + 三角传接", org:"① 门将手抛/脚踢精度练习；② 外场三人三角传球走位：传完必移动到新三角形顶点。", points:["三角滚动：持球人永远有两个接应角度","回传门将不丢人，丢球权才丢人"] },
    tech:{ name:"4v2 由后向前构建", org:"30×20m。守方 4 人（含门将）vs 压方 2 人，完成 6 脚传球后把球“推进”到中线对侧目标得 1 分。", prog:"压方 3 人", reg:"允许 3 脚触球", points:["先横向拉开再纵向推进","被压时找“第三人”——永远多一个选择"] },
    skill:{ name:"6v5 破中场线", org:"45×30m 三段区域。守方从本方底线出发，带球/传球穿越中场区到攻击三区得 2 分，直接长传绕过算 0 分（强制构建）。", points:["穿线传球比带球快","推进失败立刻反抢——构建与反抢是一体"] },
    ssg:{ name:"构建得分赛", org:"55×40m。从本方半场经 5 脚以上传递完成的进球算 3 分。", points:["推进的耐心=控球的自信","教练只在死球时提示，让球员自己解决"] },
    ask:["推进最顺的一次是怎么发起的？","什么时候该快、什么时候该慢？谁来做这个决定？"],
  },
  {
    id:"t-s-press", gameType:"field8", title:"高位逼抢与压迫触发", focus:"逼抢触发 · 整体移动 · 围剿配合",
    refs:["uefa-tg","fa-dna"],
    warm:{ name:"压迫反应游戏", org:"20×20m。5v2 抢圈升级：教练喊“触发”（某次接球停大）全员才能上抢——练对触发信号的反应。", points:["压迫是有开关的，不是满场乱跑","听/看触发信号：停大、背身、回传"] },
    tech:{ name:"整体移动走位演练", org:"半场。教练持球在对方半场不同区域，防守 8 人按“地毯原则”整体横移/前压走位，无球状态跑 8 分钟。", points:["一人动，全队动——地毯原则","封内放外：曲线跑位把球往边线赶"] },
    skill:{ name:"8v8 条件压迫", org:"全场。攻方后卫线出球，守方触发后 8 秒内夺回球权得 1 分；攻方推进过中线得 2 分。攻守 5 分钟一换。", prog:"攻方加 1 名自由人", reg:"只允许 6 名守方球员参与压迫", points:["前锋是压迫的启动键","边线是“第 11 名队友”——围剿在边线发生"] },
    ssg:{ name:"触发器实战赛", org:"55×40m。守方在对方半场夺回球权后 10 秒内进球算 3 分。", points:["压迫的目的是夺球，更是制造好机会","夺回球权的第一脚传球方向：向前！"] },
    ask:["今天我们压迫最成功的一次，触发信号是什么？","压迫失败时全队该怎么补位？"],
  },
  {
    id:"t-s-compact", gameType:"field8", title:"防守紧凑与禁区保护", focus:"三线间距 · 整体横移 · 延缓与保护",
    refs:["fa-dna","uefa-tg"],
    warm:{ name:"防守姿势与横移", org:"20×20m。① 防守滑步跟人 1v1（不抢球只跟人）；② 二人组“影子横移”：一人持球指方向，另一人保持人球之间横移。", points:["防守的第一技能是站位不是抢断","低重心、碎步、手张开"] },
    tech:{ name:"三线间距走位", org:"40×30m。防守 8 人按 mid-block 落位（间距 8-10m），教练持球移动，全队整体横移+同侧压缩走位 10 分钟。", points:["线间 8-10 米：让对手站不进两条线之间","中卫指挥：防线横移由居中中卫喊口令"] },
    skill:{ name:"5v4 禁区保护", org:"30×20m 禁区前沿区域。攻方 5 人外围倒脚找渗透或远射，守方 4 中场+后卫线保禁区。攻方进球 1 分，守方解围/断球 2 分。", points:["弧顶必须有人——远射是低位最大的漏勺","延缓（Delay）：先贴住不抢，等队友落位"] },
    ssg:{ name:"零封挑战赛", org:"55×40m。守方零封对手得 3 分奖励；被穿线传球打穿一次全队罚 10 秒原地防守滑步。", points:["紧凑防守赢在纪律不在天赋","被突破后第一反应：回追保护，不站着看"] },
    ask:["对方从哪条通道打进来最容易？","零封的时候，全队谁最关键？"],
  },
  {
    id:"t-s-counter", gameType:"field8", title:"快速反击与转换", focus:"断球决策 · 直塞时机 · 六秒原则",
    refs:["uefa-tg","fa-dna"],
    warm:{ name:"冲刺反应接力", org:"30×20m。两组听信号冲刺 15m 折返×6；随后两人组“断球-直塞”两脚出球练习。", points:["反击第一步是无氧冲刺","断球后第一脚传球只许向前"] },
    tech:{ name:"断球直塞二连", org:"30×20m。A 断教练传球后 3 秒内完成向前直塞，B/C 斜线冲刺接球。左右两侧轮换。", points:["抬头第一眼找前锋","直塞提前量传向空当不是传向人"] },
    skill:{ name:"3v2 快速反击", org:"45×30m。3 名进攻人冲 2 名退防者，6 秒内完成射门。防守从 20m 外回追。", prog:"防守 1 人提前站位", reg:"加 1 名进攻人 4v2", points:["斜线跑位拉开防守人","持球人吸引门将再分球"] },
    ssg:{ name:"六秒进球赛", org:"55×40m。断球后 6 秒内完成射门进球算 3 分。", points:["6 秒后对手落位，机会减半","反击是全队默契：谁跑、谁跟、谁保护"] },
    ask:["今天最快的一次反击用了几秒？","断球瞬间你第一眼看向哪里？"],
  },
];

/* ---------- 首页每日建议 ---------- */
const TIPS = [
  "热身一定带球做：基础阶段每名球员训练 60 分钟，触球目标不低于 600 次。",
  "讲解不超过 20 秒——超过 20 秒，孩子们的耳朵就关闭了。",
  "每项练习结束用 1-2 个提问收尾：问出来的，比讲进去的记得牢。",
  "练“传了就跑”比练“传准”更重要：跑动是免费的，球权是珍贵的。",
  "小场地（4v4）触球量是 11 人制的 3 倍以上——多打小场。",
  "表扬具体行为，不表扬天赋：说“你回做了那一下很棒”，别说“你真有天赋”。",
  "一次训练只解决一个主题：热身、技术、对抗全围绕同一个词。",
  "门将要练脚：五人制门将是第十名外场球员，出球从 U10 就开始练。",
  "输球日先谈进步再谈失误——心理社交是四角模型的一角。",
  "把「倒三角」设为全队标配：它是青训阶段性价比最高的终结方式。",
];

/* ---------- 汇总 ---------- */
const FORMATIONS = [...FUTSAL_FORMATIONS, ...FIELD8_FORMATIONS];
const PATTERNS = [...FUTSAL_ATTACK, ...FUTSAL_DEFENSE, ...FIELD8_ATTACK, ...FIELD8_DEFENSE];

const STYLE_LABELS = {
  futsal:{ atk:{possession:"控制渗透",pivot:"支点战术",fast:"快速转换"}, def:{press:"高压逼抢",zone:"区域联防",block:"收缩保护",fast:"转换反抢"} },
  field8:{ atk:{wing:"边路为主",central:"中路渗透",counter:"快速反击",possession:"控球推进",fast:"快速转换"}, def:{press:"高位逼抢",mid:"中场拦截",low:"低位保护",block:"紧凑落位",fast:"转换反抢"} },
};
